### PR TITLE
Fix "bookeepeer localbookie"

### PR DESCRIPTION
**Pull request by Shoothzj**
### Changes
- add missing `lb.start();`
- delete commented out code
- add zookeeper 4lw for easily to run/debug in ide

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

@dlg99 I think this should go in 4.15 as well

**Review by nicoloboschi — APPROVED** [review]
Good catch! 

It's a regression from https://github.com/apache/bookkeeper/pull/2901

**Review by zymap — APPROVED** [review]
The local bookie is working. but there still haven't logs.

**Comment by Shoothzj** [comment]
> The local bookie is working. but there still haven't logs.

@zymap Thanks for your attention, I will follow up on this

**Pull request merged**
