### PR TITLE
Bump grpc from 1.45.1 to 1.47.0, solve dependency check FP

### PR DESCRIPTION
**Pull request by Shoothzj**
### Changes
- Bump grpc from 1.45.1 to 1.47.0
- Bump gson from 2.8.9 to 2.9.0
- Bump perfmark-api from 0.23.0 to 0.25.0
- add dependency check suppressions

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
