### PR TITLE
bump lombok from 1.18.20 to 1.18.22 to support java17 compile

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
- required for compilation on JDK 17
- see https://projectlombok.org/changelog

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by nicoloboschi — APPROVED** [review]
I started the same kind of work here 
https://github.com/apache/bookkeeper/pull/3053

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@nicoloboschi Thanks for your attention and great work. I was trying to test #3091 on my laptop. I think we can merge this PR first to let people can run unittest with jdk17.
cc @dlg99 @eolivelli

**Review by dlg99 — APPROVED** [review]

**Comment by dlg99** [comment]
@Shoothzj merged

**Pull request merged**
