### PR TITLE
Bump vertx version from 3.9.8 to 4.3.2

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Vertx has several broken api changes. It raised error when embedded  bookkeeper with vertx application

### Changes
- Bump vertx version from 3.9.8 to 4.3.2
- Adapt vertx broken API changes

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by StevenLuMT — APPROVED** [review]
lgtm

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]
Lgtm

**Pull request merged**
