### PR TITLE
Fix the bookkeeper-server-shaded version in ledger-api doc

### PR DESCRIPTION
**Pull request by yangl**
### Motivation
image

image

### Changes

1. fix the bookkeeper-server-shaded version by  `site.latest_release`
2. fix the overview title version.

### CODE REVIEW

**Review by hangc0276 — APPROVED** [review]

**Comment by hangc0276** [comment]
@yangl Would you please rebase the master? Thanks.

**Comment by yangl** [comment]
> @yangl Would you please rebase the master? Thanks.

done.

**Review by zwOvO — APPROVED** [review]

**Comment by hangc0276** [comment]
@yangl Would you please rebase the master branch? Thanks.

**Review by dlg99 — APPROVED** [review]
LGTM but please resolve the merge conflict

**Review by shoothzj — APPROVED** [review]

**Comment by shoothzj** [comment]
Thanks for your contribution :)

**Pull request merged**
