### PR TITLE
[BUG] Fix class not found compilation failure

### PR DESCRIPTION
**Pull request by lamber-ken**
### Motivation

Fix compilation failure after merged https://github.com/apache/bookkeeper/pull/2338

image

### Changes

Fix wrong package location.

### CODE REVIEW

**Comment by lamber-ken** [comment]
@eolivelli cc, btw, can not understand why that pr build successfully? #2338

**Comment by eolivelli** [comment]
Thanks foe providing this fix.
I will check tomorrow.

@sijie merged a few PRs maybe we should have rerun these precommit tests after each merge

**Comment by lamber-ken** [comment]
## Other fixs

1. Remove this unnecessary import.
2. Log4J: Not enough arguments.

**Comment by eolivelli** [comment]
@sijie I am going to merge this patch asap

cc @rdhabalia

**Comment by eolivelli** [comment]
@lamber-ken the patch is okay.
Please stick to making the minimal change.
Do not add other commits if not necessary
This is a fast fix for master branch

**Comment by mino181295** [comment]
Okay for me!

**Comment by eolivelli** [comment]
thank you @mino181295  for taking a look

merging this fix now

**Comment by lamber-ken** [comment]
> @lamber-ken the patch is okay.
> Please stick to making the minimal change.
> Do not add other commits if not necessary
> This is a fast fix for master branch

Got, thanks 💯

**Comment by lamber-ken** [comment]
> Okay for me!

Thanks 👍

**Pull request merged**
