### PR TITLE
ISSUE-2224: Config ServerConfiguration with setAllowLoopback(true) for Unit Tests

### PR DESCRIPTION
**Pull request by coolbeevip**
### Motivation

Unit test fails when build master branch

### Changes

Config ServerConfiguration with setAllowLoopback(true) in the class GarbageCollectorThreadTest

Master Issue: #2224

### CODE REVIEW

**Comment by ArvinDevel** [comment]
run bookkeeper-server tls tests

**Comment by coolbeevip** [comment]
> run bookkeeper-server tls tests

OK，I will try it

**Comment by ArvinDevel** [comment]
> > run bookkeeper-server tls tests
> 
> OK，I will try it

I just used that command to trigger Jenkins rebuild task.
It seems that the continuous-integration still fails, but I don't know how to trigger it manually.

**Comment by eolivelli** [comment]
We have problems on travis.
I am investigating.
The problem is not in this patch

**Comment by coolbeevip** [comment]
> > > run bookkeeper-server tls tests
> > 
> > 
> > OK，I will try it
> 
> I just used that command to trigger Jenkins rebuild task.
> It seems that the continuous-integration still fails, but I don't know how to trigger it manually.

😅

**Comment by coolbeevip** [comment]
I found that checking license fails using script check-binary-license. The reason for the failure is that the 3rd party jars list in the LICENSE file does not exist in the lib directory.

e.g.

LICENSE contains the following, but these jars do not exist in bookkeeper-all-4.11.0-SNAPSHOT-bin.tar.gz

```
------------------------------------------------------------------------------------
The following bundled 3rd party jars are distributed under the
Apache Software License, Version 2.
...
- lib/io.grpc-grpc-all-1.18.0.jar [45]
- lib/io.grpc-grpc-auth-1.18.0.jar [45]
- lib/io.grpc-grpc-context-1.18.0.jar [45]
- lib/io.grpc-grpc-core-1.18.0.jar [45]
- lib/io.grpc-grpc-netty-1.18.0.jar [45]
- lib/io.grpc-grpc-okhttp-1.18.0.jar [45]
- lib/io.grpc-grpc-protobuf-1.18.0.jar [45]
- lib/io.grpc-grpc-protobuf-lite-1.18.0.jar [45]
- lib/io.grpc-grpc-protobuf-nano-1.18.0.jar [45]
- lib/io.grpc-grpc-stub-1.18.0.jar [45]
- lib/io.grpc-grpc-testing-1.18.0.jar [45]
...
```

**Comment by eolivelli** [comment]
In order to reproduce the issue you have to build with -Dstream

**Comment by eolivelli** [comment]
I have sent a pr #2228 with a fix

**Comment by coolbeevip** [comment]
> In order to reproduce the issue you have to build with -Dstream

Thank you, `mvn clean package -Dstream` has been successfully on my local machine

**Comment by eolivelli** [comment]
I have restarted Travis job.
This patch should be good to go now.

Thank you @coolbeevip

**Comment by eolivelli** [comment]
If Travis won't be ok please rebase to latest master, that has #2228

**Comment by eolivelli** [comment]
I have rebased to current master

**Comment by eolivelli** [comment]
Jenkins H30 node has problems, I have filed
https://issues.apache.org/jira/browse/INFRA-19660

**Comment by eolivelli** [comment]
rebuild java11
run bookkeeper-server client tests

**Comment by jiazhai** [comment]
rebuild java11

**Pull request merged**
