### PR TITLE
Use isEmpty method instead of size check

### PR DESCRIPTION
**Pull request by aahmed-se**
In HTTP ListLedgerService use is Empty instead of size check.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by eolivelli** [comment]
It would be good to change the description of this PR in order to make it more explicit.

Or run thru the whole codebase and seek for other similar cases.

The change looks good to me btw

**Comment by aahmed-se** [comment]
Can't see another similar changes to make.
```
Exception in thread "bookkeeper-io-22" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.ru
```

Test failures seem unrelated.

**Comment by eolivelli** [comment]
Thank you @aahmed-se . The failure is unrelated.
Please state in the PR message that the change is on http service / list ledgers, otherwise in the git log it will be confusing.

Thank you for your contribution

**Pull request closed without merging**
