### PR TITLE
fix some jdk17 test problem

### PR DESCRIPTION
**Pull request by Shoothzj**
### Changes
- add jdk17 required module opens
- bump junit5 version from 5.6.2 to 5.8.2
- bump powermock version from 2.0.2 to 2.0.9

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by zymap — APPROVED** [review]

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh PTAL

**Review by liangyuanpeng — APPROVED** [review]

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh PTAL

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
