### PR TITLE
BOOKKEEPER-901: Authentication framework

### PR DESCRIPTION
**Pull request by merlimat**

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat it seems there are files don't have apache licenses

**Comment by merlimat** [comment]
@sijie rebased and added missing license header

**Comment by sijie** [comment]
seems still failing with 

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.7:check (default-cli) on project bookkeeper-server: Too many unapproved licenses: 1 -> [Help 1]

https://builds.apache.org/job/bookkeeper-master-git-pullrequest/46/changes

**Comment by merlimat** [comment]
I see, there was still one protobuf generated file without the license header. I've added it to the rat exclusion list.

**Comment by sijie** [comment]
the Jenkins failures are unrelated. there is a ticket for investigation.

the code change looks good to me. +1

**Pull request closed without merging**
