### PR TITLE
BOOKKEEPER-998: Increased the max entry size to 5MB

### PR DESCRIPTION
**Pull request by revans2**
Full disclosure, most of these changes were actually done by @merlimat For this I am mostly just putting them back into open source.

### CODE REVIEW

**Comment by eolivelli** [comment]
@revans2 
IMHO it would be better to make it configurable as system property or in ServerConfiguration it would be even better, so it would be more "testable".
I'm not aware of some system property naming convention, maybe you can suggest one and then the discuss is open.

IMHO the max entry size can be related to the max Netty frame size but maybe we can use two different limits. For instance on the wire we need headers
@sijie what to you think ?

I think that at Salesforce they make large use of big entries (as they store BLOBs on BK), maybe JV as some number to share

For me, I'm starting a new project which will need to store "huge" (more than 10 MB) entries and so I will need to set this limit to a greater value that 5MB

**Comment by revans2** [comment]
@eolivelli Thanks I'll look at making them separate.

If someone from salesforce wants to take a look that would be great.  If they are storing large BLOBs on BK there is a high likelihood that they have similar code too.

**Comment by revans2** [comment]
@eolivelli I added in configs for both the server and the client.  Please take a look again.

**Comment by sijie** [comment]
I think 1MB limitation was coming before we used netty for the network transportation. Increasing it to 5MB sounds okay to me. I don't think it breaks any backward compatibility issue. I don't have any strong preference here on using a system property or configuration setting for it.

**Comment by jvrao** [comment]
1MB is good enough for us at least for now. Did not test anything larger.

**Comment by revans2** [comment]
Thanks everyone I moved the configs to AbstractConfiguration and squashed the commits.  Hopefully this is good to go now.

**Comment by revans2** [comment]
@eolivelli and @jvrao is there anything more I need to do to get this merged in?

**Comment by eolivelli** [comment]
For me is +1 but I am not a committer. Usually @sijie merges PR or maybe @merlimat

**Comment by jvrao** [comment]
+1 LGTM.

**Pull request closed without merging**
