### PR TITLE
fix description of BookKeeperAdmin#watchWritableBookiesChanged

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation
The implementation of  is not consistent with the description.

### Changes
fix doc.

Master Issue: https://github.com/apache/bookkeeper/issues/4253

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @hangc0276 @horizonzy @zhaijack @eolivelli @shoothzj

**Review by shoothzj — APPROVED** [review]

**Review by shoothzj — CHANGES_REQUESTED** [review]
It's actually oneshot listener. When complete, listener will be removed.

**Review by shoothzj — APPROVED** [review]

**Comment by shoothzj** [comment]
> It's actually oneshot listener. When complete, listener will be removed.

sorry, I mischecked.

**Review by horizonzy — APPROVED** [review]
LGTM

**Review by wenbingshen — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
