### PR TITLE
Use ${sha1} instead of ${ghprbActualCommit} for Pre-commit Jobs

### PR DESCRIPTION
**Pull request by eolivelli**
Descriptions of the changes in this PR:

### Motivation

According to  the documentation of the GitHub Pull Request plugin:
- ${sha1} means a commit which is the result of merging the PR branch with the target branch
- ${ghprbActualCommit} is directly the PR branch

So currently we are not testing the PR branch against the target branch, but only the branch "as it is"

see:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=2ahUKEwje0PjpnuDeAhUF2SwKHXN4BgYQFjADegQIAxAB&url=https%3A%2F%2Fwiki.jenkins.io%2Fdisplay%2FJENKINS%2FGitHub%2Bpull%2Brequest%2Bbuilder%2Bplugin&usg=AOvVaw2XvPL5ynRYnqVEWqpe9cs1

### Changes

Use ${sha1} instead of ${ghprbActualCommit} for Pre-commit Jobs

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [x] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [x] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [x] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [x] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [x] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by sijie** [comment]
@eolivelli did you actually test this change? with master and with branches. I believe ${ghprbActualCommit} was used for a reason.

**Comment by eolivelli** [comment]
@sijie no, I can change manually the jib on Jenkins and see if it works cleanly.
I can't remember why you changed it.
To me it seems better to use sha1, after re reading the docs.

I have worked on Zookeeper project  CI jobs recently, and there is sha1 there

**Comment by sijie** [comment]
> I can't remember why you changed it.

there was an email thread discussing that. I changed it to ${ghprbActualCommit} to support running jenkins jobs against PR made to branches (not master). 

If you switched back to ${sha1}, I guess you will break those PRs who made against branches. so I'd rather you test it before making this change.

${sha1} sounds promising and we also use it in pulsar. however in reality, I think we are still asking people to rebase to latest master. so I am not sure how exactly ${sha1} is working.

**Comment by eolivelli** [comment]
Il giorno lun 19 nov 2018 alle ore 22:04 Sijie Guo <notifications@github.com>
ha scritto:

> I can't remember why you changed it.
>
> there was an email thread discussing that. I changed it to
> ${ghprbActualCommit} to support running jenkins jobs against PR made to
> branches (not master).
>
> If you switched back to ${sha1}, I guess you will break those PRs who made
> against branches. so I'd rather you test it before making this change.
>
> ${sha1} sounds promising and we also use it in pulsar. however in reality,
> I think we are still asking people to rebase to latest master. so I am not
> sure how exactly ${sha1} is working.
>
${sha1} is better, it works like the script we are using for merging PRs
and it falls back to ${ghprbActualCommit} if the patch has conflicts.

I would go for ${sha1}, as I am proposing with this patch

**Comment by eolivelli** [comment]
Makes sense.
I see it working on zookkeeper.

In order to see it working on our jobs I can change manually the config and send a trial PR against vramch 4.8 so that we can have the proof.

Is this a good plan to you?

**Comment by eolivelli** [comment]
@sijie is my plan valid ? otherwise I don't know how to prove it to you. I can set up something in some other public Jenkins but it will pollute BK github repository.

**Comment by eolivelli** [comment]
@sijie  ping

**Comment by sijie** [comment]
@eolivelli go for it

**Comment by sijie** [comment]
@eolivelli 

> In order to see it working on our jobs I can change manually the config and send a trial PR against vramch 4.8 so that we can have the proof.



I thought you are going to manually change the job and verify if it is working before merging this PR.

**Comment by eolivelli** [comment]
@sijie I am really sorry. I misunderstood.
I am checking the prs of today if all went cleanly

**Comment by eolivelli** [comment]
@sijie  the seed job did not run yet so there is the old config in place

I am changing now manually tls_tests and retest a pending mergeable PR
https://builds.apache.org/job/bookkeeper_precommit_tls_tests

**Comment by eolivelli** [comment]
@sijie 
I have tryed in:
https://github.com/apache/bookkeeper/pull/1842

these are differences:
before:
https://builds.apache.org/job/bookkeeper_precommit_tls_tests/544/consoleFull
after:
https://builds.apache.org/job/bookkeeper_precommit_tls_tests/546/consoleFull

apparently with  the old job configuration there is a strage "Merge remote-tracking branch 'apache/master' into add_zookeeper_resolver" and with the new there is a "Merge a098505167c9652a39034265c1e709a6ceffbdbb into 6d4e5c806ebcb593815ce23e21762cd0672de9cc"

**Comment by sijie** [comment]
@eolivelli 

- "Merge remote-tracking branch 'apache/master' into add_zookeeper_resolver" is my commit in #1842 . It is not strange. It is actually right, because the old configuration is testing actual commit.

- the new configuration is testing sha1. 

However I think what we should do is testing PRs to branches.

**Comment by eolivelli** [comment]
@sijie thank you for giving me the explanation for that message

 sorry I did not understand your last comment. Do you mean that you are fine with the new behavior or should I revert my commit?

**Comment by sijie** [comment]
@eolivelli : #1842 is a PR based master. we should test a PR based on branches, like branch-4.8 or branch-4.7. As I commented before, I suspect the new behavior will be failing on PRs based on branches.

**Comment by eolivelli** [comment]
I will send some dummy prs

**Comment by eolivelli** [comment]
@sijie 
seems it is working fine:
https://github.com/apache/bookkeeper/pull/1846

I found the source of your concerns. We have an additional "parameter" in the job configuration ("This build is parametrized...") which is named 'sha1' and so in the "Parameters" page you will see twice the 'sha1' parameter:
```
sha1 -> master
sha1 -> origin/pr/1846/merge

```

Maybe we can drop the explicit "sha1" parameter which is messing up the view

**Pull request merged**
