### PR TITLE
Migrate command `listledgers`

### PR DESCRIPTION
**Pull request by zymap**
Descriptions of the changes in this PR:

Using `bkctl` run command `listledgers`

### Motivation

#2004

### CODE REVIEW

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Pull request merged**
