### PR TITLE
Release notes for 4.6.1

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by sijie** [comment]
@eolivelli I cherry-picked #996 into branch 4.6.1. can you update the release notes?

**Comment by eolivelli** [comment]
Sure it is an important change

**Comment by sschepens** [comment]
@sijie https://github.com/apache/bookkeeper/pull/996 included some changes that can cause errores, we've reverted them on pulsar, could you merge my new PR?

**Comment by eolivelli** [comment]
@sijie @jiazhai @merlimat 
I have updated the release notes about Netty fix.

As you already reviewed this patch please take a look again

this is the commit
https://github.com/apache/bookkeeper/pull/980/commits/f8389a64e46d48d326109499130cbfdccc73fe9e

**Comment by sijie** [comment]
@eolivelli lgtm +1

**Comment by jvrao** [comment]
+1

**Pull request closed without merging**
