### PR TITLE
Fix RegionAwareEnsemblePlacementPolicy update rack info problem.

### LINKED ISSUE #3665: RegionAwareEnsemblePlacementPolicy#onBookieRackChange didn't update perRegionPlacement.
**BUG REPORT**
RegionAwareEnsemblePlacementPolicy#onBookieRackChange didn't update perRegionPlacement.
There are 4 bookies `bookie-0`,`bookie-1`,`bookie-2`,`bookie-3`. 
The rack info: `bookie-0:us-east-1a/rack-1`,`bookie-1:us-east-1b/rack-1`,`bookie-2:us-east-1a/rack-1`,`bookie-3:us-east-1b/rack-1`.

Use pulsar-admin to update the `bookie0` rack info.
```
bin/pulsar-admin bookies set-bookie-rack --bookie bookie-0:3181 --hostname bookie-0 --rack us-east-1c/rack-1
```
After updating the rack info, the RegionAwareEnsemblePlacementPolicy log show that the `bookie0` rack is still `us-east-1a/rack-1`, not `us-east-1c/rack-1`.
```
Region us-east-1a allocating bookies with ensemble size 1 and write quorum size 1 : [bookie-0:3181]
Region us-east-1a allocating bookies with ensemble size 1 and write quorum size 1 : [bookie-2:3181]
Region us-east-1b allocating bookies with ensemble size 1 and write quorum size 1 : [bookie-1:3181]
```

### PR DESCRIPTION
**Pull request by horizonzy**
### Motivation
Fixes #3665

### CODE REVIEW

**Comment by horizonzy** [comment]
rerun failure checks

**Comment by horizonzy** [comment]
rerun failure checks

**Review by hangc0276 — APPROVED** [review]

**Comment by hangc0276** [comment]
ping @eolivelli @dlg99 @zymap @merlimat Please help take a look, thanks.

**Review by eolivelli — APPROVED** [review]
LGTM

**Pull request merged**
