### PR TITLE
compatible fix wrong key for getHttpServerTrustStorePassword

### LINKED ISSUE #3639: ServerConfiguration returns incorrect property for httpServerTrustStorePassword
**BUG REPORT**

***Describe the bug***

ServerConfiguration.getHttpServerTrustStorePassword() returns value of HTTP_SERVER_KEY_STORE_PASSWORD. Instead it should return the value of HTTP_SERVER_TRUST_STORE_PASSWORD.

***To Reproduce***

1. Set the following properties, specifying different key store and truststore files with different passwords:
httpServerTlsEnable=true
httpServerKeyStorePath
httpServerKeyStorePassword
httpServerTrustStorePath
httpServerTrustStorePassword
2. Start bookkeeper and observe the truststore password is incorrect.

***Expected behavior***

The truststore should be unlocked with its password.

***Screenshots***

N/A

***Additional context***

N/A

### PR DESCRIPTION
**Pull request by shoothzj**
Fix #3639 

### Motivation

Fix mistake typo, compatible code can be removed in next major version

### CODE REVIEW

**Comment by shoothzj** [comment]
@nicoloboschi @eolivelli @hangc0276 @merlimat @zhaijack PTAL

**Review by eolivelli — APPROVED** [review]
+1

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Comment by hangc0276** [comment]
With this concern https://github.com/apache/bookkeeper/pull/3962#discussion_r1201573602, not cherry-pick this PR to patch release. We should high light this change in the next major release.

**Pull request merged**
