### PR TITLE
Issue 534: Download docs reference old release

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

use the latest release in the download page

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/69/

**Comment by zhaijack** [comment]
Not related with this change, but CI reported errors, while TestTLS:
```
  TestTLS.setUp:110->BookKeeperClusterTestCase.setUp:116->BookKeeperClusterTestCase.startBKCluster:176->BookKeeperClusterTestCase.startNewBookie:540->BookKeeperClusterTestCase.startBookie:555 » Security
  TestTLS.setUp:110->BookKeeperClusterTestCase.setUp:116->BookKeeperClusterTestCase.startBKCluster:176->BookKeeperClusterTestCase.startNewBookie:540->BookKeeperClusterTestCase.startBookie:555 » Security
```

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
rebased this to master to force ci rebuild

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/83/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/82/

**Pull request closed without merging**
