### PR TITLE
[improve] Add auditor skipping check task times metric

### PR DESCRIPTION
**Pull request by wenbingshen**
### Motivation

When we skip some auditor check tasks, it only records a line of logs, we may miss it, so add one metric to help prompt us whether manual intervention is needed to ensure cluster data consistency.

### CODE REVIEW

**Comment by wenbingshen** [comment]
rerun failure checks

**Review by hangc0276 — APPROVED** [review]
Trigger those check tasks need to trigger auditor election.

**Comment by wenbingshen** [comment]
> Trigger those check tasks need to trigger auditor election.

@hangc0276 Yes, I noticed this tool: ForceAuditorChecksCmd, I am trying to see if I can trigger the check task without restarting Auditor or re-election.

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Pull request merged**
