### PR TITLE
[ci] [github] upload test log when fail

### PR DESCRIPTION
**Pull request by Shoothzj**
### Changes
add github actions to upload test log when fail

You can find the test log in the github actions summary
image

### CODE REVIEW

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @nicoloboschi @merlimat @pkumar-singh PTAL

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by zymap** [comment]
Is there any example showing it's working properly?  For the CI scripts, I would suggest running it on your branch to test if it is working well, then pushing it to the apache repo.

**Comment by Shoothzj** [comment]
> Is there any example showing it's working properly?  For the CI scripts, I would suggest running it on your branch to test if it is working well, then pushing it to the apache repo. 

@zymap I put the screenshot on my pr content, and I have done download it to analyze.

**Review by zymap — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
