### PR TITLE
BOOKKEEPER-1027: Cleanup README

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- Move README to README.md (written it in markdown syntax)
- Organized the README as below:
  - what is bookkeeper and what it can be used for
  - getting started
  - documentation
  - contribution

### CODE REVIEW

**Comment by sijie** [comment]
This is the attempt to improve current documentation. The content is based on current website and documentation. We can improve README later on after we improve website.

**Comment by sijie** [comment]
@eolivelli " the logo is not displaying correctly " => what do you suggest to display? the logo is a square logo. do you want just a smaller square?

**Comment by eolivelli** [comment]
Can you try with a smaller one?

**Comment by eolivelli** [comment]
Maybe we can just put the logo in the readme and use it as project logo in the Github project

**Comment by sijie** [comment]
I tried a few methods. they didn't really work. so I am not sure if we really need to resize it. but I'd prefer having a logo in README, because people don't really know what the logo it is even the project has been 6 years.

**Pull request closed without merging**
