### PR TITLE
Fix: Multiple tests failing in /stream subproject

### PR DESCRIPTION
**Pull request by dlg99**
Descriptions of the changes in this PR:

Fixed (some of) the test failures.

Other tests need more work, some of them succeed on retry, some might fail but for different reasons.
To be continued.

### Motivation

the tests shall pass

### Changes

Fixed: missing dependencies for some subprojects
Fixed: mock setup for some tests

Master Issue: #2577

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by pkumar-singh** [comment]
Looks good to me.

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
also "approved" by Prashant Kumar (see message on slack)

**Comment by eolivelli** [comment]
I have committed this patch to master and to branch-4.12.

branch-4.11 is with ZK 3.5.x to this patch cannot be applied

**Pull request merged**
