### PR TITLE
Fix batch read data in cache does not take effect

### PR DESCRIPTION
**Pull request by liudezhi2098**
Descriptions of the changes in this PR:

### Motivation

Fix batch read data in cache does not take effect

### Changes

(Describe: what changes you have made)

Master Issue: #2230 
Fixes: #2230

### CODE REVIEW

**Comment by eolivelli** [comment]
Hi.
Can you please explain your problem and the fix?

We should also add a test case to demonstrate that the fix works and in order to prevent regressions in the future.

Thank you for contributing your fix

**Comment by liudezhi2098** [comment]
HI.
Problems I found while testing pulsar consumption backtrace,
When reading historical data, you need to pull to disk. In theory, it should be batch pull, but from the phenomenon point of view, it does not. It is used in 4.9.2









Set -1 to firstEntryId and let it increment
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Enrico Olivelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 下午2:37
收件人:&nbsp;"apache/bookkeeper"<bookkeeper@noreply.github.com&gt;;
抄送:&nbsp;"Just do it "<278903642@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/bookkeeper] Fix batch read data in cache does not take effect (#2231)




Hi.
 Can you please explain your problem and the fix?
 
We should also add a test case to demonstrate that the fix works and in order to prevent regressions in the future.
 
Thank you for contributing your fix

**Comment by liudezhi2098** [comment]
retest this please

**Comment by jiazhai** [comment]
rebuild java11
run integration tests

**Comment by jiazhai** [comment]
@eolivelli  is helping fix the CI issue.

**Comment by sijie** [comment]
@eolivelli 

I think the code is obvious and the code path should have been already covered by existing tests. So this change should be good to go.

**Comment by liudezhi2098** [comment]
retest this please

**Comment by liudezhi2098** [comment]
retest this please

**Comment by eolivelli** [comment]
I am sorry but the magic comment doesn't work anymore with github actions.
I will  trigger CI manually

**Comment by eolivelli** [comment]
@liudezhi2098  can you please merge with master branch so that CI kicks in again ?
We had problems with GitHub actions, hopefully they have been solved

thanks in advance

**Pull request merged**
