### PR TITLE
[dlog] Add smoke tests for dlog library

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

This PR adds smoke tests for dlog library to cover basic functionalities like basic write/read, control-write and tailing reads.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by eolivelli** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-seed/209/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_release_branch_46/57/<h2>Build result: FAILURE</span></h2>[...truncated 417.18 KB...]2018-06-05T19:17:57.583 [INFO] Apache BookKeeper :: DistributedLog :: IO :: FileSystem SKIPPED2018-06-05T19:17:57.583 [INFO] Apache BookKeeper :: DistributedLog :: IO .......... SKIPPED2018-06-05T19:17:57.583 [INFO] ------------------------------------------------------------------------2018-06-05T19:17:57.583 [INFO] BUILD FAILURE2018-06-05T19:17:57.583 [INFO] ------------------------------------------------------------------------2018-06-05T19:17:57.583 [INFO] Total time: 03:24 min2018-06-05T19:17:57.583 [INFO] Finished at: 2018-06-05T19:17:57Z2018-06-05T19:17:58.394 [INFO] Final Memory: 114M/2565M2018-06-05T19:17:58.395 [INFO] ------------------------------------------------------------------------2018-06-05T19:17:58.407 [ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:check (default-cli) on project circe-checksum: failed with 4 bugs and 0 errors -> [Help 1]2018-06-05T19:17:58.407 [ERROR] 2018-06-05T19:17:58.407 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.2018-06-05T19:17:58.407 [ERROR] Re-run Maven using the -X switch to enable full debug logging.2018-06-05T19:17:58.407 [ERROR] 2018-06-05T19:17:58.407 [ERROR] For more information about the errors and possible solutions, please read the following articles:2018-06-05T19:17:58.407 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException2018-06-05T19:17:58.408 [ERROR] 2018-06-05T19:17:58.408 [ERROR] After correcting the problems, you can resume the build with the command2018-06-05T19:17:58.408 [ERROR]   mvn <goals> -rf :circe-checksumchannel stoppedSending e-mails to: issues@bookkeeper.apache.orgSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_release_branch_46/57/ and message: 'FAILURE 'Using context: Jenkins: Release Branch 4.6 Test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_remaining_tests/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_replication_tests/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_postcommit_validation_master/4/<h2>Build result: FAILURE</span></h2>[...truncated 1.24 MB...]2018-06-05T19:33:46.162 [INFO] Apache BookKeeper :: Stream Storage :: CLI ......... SKIPPED2018-06-05T19:33:46.162 [INFO] ------------------------------------------------------------------------2018-06-05T19:33:46.162 [INFO] BUILD FAILURE2018-06-05T19:33:46.162 [INFO] ------------------------------------------------------------------------2018-06-05T19:33:46.162 [INFO] Total time: 30:10 min2018-06-05T19:33:46.162 [INFO] Finished at: 2018-06-05T19:33:46Z2018-06-05T19:33:47.297 [INFO] Final Memory: 229M/2125M2018-06-05T19:33:47.298 [INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data2018-06-05T19:33:48.533 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (default-cli) on project smoke: You have 1 Checkstyle violation. -> [Help 1]2018-06-05T19:33:48.534 [ERROR] 2018-06-05T19:33:48.534 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.2018-06-05T19:33:48.534 [ERROR] Re-run Maven using the -X switch to enable full debug logging.2018-06-05T19:33:48.534 [ERROR] 2018-06-05T19:33:48.534 [ERROR] For more information about the errors and possible solutions, please read the following articles:2018-06-05T19:33:48.534 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException2018-06-05T19:33:48.534 [ERROR] 2018-06-05T19:33:48.534 [ERROR] After correcting the problems, you can resume the build with the command2018-06-05T19:33:48.534 [ERROR]   mvn <goals> -rf :smokechannel stoppedSending e-mails to: issues@bookkeeper.apache.orgSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_postcommit_validation_master/4/ and message: 'FAILURE 'Using context: Jenkins: Postcommit Validation

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_pullrequest_java8/1184/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_pullrequest_java9/1184/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_tls_tests/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_pullrequest_validation/20/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='bookkeeper_precommit_pullrequest_validation/org.apache.distributedlog:distributedlog-core' /><a href='https://builds.apache.org/job/bookkeeper_precommit_pullrequest_validation/20/org.apache.distributedlog$distributedlog-core/testReport'>bookkeeper_precommit_pullrequest_validation/org.apache.distributedlog:distributedlog-core</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/bookkeeper_precommit_pullrequest_validation/20/org.apache.distributedlog$distributedlog-core/testReport/org.apache.distributedlog/TestTruncate/testExplicitTruncation/'><strong>org.apache.distributedlog.TestTruncate.testExplicitTruncation</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_release_nightly_snapshot/23/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_client_tests/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_release_branch_47_java9/58/<h2>Build result: ABORTED</span></h2>[...truncated 789.38 KB...]2018-06-05T19:52:42.642 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 81 iota=892018-06-05T19:52:42.642 [INFO] 2018-06-05T19:52:42.642 [INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ vertx-http-server <<<2018-06-05T19:52:42.642 [INFO] 2018-06-05T19:52:42.642 [INFO] 2018-06-05T19:52:42.642 [INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ vertx-http-server ---2018-06-05T19:52:42.657 [INFO] Building jar: /home/jenkins/jenkins-slave/workspace/bookkeeper_release_branch_47_java9/bookkeeper-http/vertx-http-server/target/vertx-http-server-4.8.0-SNAPSHOT-sources.jar2018-06-05T19:52:42.838 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 81 iota=892018-06-05T19:52:42.839 [INFO] 2018-06-05T19:52:42.839 [INFO] >>> spotbugs-maven-plugin:3.1.0-RC6:check (default-cli) > :spotbugs @ vertx-http-server >>>2018-06-05T19:52:42.856 [INFO] 2018-06-05T19:52:42.856 [INFO] --- spotbugs-maven-plugin:3.1.0-RC6:spotbugs (spotbugs) @ vertx-http-server ---2018-06-05T19:52:42.864 [INFO] Fork Value is true     [java] WARNING: An illegal reflective access operation has occurred     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/home/jenkins/jenkins-slave/workspace/bookkeeper_release_branch_47_java9/.repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations     [java] WARNING: All illegal access operations will be denied in a future releaseBuild was abortedAborted by sijie     [java] channel stoppedSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_release_branch_47_java9/58/ and message: 'FAILURE 'Using context: Jenkins: Release Branch 4.7 Java 9 Test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_postcommit_master_java9/157/<h2>Build result: ABORTED</span></h2>[...truncated 620.08 KB...]2018-06-05T19:52:11.238 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 34 iota=892018-06-05T19:52:11.238 [INFO] 2018-06-05T19:52:11.239 [INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ twitter-finagle-provider <<<2018-06-05T19:52:11.239 [INFO] 2018-06-05T19:52:11.239 [INFO] 2018-06-05T19:52:11.239 [INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ twitter-finagle-provider ---2018-06-05T19:52:11.248 [INFO] Building jar: /home/jenkins/jenkins-slave/workspace/bookkeeper_postcommit_master_java9/bookkeeper-stats-providers/twitter-finagle-provider/target/twitter-finagle-provider-4.8.0-SNAPSHOT-sources.jar2018-06-05T19:52:11.454 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 34 iota=892018-06-05T19:52:11.454 [INFO] 2018-06-05T19:52:11.454 [INFO] >>> spotbugs-maven-plugin:3.1.0-RC6:check (default-cli) > :spotbugs @ twitter-finagle-provider >>>2018-06-05T19:52:11.465 [INFO] 2018-06-05T19:52:11.465 [INFO] --- spotbugs-maven-plugin:3.1.0-RC6:spotbugs (spotbugs) @ twitter-finagle-provider ---2018-06-05T19:52:11.470 [INFO] Fork Value is true     [java] WARNING: An illegal reflective access operation has occurred     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/home/jenkins/jenkins-slave/workspace/bookkeeper_postcommit_master_java9/.repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations     [java] WARNING: All illegal access operations will be denied in a future release2018-06-05T19:52:17.262 [INFO] Done SpotBugs Analysis....Build was abortedAborted by sijieSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_postcommit_master_java9/157/ and message: 'FAILURE 'Using context: Jenkins: Java 9 Test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_release_branch_47_java8/58/<h2>Build result: ABORTED</span></h2>[...truncated 894.80 KB...]2018-06-05T19:52:55.439 [INFO] skip non existing resourceDirectory /home/jenkins/jenkins-slave/workspace/bookkeeper_release_branch_47_java8/stream/distributedlog/protocol/src/main/resources2018-06-05T19:52:55.439 [INFO] Copying 3 resources2018-06-05T19:52:55.634 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 29 iota=892018-06-05T19:52:55.634 [INFO] 2018-06-05T19:52:55.634 [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ distributedlog-protocol ---2018-06-05T19:52:55.647 [INFO] Changes detected - recompiling the module!2018-06-05T19:52:55.647 [INFO] Compiling 53 source files to /home/jenkins/jenkins-slave/workspace/bookkeeper_release_branch_47_java8/stream/distributedlog/protocol/target/classes2018-06-05T19:52:56.342 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 29 iota=892018-06-05T19:52:56.342 [INFO] 2018-06-05T19:52:56.342 [INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ distributedlog-protocol ---2018-06-05T19:52:56.343 [INFO] Using 'UTF-8' encoding to copy filtered resources.2018-06-05T19:52:56.344 [INFO] Copying 1 resource2018-06-05T19:52:56.344 [INFO] Copying 3 resources2018-06-05T19:52:56.539 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 29 iota=892018-06-05T19:52:56.539 [INFO] 2018-06-05T19:52:56.539 [INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ distributedlog-protocol ---Build was abortedAborted by sijie2018-06-05T19:52:56.547 [INFO] Changes detected - recompiling the module!2018-06-05T19:52:56.548 [INFO] Compiling 2 source files to /home/jenkins/jenkins-slave/workspace/bookkeeper_release_branch_47_java8/stream/distributedlog/protocol/target/test-classeschannel stoppedSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_release_branch_47_java8/58/ and message: 'FAILURE 'Using context: Jenkins: Release Branch 4.7 Java 8 Test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_postcommit_master_java8/156/<h2>Build result: ABORTED</span></h2>[...truncated 672.18 KB...]2018-06-05T19:52:57.401 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/scala-json_2.9.2/3.0.1/scala-json_2.9.2-3.0.1.pom (1.9 kB at 171 kB/s)2018-06-05T19:52:57.408 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/ostrich_2.9.2/9.1.3/ostrich_2.9.2-9.1.3.jar2018-06-05T19:52:57.409 [INFO] Downloading: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar2018-06-05T19:52:57.410 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/util-core_2.9.2/6.3.7/util-core_2.9.2-6.3.7.jar2018-06-05T19:52:57.410 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/util-eval_2.9.2/6.3.7/util-eval_2.9.2-6.3.7.jar2018-06-05T19:52:57.411 [INFO] Downloading: https://repo.maven.apache.org/maven2/org/scala-lang/scala-compiler/2.9.2/scala-compiler-2.9.2.jar2018-06-05T19:52:57.435 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/util-eval_2.9.2/6.3.7/util-eval_2.9.2-6.3.7.jar (43 kB at 1.6 MB/s)2018-06-05T19:52:57.435 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/util-logging_2.9.2/6.3.7/util-logging_2.9.2-6.3.7.jar2018-06-05T19:52:57.473 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/util-logging_2.9.2/6.3.7/util-logging_2.9.2-6.3.7.jar (198 kB at 3.2 MB/s)2018-06-05T19:52:57.473 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/util-app_2.9.2/6.3.7/util-app_2.9.2-6.3.7.jar2018-06-05T19:52:57.479 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/ostrich_2.9.2/9.1.3/ostrich_2.9.2-9.1.3.jar (454 kB at 6.4 MB/s)2018-06-05T19:52:57.479 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/util-jvm_2.9.2/6.3.7/util-jvm_2.9.2-6.3.7.jar2018-06-05T19:52:57.493 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/util-app_2.9.2/6.3.7/util-app_2.9.2-6.3.7.jar (84 kB at 1.0 MB/s)2018-06-05T19:52:57.493 [INFO] Downloading: https://repo.maven.apache.org/maven2/com/twitter/scala-json_2.9.2/3.0.1/scala-json_2.9.2-3.0.1.jar2018-06-05T19:52:57.506 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/util-jvm_2.9.2/6.3.7/util-jvm_2.9.2-6.3.7.jar (164 kB at 1.7 MB/s)2018-06-05T19:52:57.511 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/scala-json_2.9.2/3.0.1/scala-json_2.9.2-3.0.1.jar (66 kB at 662 kB/s)2018-06-05T19:52:57.541 [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/twitter/util-core_2.9.2/6.3.7/util-core_2.9.2-6.3.7.jar (791 kB at 6.0 MB/s)Build was abortedAborted by sijie2018-06-05T19:52:58.287 [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar (8.9 MB at 10 MB/s)channel stoppedSetting status of b7e4577ef8ff74e342f403e2b7c34f406394b004 to FAILURE with url https://builds.apache.org/job/bookkeeper_postcommit_master_java8/156/ and message: 'FAILURE 'Using context: Jenkins: Java 8 Test

**Comment by sijie** [comment]
Closed this PR for now. will reopen when I fixed the jenkins.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_bookie_tests/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_postcommit_publish_website/358/

**Comment by sijie** [comment]
will resend the PR to get a clean list of CI jobs.

**Pull request closed without merging**
