### PR TITLE
Optimize getActiveLedgersInRange

### PR DESCRIPTION
**Pull request by AnonHxy**
Descriptions of the changes in this PR:

### Motivation

Optimize `Iterable<Long>  getActiveLedgersInRange(0, Long.MAX_VALUE)` by  avoid applying the filter predicate when traverse the `Iterable<Long>`.

There are many places call `getActiveLedgersInRange(0, Long.MAX_VALUE)`  to get the `Iterable` of all the `ledgerId`,  for example:
1. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java#L124-L125
2. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToDBStorageCommand.java#L88
3. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java#L160

We could return the keys of `ledgers` directly to avoid applying the filter predicate when traverse the `Iterable<Long>`

### Changes

Return the keys of `ledgers` directly if `firstLedgerId <=0 && lastLedgerId == Long.MAX_VALUE`

### CODE REVIEW

**Review by StevenLuMT — APPROVED** [review]
good catch,LGTM

**Review by horizonzy — COMMENTED** [review]
We would better add a new method `getAllActiveLedgers`.

**Comment by StevenLuMT** [comment]
> We would better add a new method `getAllActiveLedgers`.

Whether to change the semantics of the original method, if it is changed, it is recommended to initiate a BP to add

**Review by hangc0276 — APPROVED** [review]

**Comment by hangc0276** [comment]
> We would better add a new method `getAllActiveLedgers`.

@horizonzy This change is low risk, and I think it's ok to be put in the original method.

**Comment by horizonzy** [comment]
That's fine.&nbsp;

------------------ Original ------------------
From: Hang Chen ***@***.***&gt;
Date: Mon,Jul 3,2023 3:57 PM
To: apache/bookkeeper ***@***.***&gt;
Cc: Yan Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/bookkeeper] Optimize getActiveLedgersInRange (PR #4005)





  
We would better add a new method getAllActiveLedgers.
  
@horizonzy This change is low risk, and I think it's ok to be put in the original method.

**Review by horizonzy — APPROVED** [review]
LGTM

**Pull request merged**
