### PR TITLE
[Branch 4.14] Fix potential memory leak.

### PR DESCRIPTION
**Pull request by horizonzy**
Descriptions of the changes in this PR:
cherry-pick from #3525.

### CODE REVIEW

**Comment by horizonzy** [comment]
rerun failure checks

**Comment by horizonzy** [comment]
rerun failure checks

**Review by hangc0276 — APPROVED** [review]

**Comment by dlg99** [comment]
Bunch of TLS tests failed, I triggered re-run though these tests used to be stable

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by horizonzy** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
https://github.com/apache/bookkeeper/pull/3557
This Pr has been merged, please rebase branch-4.14, thanks.

**Comment by horizonzy** [comment]
> #3557 This Pr has been merged, please rebase branch-4.14, thanks.

Fine

**Comment by hangc0276** [comment]
rerun failure checks

**Pull request merged**
