### PR TITLE
Issue #1752: Etcd docker based tests are running on wrong jobs on CI

### LINKED ISSUE #1752: Etcd docker based tests are running on wrong jobs on CI
For instance we have this error in Java 8 job:

```
2018-10-17T22:40:33.646 [INFO] Results:
2018-10-17T22:40:33.646 [INFO]
2018-10-17T22:40:33.646 [ERROR] Errors:
2018-10-17T22:40:33.646 [ERROR]   Etcd64bitIdGeneratorTest.org.apache.bookkeeper.metadata.etcd.Etcd64bitIdGeneratorTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   EtcdClusterTest.org.apache.bookkeeper.metadata.etcd.EtcdClusterTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   EtcdCookieTest.org.apache.bookkeeper.metadata.etcd.EtcdCookieTest » NotFound {...
2018-10-17T22:40:33.646 [ERROR]   EtcdLayoutManagerTest.org.apache.bookkeeper.metadata.etcd.EtcdLayoutManagerTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   EtcdLedgerManagerTest.org.apache.bookkeeper.metadata.etcd.EtcdLedgerManagerTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   EtcdRegistrationTest.org.apache.bookkeeper.metadata.etcd.EtcdRegistrationTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   HelpersTest.org.apache.bookkeeper.metadata.etcd.helpers.HelpersTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   KeySetReaderTest.org.apache.bookkeeper.metadata.etcd.helpers.KeySetReaderTest » NotFound
2018-10-17T22:40:33.646 [ERROR]   SmokeTest.org.apache.bookkeeper.metadata.etcd.integration.SmokeTest » NotFound
2018-10-17T22:40:33.646 [INFO]
2018-10-17T22:40:33.646 [ERROR] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0
2018-10-17T22:40:33.646 [INFO]
2018-10-17T22:40:33.650 [ERROR] There are test failures.
```

### PR DESCRIPTION
**Pull request by codingwangqi**
Descriptions of the changes in this PR:

*Motivation*

Fixes #1752 

Etcd metadata driver is using testcontainer to run Etcd in containers for integration tests.
However this job is running as part normal build, which can cause container image being deleted
due to concurrent builds.

*Changes*

Move etcd metadata driver tests to be as part of `integrationTests`

Master Issue: #1752 

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
It seems to me that java8 job still run etcd tests
https://builds.apache.org/job/bookkeeper_precommit_pullrequest_java8/1653/testReport/

**Comment by codingwangqi** [comment]
@eolivelli : I don't think the jenkins changes take efforts in this PR. Those changes will only apply after this PR is merged.

**Comment by sijie** [comment]
@eolivelli @codingwangqi yes the jenkins changes are only applied when this PR is merged.

**Comment by eolivelli** [comment]
rerun integration tests

**Comment by sijie** [comment]
@eolivelli integration tests was broken at handling yahoo custom image. Ivan and me are looking into it. so you can ignore it ci to merge the PR

**Comment by sijie** [comment]
IGNORE IT CI

**Comment by eolivelli** [comment]
@codingwangqi 
I would like to invite you to the Community Meeting, so that we can talk about your experience with ETDC

@jujjuri is also interested

**Comment by codingwangqi** [comment]
@eolivelli  thank you for inviting me. however I am based in China, the time of the community meeting is too late for me. I can't attend it. sorry about that. we can probably discuss that in mailing list, I guess that works better for the whole community since that's Apache way. If you have any questions about etcd, feel free to shoot me any emails.

**Pull request merged**
