### PR TITLE
[Doc][Issue #2442] New website Project Page

### PR DESCRIPTION
**Pull request by rudy2steiner**
Descriptions of the changes in this PR:

 Update our new website project Privacy policy page

### Motivation
 
   we decide to use new website framework and skeleton to renew our website

### Changes

  Add Privacy policy 

Master Issue: #2442

### CODE REVIEW

**Review by Ghatage — APPROVED** [review]
LGTM +1
Thanks a lot for your contribution @rudy2steiner!
Looking forward to more of your work.

**Comment by rudy2steiner** [comment]
we should polish the project page where and how to place link of:
  - license
  - sponsors
  - bylaws
  - Privacy policy
   - and so on

**Review by Abhey — APPROVED** [review]

**Comment by Ghatage** [comment]
@rudy2steiner I think the misalignment of the privacy policy panel is because the above panel list has 3. If we add another panel to the list it'll center align.

**Comment by rudy2steiner** [comment]
> @rudy2steiner I think the misalignment of the privacy policy panel is because the above panel list has 3. If we add another panel to the list it'll center align.

right

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
