### PR TITLE
BOOKKEEPER-927: LedgerHandleAdv to handle disabled ledgers operation …

### PR DESCRIPTION
**Pull request by jvrao**
…throttling

BOOKKEEPER-886 missed taking care of LedgerHandleAdv.
This takes care of that issue.

Signed-off-by: Venkateswararao Jujjuri (JV) <vjujjuri@salesforce.com>

### CODE REVIEW

**Comment by jvrao** [comment]
This looks like a Jenkins issue.

/tmp/hudson2501778598612024074.sh: line 8: mvn: command not found

**Comment by merlimat** [comment]
👍

**Comment by sijie** [comment]
+1

**Comment by eolivelli** [comment]
Do we have a test case which covers this case? If not can we add it?

**Comment by sijie** [comment]
@eolivelli I don't think we have a test case for it.

**Pull request closed without merging**
