### PR TITLE
[ZooKeeper] [Conflict] Bump dropwizard metrics to zookeeper needed

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
now dropwizard metrics version is conflicted with zookeeper's metric version, which will lead to `NoClassDefError`

### Changes
- bump dropwizard metrics to 4.1.12.1
- dropwizard refract jmx to another module, adapt changes https://github.com/dropwizard/metrics/issues/1581

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by nicoloboschi — APPROVED** [review]

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by eolivelli — CHANGES_REQUESTED** [review]
Great catch

**Review by eolivelli — APPROVED** [review]

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 should this pr be contained in 4.15.0?

**Pull request merged**
