### PR TITLE
improve: replace deprecated method usage in vertx

### PR DESCRIPTION
**Pull request by shoothzj**

### CODE REVIEW

**Comment by shoothzj** [comment]
@dlg99 @eolivelli @hangc0276 @merlimat @nicoloboschi @StevenLuMT @wenbingshen @zhaijack PTAL

**Review by zymap — COMMENTED** [review]
It seems those are different method, and I didn't see they are marked deprecated? Where shows they are deprecated?

**Comment by shoothzj** [comment]
@zymap See https://github.com/eclipse-vertx/vert.x/blob/1c1619e0f289d0f33aa9325f1819f4bd4447a56c/src/main/java/io/vertx/core/http/HttpServerOptions.java#L430-L435

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Pull request merged**
