### PR TITLE
improve rocksDB

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

1. some old parameters in rocksDB is not configurable
2. the rocksDB write/read has no rate limiter

### Changes

1.rocks all old parameter change to be configurable
2.add RateLimiter feature,default closed

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
@eolivelli @pkumar-singh @zymap
If you have time, please help me review it, thank you

**Comment by mauricebarnum** [comment]
have you considered adding support to use the native RocksDB configuration file support? https://github.com/facebook/rocksdb/blob/main/java/src/main/java/org/rocksdb/OptionsUtil.java

**Comment by StevenLuMT** [comment]
> have you considered adding support to use the native RocksDB configuration file support? https://github.com/facebook/rocksdb/blob/main/java/src/main/java/org/rocksdb/OptionsUtil.java

I think it's a good idea, finished this pr, I will research that direction

**Comment by zymap** [comment]
I would suggest using the RocksDB config file directly. That will make us don't need to introduce extra configuration changes in the bookkeeper repo.

**Pull request closed without merging**
