### PR TITLE
[build] make build passes on JDK17

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

At the moment if you build the project with jdk17 there are a lot of crashes.

### Changes

* Upgrade of various plugins (spotbugs, shadow)
* Lombok upgrade
* Removed usage of `java.security.AccessControlException` which is deprecated for removal and it shows a warning during the build. Replaced with a `BookieUnauthorizedAccessException `. This could be considered a breaking change
* Removed `java.security.AccessController.doPrivileged` usage in the integrations tests because is deprecated for removal

### CODE REVIEW

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by dlg99** [comment]
@nicoloboschi we need to update maven pom files too since it is back now.

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
@dlg99 @eolivelli rebased and ported changes to maven

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
@dlg99 @eolivelli @Shoothzj PTAL

**Review by Shoothzj — APPROVED** [review]

**Comment by nicoloboschi** [comment]
@eolivelli @dlg99 checks passed, PTAL

**Review by eolivelli — APPROVED** [review]
Lgtm

**Pull request merged**
