### PR TITLE
Read ExplicitLAC in asyncReadLastConfirmed - enable ExplicitLAC in new API

### PR DESCRIPTION
**Pull request by eolivelli**
- Readers will handle explicit LAC transparently
- V2 Readers stay with old PiggyBackLAC

Descriptions of the changes in this PR:
In readLastAddConfirmed we are going to call readLac which is an RPC supported from BK 4.5 which returns both the Piggybacked LAC and the Explicit LAC.
This way readers will be able to advance their view of the LAC even in case of writers which are using ExplicitLAC.
**This change enables users of the new API to leverage ExplicitLAC**

Client which are using v2 protocol will fallback to Piggybacked LAC as readLAC is not available in v2 protocol.

### Motivation
This way new API users will be able to use ExplicitLAC

### Changes

Call LedgerHandle#asyncReadExplicitLastConfirmed inside LedgerHandle#asyncReadLastConfirmed in case of non v2 protocol.

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
run bookkeeper-server client tests

**Comment by eolivelli** [comment]
@sijie do you think this narrower patch could be a good tradeoff ?
I am not changing any protocol, no new concept.

**Comment by eolivelli** [comment]
@sijie sorry I did not see your comment

**Comment by eolivelli** [comment]
Okay @sijie I will wait for 4.10.
I have other changes about ExplicitLAC, let's release 4.9 first.

**Comment by eolivelli** [comment]
run bookkeeper-server client tests

**Comment by eolivelli** [comment]
I will send a BP with a more complete view.

**Comment by sijie** [comment]
@eolivelli : @zymap was working on fixing a problem for apache/pulsar#3828. so we might need this change. I am wondering if you are still working on this. If you already have a proposal but not start implementing it, @zymap might be able to pick up the task from your side.

**Comment by eolivelli** [comment]
@zymap @sijie do you want to pick this up ?
it would be a great step forward for the new API, but I don't have much time

**Comment by eolivelli** [comment]
@jiazhai are you interested in this work ?
If you want I can rebase to current master

cc @sijie

**Comment by sijie** [comment]
@eolivelli Yes. If you can rebase to current master, that would be super helpful! Much appreciated!

**Review by jiazhai — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@zymap have verified this change worked well in the Pulsar env. And a test is added in pulsar repo, once pulsar has this change, we could enable that test.

**Comment by jiazhai** [comment]
@sijie would you please help review this change again, there was a "change requested", and it may block the pr merge

**Comment by eolivelli** [comment]
@jiazhai I have merged with current master.
It looks like the change is so little that there was no conflict at all

if you and @sijie agree on the approach it is better that I finish the work and add more tests

**Comment by jiazhai** [comment]
Thanks @eolivelli ,  +1 for this approch

**Comment by eolivelli** [comment]
@jiazhai @sijie @zymap in Pulsar we are using DBLedgerStorage

Probably in order to fully leverage this feature we have to fix this issue (I found a reference to it in testExplicitLACIsPersisted

https://github.com/apache/bookkeeper/issues/1533

**Review by eolivelli — COMMENTED** [review]
@sijie  @jiazhai the patch is ready for review.

Please @sijie check it out, you left "request changes" status here

**Review by jiazhai — APPROVED** [review]

**Comment by sijie** [comment]
@eolivelli @jiazhai Can you cherry-pick this change to branch-4.11 and release 4.11.1? I'd like to land this change for fixing the presto read last message issue in Pulsar.

**Pull request merged**
