### PR TITLE
check all Op requests and update log

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

1. check all Op requests and update log
2. correct logs help us locate problems

### Changes

1. ForceLedgerOp: change log's level 
2. PendingReadLacOp: print coverageSet and  change log's level

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by eolivelli** [comment]
Ci failed please check

**Comment by StevenLuMT** [comment]
> Ci failed please check

ok,I rerun it,thanks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by hangc0276 — APPROVED** [review]

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
@dlg99 @eolivelli
if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@dlg99 @eolivelli
if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@dlg99 @eolivelli
if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@dlg99 @eolivelli
if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
if this pr has no problem , help me merge it ,thanks

**Review by pkumar-singh — APPROVED** [review]

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year,  if this pr has no problem , help me merge it ,thanks

**Review by liangyuanpeng — APPROVED** [review]

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by StevenLuMT** [comment]
@eolivelli
Happy new year, if this pr has no problem , help me merge it ,thanks

**Comment by pkumar-singh** [comment]
LGTM. And since approved by @eolivelli  and others so going ahead and merging it.

**Pull request merged**
