### PR TITLE
BOOKKEEPER-1089: Ledger Recovery (part-4) - allow batch reads in ledger recovery

### PR DESCRIPTION
**Pull request by sijie**
This change is based on #178 - (you can review git sha 82f73ef)

bookkeeper recovery improvement (part-4): allow batch reading in ledger recovery

    - enable batch read in ledger recovery, so we could parallel reading to improve recovery time.

    RB_ID=266145

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat ?

**Comment by eolivelli** [comment]
@sijie this patch has been reviewed and all previous commits have been merged, can you rebase ?

**Comment by sijie** [comment]
It is still blocked on #180. I already pinged on that pr. Do you mind letting me managing the merge on these patches, because they have sequence and dependencies?

**Comment by sijie** [comment]
rebased to latest master, waiting for CI to complete

**Pull request closed without merging**
