### PR TITLE
Basic function: directories to store index files

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

planning for index dir: [mail talking](https://lists.apache.org/thread/r657jf55khl59bbqltj2s95107lbkr0w)
coding for basic function : directories to store index files 

### Changes

1) DbLedgerStorage: add LedgerDirsManager init for index
2) SingleDirectoryDbLedgerStorage: add indexDirs check and default value

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by eolivelli — CHANGES_REQUESTED** [review]
Looks good
Please add tests

**Comment by hangc0276** [comment]
Please add test to cover the change

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by Shoothzj — CHANGES_REQUESTED** [review]
should we use junit5 for new tests?  @eolivelli

**Review by eolivelli — CHANGES_REQUESTED** [review]
I can't understand where the user configures this feature.

is it backward compatible ?

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
> I can't understand where the user configures this feature.
> 
> is it backward compatible ?

it's the different api : 
this is junit 5, import by org.junit.jupiter.api: 
image
image

old junit 4,import by org.junit
image
image

I think it's not necessary to expand here. we can start a mail to discuss this for bookkeeper's testcase. @eolivelli @Shoothzj

**Review by Shoothzj — APPROVED** [review]

**Comment by eolivelli** [comment]
Sorry, I wasn't clear.

My question is about how do users configure this new feature.
The feature is about having the ability to configure a separate directory to store index files, isn't it ?

So, if I have an existing bookie and I upgrade to the latest version, will the bookie continue to work ?

**Comment by StevenLuMT** [comment]
> Sorry, I wasn't clear.
> 
> My question is about how do users configure this new feature. The feature is about having the ability to configure a separate directory to store index files, isn't it ?
> 
> So, if I have an existing bookie and I upgrade to the latest version, will the bookie continue to work ?

ok, I see, just set the existed config ServerConfiguration#setIndexDirName
the new add testcase([DbLedgerStorageIndexDirTest.java](https://github.com/apache/bookkeeper/pull/3352/files#diff-cff8c7276c6d4c99c1206f51be9e8c83a5aa41245d5e74d5a41b4732671b5b5a)) has show how to open the feature

**Comment by StevenLuMT** [comment]
> > Sorry, I wasn't clear.
> > My question is about how do users configure this new feature. The feature is about having the ability to configure a separate directory to store index files, isn't it ?
> > So, if I have an existing bookie and I upgrade to the latest version, will the bookie continue to work ?
> 
> @eolivelli ok, I see, just set the existed config ServerConfiguration#setIndexDirName the new add testcase([DbLedgerStorageIndexDirTest.java](https://github.com/apache/bookkeeper/pull/3352/files#diff-cff8c7276c6d4c99c1206f51be9e8c83a5aa41245d5e74d5a41b4732671b5b5a)) has show how to open the feature

This pr is more about fixing a functional bug, and I will continue to improve the other features of indexDir, as mentioned in [mail talking](https://lists.apache.org/thread/r657jf55khl59bbqltj2s95107lbkr0w)

**Review by eolivelli — APPROVED** [review]

**Comment by StevenLuMT** [comment]
> @StevenLuMT Can you please follow up with a PR to use junit4 in the test, to make sure tests aren't skipped and work as expected?
> 
> junit5 is imported in pom
> 
> ```
>     <junit.version>4.12</junit.version>
>     
>     <junit5.version>5.8.2</junit5.version>
> ```
> 
> but it is not used in the tests
> 
> ```
> $ ggrep -rI "import org.junit.jupiter" 
> $
> ```

finished, pr:[3371](https://github.com/apache/bookkeeper/pull/3371)

**Pull request merged**
