### PR TITLE
Use netty maxDirectMemory instead of DirectMemoryUtils

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation

Our `DirectMemoryUtils` has huge limit, it can't work well with other jvm. The Netty `PlatformDependent.maxDirectMemory();` is more generic.

### Changes
Use `PlatformDependent.maxDirectMemory();` instead of `DirectMemoryUtils`

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh PTAL

**Review by dlg99 — CHANGES_REQUESTED** [review]
I don't think this is the right change. As I understand you have a situation when direct memory usage results in problems for other processes, possibly linux's OOM killer kicking in.

https://netty.io/4.1/xref/io/netty/util/internal/PlatformDependent.html#L153 describes how PlatformDependent.maxDirectMemory is controlled and used in netty. It doesn't limit direct memory for the JVM, `-XX:MaxDirectMemorySize` jvm parameter does.
The idea is to set `-XX:MaxDirectMemorySize` for the JVM and possibly limit (up to that max) for netty, 

I suggest taking a look at the shell scripts for BK for examples of  `-XX:MaxDirectMemorySize` usage and setting it to the appropriate value.
Please let me know if I misunderstood something.
.

**Comment by Shoothzj** [comment]
> 

@dlg99 Hi, We have a bookkeeper server, which is conifugred as "-Xmx6G -XDirectMemory4G". And we are using huawei jdk11. `DirectMemoryUtils` can't reed the `sun.misc.VM. maxDirectMemory`, fall back to the heap memory, which is 6G beyond the real `-XDirectMemory`.
Instead of enhace `DirectMemoryUtils`, we can use `PlatformDependent.maxDirectMemory()`

**Comment by dlg99** [comment]
Just switching to PlatformDependent.maxDirectMemory() feels like a misuse of it plus it might not work for some people if they e.g. set `io.netty.maxDirectMemory` greater than zero.
I'd try something like a configurable strategy for the DirectMemoryUtils to specify how to read the max memory (via Oracle JD specific methods, via Huawei's, via config parameter, etc)

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
> Did you copy paste the code from Netty?

Yes, I did it because that these are more genernal, and netty is under apache license.

**Comment by eolivelli** [comment]
What about sending a PR to Netty in order to expose such value?
Netty project is very open to contributions, I sent some PRs in the past.
They also have a very frequent release cycle.

I would prefer to not copy paste, because in Netty they are maintaining that code and adapt it to new Java versions, and we will keep this version forever

**Comment by Shoothzj** [comment]
@eolivelli Thanks for your advice, I will try

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 https://github.com/netty/netty/pull/12118 is merged. I will reopen this PR when we update to netty next version.

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh PTAL again.  **Netty** has exposed a util method for user to get maxDirectoryMemory. See https://github.com/netty/netty/pull/12118

**Review by eolivelli — APPROVED** [review]
Great!

**Review by nicoloboschi — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh @nicoloboschi 
Please help merge this PR when you have time, thanks :)

**Pull request merged**
