### PR TITLE
BOOKKEEPER-390 Provide support for ZooKeeper authentication

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by sijie** [comment]
@eolivelli do you mind rebasing this branch?

**Comment by eolivelli** [comment]
@sijie  rebased

**Comment by eolivelli** [comment]
@sijie  I'm going to rebase as soon as I can

**Comment by eolivelli** [comment]
@sijie  rebased to actual master

**Comment by eolivelli** [comment]
@sijie 
JIRA for documentation
https://issues.apache.org/jira/browse/BOOKKEEPER-1017

**Pull request closed without merging**
