### PR TITLE
BOOKKEEPER-748: Move fence requests out of read threads

### PR DESCRIPTION
**Pull request by sijie**
This change is moving the fence request out of current read threads and using callback to trigger scheduling read entry and also it refactors the ReadEntryProcessV3 to support long poll in the subsequent requests.

Major changes:

- change fence request to use SettableFuture
- refactor ReadEntryProcessV3: to support run fence request in callback and support long poll (in subsequent requests)
- fix stats issue: requests stats measure the latency from bookie receives the request until it sends the response.
- remove "public static final" for state fields. it is not needed for variables in Interface.

### CODE REVIEW

**Comment by sijie** [comment]
The long poll part is mainly contributed by Robin & Leigh. Please list them when merging long poll related changes.

**Comment by sijie** [comment]
The CI passed (refs/remotes/origin/pr/174/head) at https://builds.apache.org/job/bookkeeper-precommit-pullrequest/21/

**Comment by jiazhai** [comment]
This is a great feature.

**Comment by eolivelli** [comment]
I did a review on code. It looks great.
All tests are passing.
+1

**Comment by sijie** [comment]
rebased to latest master and wait CI to complete.

**Pull request closed without merging**
