### PR TITLE
WIP - Drop 'stream' and 'streamTests' profiles

### PR DESCRIPTION
**Pull request by eolivelli**
Descriptions of the changes in this PR:

### Motivation

Since 4.8 we are delivering Stream Storage library, it is time to make it a first class citizen in BookKeeper repository.
Having -Dstream and -DstreamTests profiles makes poms more complex, and it make it difficul to set tup Code coverage for such modules.

### Changes

Drop 'stream' and 'streamTests' profiles

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
@sijie  I hope I have clean up every thing ;-)

**Comment by eolivelli** [comment]
retest this please

**Comment by eolivelli** [comment]
@sijie there are spotbugs errors on stream storage, I will address them in this patch, okay ?

[INFO] Total bugs: 2
[INFO] Useless control flow in org.bookkeeper.tests.proto.rpc.PingRequest$Builder.maybeForceBuilderInitialization() [org.bookkeeper.tests.proto.rpc.PingRequest$Builder] At PingRequest.java:[line 274] UCF_USELESS_CONTROL_FLOW
[INFO] Useless control flow in org.bookkeeper.tests.proto.rpc.PongResponse$Builder.maybeForceBuilderInitialization() [org.bookkeeper.tests.proto.rpc.PongResponse$Builder] At PongResponse.java:[line 330] UCF_USELESS_CONTROL_FLOW
[INFO]

**Comment by eolivelli** [comment]
@sijie  @jvrao news on this topic ?
at the moment I think we should drop those profiles.
We are distributing Table Service now in the binary package, it is fully part of the project
For people who work every day on bookkeeper-server this change is not important but it makes simpler the build and testing process, in particular CI jobs and code coverage jobs

**Comment by sijie** [comment]
> but it makes simpler the build and testing process, in particular CI jobs and code coverage jobs

CI jobs and release process are automated already. so I don't think it is a real pain at this moment though.

But I will try to come back to this topic next week when I has more time.

**Comment by eolivelli** [comment]
Okay, actally the real problem is with the Code coverage jobs, I would have to add additinal tricks on surefire configuration in -DstreamTests because downstream poms override main surefire configuration

**Pull request closed without merging**
