### PR TITLE
[clean code]remove unused fields in bookkeeperserverstats

### PR DESCRIPTION
**Pull request by Pomelongan**
### Motivation
clean code : remove unused fields in `org.apache.bookkeeper.bookie.BookKeeperServerStats`

### CODE REVIEW

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by hangc0276 — APPROVED** [review]

**Comment by zymap** [comment]
It has some conflict when cherry-picking to other branches. Because it is a cleanup, it's ok to release with the next minor version.

**Pull request merged**
