### PR TITLE
Add code coverage report and upload to Codecov

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

Bookkeeper has already added jacoco plugin but it doesn't work in Github action, and it seems original code coverage reports are uploaded to [coveralls](https://coveralls.io/github/apache/bookkeeper?branch=master) by jenkins. Currently, we use Github action, so let's try it and switch to CodeCov.

### Changes

- Add code-coverage profile in every unit test command
- Add uploading to CodeCov github action in every module's test workflow

### CODE REVIEW

**Comment by yaalsn** [comment]
base coverage (master branch) will be updated after this PR merged.

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Review by zymap — APPROVED** [review]

**Comment by zymap** [comment]
It's better to send an email about this.

**Review by wenbingshen — APPROVED** [review]

**Comment by hangc0276** [comment]
@yaalsn Thanks for your contribution, would you please help resolve those conflicts? thanks a lot.

**Comment by yaalsn** [comment]
@hangc0276 Done, PTAL.

**Pull request merged**
