### PR TITLE
Fix the tls failed test

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

When running the tls test, the remote address is a LocalAddress,
but we cast it to the `InetSocketAddress`. That cause the test
`testConnectToLocalTLSClusterTLSClient` failed.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Great work !
LGTM

@StevenLuMT @nicoloboschi @michaeljmarshall PTAL

**Review by hangc0276 — APPROVED** [review]

**Review by StevenLuMT — APPROVED** [review]
I have verified it,it's no problem
look good to me

**Comment by zymap** [comment]
Now the TLS test has no failures
 https://pipelines.actions.githubusercontent.com/serviceHosts/18fb66ef-1cbe-4dfc-9200-fca890f3f8b2/_apis/pipelines/1/runs/42799/signedlogcontent/2?urlExpires=2022-08-18T10%3A52%3A17.3454438Z&urlSigningMethod=HMACV1&urlSignature=4OgNmMsK2ulHlnZuZnTBhmKSl3mt5X%2FBQmsYl8oUN9w%3D

**Review by Shoothzj — APPROVED** [review]

**Comment by eolivelli** [comment]
@zymap please cherry-pick to 4.15 and 4.14 branches

**Comment by zymap** [comment]
Sure

**Comment by zymap** [comment]
cherry-picked to 4.14 and 4.15

**Pull request merged**
