### PR TITLE
Upgrade rocksdb to 6.29.4.1

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation

Upgrade to newest version of RocksDb which has support for Mac with M1 architecture.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
@dlg99 if it is possible please include this in 4.15.0

**Review by nicoloboschi — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]

**Comment by hangc0276** [comment]
For the failed CI `OWASP Dependency Check`, waiting for the PR https://github.com/apache/bookkeeper/pull/3140 to be merged to the master.

**Comment by eolivelli** [comment]
cherry picked to branch-4.14

**Comment by lhotari** [comment]
6.29.5 is the most recent 6.x / 6.29.x release at the moment.  Would it make sense to upgrade to that before releasing 4.15.0 ?
https://github.com/facebook/rocksdb/releases/tag/v6.29.5

**Pull request merged**
