### PR TITLE
Issue 1262: Remove Deprecated CodahaleMetricsProvider, CodahaleOpStatsLogger and …

### PR DESCRIPTION
**Pull request by Ghatage**
…CodahaleStatsLogger classes.

### Motivation

We have deprecated these classes since 2018 and moved them to the codahale package.

### Changes

Removed the deprecated files.

Master Issue: #1262, #762

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
rerun failure checks

**Review by nicoloboschi — APPROVED** [review]
+1

**Pull request merged**
