### PR TITLE
Remove gradle build script

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Remove gradle build script
See 
https://lists.apache.org/thread/k3pdlpbvkzt061338fkxtppq3z70nk03
https://lists.apache.org/thread/os28qm4t0kf74q2k3lzsmnnpr0lnm6zc
### Changes
- delete gradle build script
- add `netty-buffer` dependency on module `distributedlog-core-shaded-test` to fix broken master tests.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
lgtm

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
the failure actions are not related to this PR.

**Comment by hangc0276** [comment]
This PR breaks the backward-compat test in CI, Please help take a look, thanks @Shoothzj 
https://github.com/apache/bookkeeper/issues/3345

**Comment by Shoothzj** [comment]
@hangc0276 I will try, my computer is still under repaired. Probably not so fast.

**Comment by hangc0276** [comment]
> @hangc0276 I will try, my computer is still under repaired. Probably not so fast.

@Shoothzj I'm not sure whether this Pr also breaks other CI tests, we'd better check it one by one.

If the backward-compat test in CI can't be repaired in a short time, I will revert the CI to gradle.

**Comment by Shoothzj** [comment]
@hangc0276 It's not worked before. See https://github.com/apache/bookkeeper/pull/2937. I will try to fix maven tests ASAP.

**Comment by hangc0276** [comment]
> @hangc0276 It's not worked before. See #2937. I will try to fix maven tests ASAP.

@Shoothzj  In gradle, it woks before.
https://github.com/apache/bookkeeper/runs/5953506864?check_suite_focus=true

**Pull request merged**
