### PR TITLE
[table service] client interceptor and storage container grpc proxy

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

This is a subsequent change after apache/bookkeeper#1428. 

*Motivation*

Current almost every grpc requests are wrapped into `StorageContainerRequest` and their responses
are wrapped into `StorageContainerResponse`. It makes things a bit complicated on adding new grpc
services.

*Changes*

To simplify things, this PR introduces two functionalities for simplifying dispatching container requests/responses.

1) *StorageContainerClientInterceptor*: A grpc `ClientInterceptor` that stamps container information (currently is `scId`) into the requests' metadata before sending the requests to the wire.

2) A simple grpc reverse proxy to dispatch grpc requests to the channels provided by a `ChannelFinder`.

*Tests*

1. Existing unit tests covered client interceptor changes.
2. Introduced a `stream-storage-tests-common` module to include common classes that would be used for testing.
3. Introduced a `PingPongService` for testing reverse proxy : unary/client-streaming/server-streaming/bidi-streaming.

Master Issue: #1205

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by jiazhai** [comment]
retest this please

**Comment by sijie** [comment]
the IT failure is unrelated. ignore IT failures.

**Comment by sijie** [comment]
IGNORE IT CI

**Pull request closed without merging**
