### PR TITLE
Catch onBookieRackChange exception

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
When we update the bookie rack info, it will use all the bookie list to update rack topology. However If one bookie update failed and throw exception out, it will throw the exception out and the remains bookie info won't be updated into the rack topology, which will affect the ledger ensemble selection.

### Changes

Catch the bookie topology update exception to ensure the remaining bookies' info can be updated into the rack topology.

### CODE REVIEW

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Review by zymap — COMMENTED** [review]
Overall looks good. Could you please add a unit test?

**Review by zymap — APPROVED** [review]

**Pull request merged**
