### PR TITLE
Fix the travis config on building dlog module

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

The original intention is building dlog module on 1) branches (non pull requests) 2) pull requests that modify dlog module. However the check logic was wrong in travis.yml. This change fixes the travis yml.

### CODE REVIEW

**Comment by sijie** [comment]
@ivankelly I was looking into some PRs' pull requests results, I realized that the check logic in travis.yml was wrong. that's why the pull requests keep running dlog tests even they don't modify dlog module. here is the fix.

**Comment by ivankelly** [comment]
retest this please // jenkins was rebooted this morning, which probably failed the test

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ivankelly** [comment]
This needs to merge master to fix the pulsar script issue

**Comment by sijie** [comment]
merged latest master

**Comment by sijie** [comment]
merged latest master (after #1158 is merged)

**Comment by sijie** [comment]
CI passed except "Integration Tests". Since this change is on touching travis.yml only, "Integration Test" is irrelevant, ignore CI to merge it.

**Comment by sijie** [comment]
IGNORE CI

**Pull request closed without merging**
