### PR TITLE
Added CLI command to start state store service without a bookie

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Allow to start a state store service process alone, without requiring to start a bookie. This is useful to have the state store to operate as a separate service, which uses BK for persistence.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Cool

+1

**Comment by eolivelli** [comment]
@dlg99 PTAL

**Comment by eolivelli** [comment]
@merlimat  we have build error

```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/bookkeeper/bookkeeper/stream/server/src/main/java/org/apache/bookkeeper/stream/server/StateStoreMain.java:[21,36] cannot find symbol
  symbol:   class BookieResources
  location: package org.apache.bookkeeper.bookie
Error:  /home/runner/work/bookkeeper/bookkeeper/stream/server/src/main/java/org/apache/bookkeeper/stream/server/StateStoreMain.java:[23,46] cannot find symbol
  symbol:   class ByteBufAllocatorWithOomHandler
  location: package org.apache.bookkeeper.common.allocator
Error:  /home/runner/work/bookkeeper/bookkeeper/stream/server/src/main/java/org/apache/bookkeeper/stream/server/StateStoreMain.java:[24,46] cannot find symbol
  symbol:   class AutoCloseableLifecycleComponent
  location: package org.apache.bookkeeper.common.component
```

**Comment by hangc0276** [comment]
@merlimat Thanks for your contribution. Would you please rebase the master? thanks.

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Pull request closed without merging**
