### PR TITLE
Issue 1630: TestHttpService#testWhoIsAuditorService is flaky

### LINKED ISSUE #1630: TestHttpService#testWhoIsAuditorService is flaky
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run "mvn clean install" on the root of 4.7.2 source distribution (it still happens on master)

- What did you expect to see?

All tests passing

- What did you see instead?

```
[ERROR] org.apache.bookkeeper.server.http.TestHttpService.testWhoIsAuditorService(org.apache.bookkeeper.server.http.TestHttpService)
[ERROR]   Run 1: TestHttpService.testWhoIsAuditorService:638 expected:<200> but was:<404>
[ERROR]   Run 2: TestHttpService.testWhoIsAuditorService:638 expected:<200> but was:<404>
[ERROR]   Run 3: TestHttpService.testWhoIsAuditorService:638 expected:<200> but was:<404>

```

the failure happens only if running the whole TestHttpService file, not the single test

### PR DESCRIPTION
**Pull request by codingwangqi**
Descriptions of the changes in this PR:

 ### Motivation

Fixes #1630. The problem is auditor elector was started async, the test itself doesn't wait until election completed.
so the test can be running before auditor runs elector.

 ### Changes

The fix is simple, just wait until auditor completes election.

Master Issue: #1630 

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
rerun bookkeper-server client tests
rerun integration-tests

**Comment by eolivelli** [comment]
rerun bookkeper-server tls tests

**Comment by eolivelli** [comment]
retest this please

**Comment by eolivelli** [comment]
I will cherry pick to 4.8

**Comment by sijie** [comment]
@eolivelli I merged it to master, branch-4.8 and branch-4.7

**Comment by eolivelli** [comment]
@sijie thank you

**Pull request closed without merging**
