### PR TITLE
Upgrade RocksDB to 5.13.1

### PR DESCRIPTION
**Pull request by merlimat**
Upgrade RocksDB version to include a fix for empty SSTs written by flushing with deleteRange() operations that cause assertion failures on DB open. 

Description can be found at : facebook/rocksdb#2717

### CODE REVIEW

**Comment by ivankelly** [comment]
A class that we use has been deprecated, so that needs to be fixed before any build will run.

**Comment by merlimat** [comment]
@sijie fixed compile errors

**Comment by sijie** [comment]
@merlimat I think there are some compilation errors for table service as well. I will try to fix them and push to this branch.

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
rerun integration tests

**Comment by eolivelli** [comment]
Do we need some note in the upgrade procedure?
Is it possible to downgrade to previous version or once the upgrade to 4.7.1/4.8.0 it is not possible to rollback?

@sijie @merlimat

**Comment by sijie** [comment]
@eolivelli I don't think there is any disk format changes. @merlimat can correct me if I am wrong.

**Comment by sijie** [comment]
rerun integration tests

**Comment by sijie** [comment]
rerun integration tests

**Comment by sijie** [comment]
rerun integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
It seems integration tests keep timed out on H30 node.

**Comment by sijie** [comment]
rick it

**Comment by sijie** [comment]
rerun integration tests

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_replication_tests/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_tls_tests/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_bookie_tests/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_remaining_tests/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_client_tests/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper_precommit_integrationtests/864/

**Comment by sijie** [comment]
finally ... the integration tests passed.  once the remaining 2 passed. will merge it to master and branch-4.7.

**Comment by sijie** [comment]
rebuild java8

**Comment by sijie** [comment]
All CI passed (the build java9 is a flaky one)

**Comment by sijie** [comment]
IGNORE CI

**Pull request closed without merging**
