### PR TITLE
ISSUE #239: typo in class name SpeculativeRequestExecutor

### PR DESCRIPTION
**Pull request by eribeiro**
Fix a simple typo in class name. It should be `SpeculativeRequestExecutor` instead of `SpeculativeRequestExectuor`.

### CODE REVIEW

**Comment by jvrao** [comment]
+1

**Comment by jiazhai** [comment]
seems merge script meet this error:
```
(master) python dev/bk-merge-pr.py
git rev-parse --abbrev-ref HEAD
Which pull request would you like to merge? (e.g. 34): 240
Traceback (most recent call last):
  File "dev/bk-merge-pr.py", line 555, in <module>
    main()
  File "dev/bk-merge-pr.py", line 466, in main
    pr_reviewers = get_reviewers(pr_num)
  File "dev/bk-merge-pr.py", line 450, in get_reviewers
    reviewers_emails.append('{0} <{1}>'.format(username, useremail))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
```

**Comment by eolivelli** [comment]
@jiazhai I think that the problem is in dealing with the name of @sigee which contains non-ascii 7bit characters

**Comment by sigee** [comment]
@eribeiro, Sorry. I'm hungarian. My name contains special characters. Would you like me to remove them from my name?

**Comment by eolivelli** [comment]
@sigee the problem is not for @eribeiro, it is only for our internal commit/merge/push procedure. we will update it.
At every commit we add in the log all the 'reviewers' with their name. There "merge script" (dev/bk-merge-pr.py) does not handle it.
We need to create an issue and then a fix for the script, if you want you can do it

**Comment by eolivelli** [comment]
@sigee @jiazhai this is the issue #241

**Comment by jiazhai** [comment]
@eolivelli. thanks for the info. @sigee, From my view, your name certainly have no error, we will fix the merge script soon.  :)

**Pull request merged**
