### PR TITLE
  Move the result of the BKCTL to the console by default

### PR DESCRIPTION
**Pull request by SunDapeng1**
### Changes

  Move the result of the BKCTL to the console

Master Issue: #2236

### CODE REVIEW

**Comment by SunDapeng1** [comment]
run bookie tests

**Comment by SunDapeng1** [comment]
run Bookie Tests

**Comment by SunDapeng1** [comment]
Run metadata driver tests

**Comment by SunDapeng1** [comment]
Run Integration Tests

**Comment by SunDapeng1** [comment]
run integration tests

**Comment by SunDapeng1** [comment]
retest this please

**Comment by eolivelli** [comment]
With github actions magic comments do not work anymore.

**Comment by SunDapeng1** [comment]
retest this please

> With github actions magic comments do not work anymore.

How should I rerun the failed test？ I'm not familiar with github actions，thanks

**Comment by eolivelli** [comment]
Only committers (people with write access) can trigger the execution.
I have done it for you.
I will follow up.
If CI fails constently maybe your patch has problems.
Did you run all of the integration tests locally ?
This patch is changing the output of bkctl and this can trigger test failures on integration tests

**Comment by eolivelli** [comment]
can you please rebase to latest master ?

**Comment by eolivelli** [comment]
I have closed/reopened the PR in order to bulk restart all tests

**Comment by SunDapeng1** [comment]
Some threads exist too short time, causing  `EntryLogTests` failed which occurs very frequently. Therefore, I adjusted the thread waiting time. I don’t know if this is correct, but  it was effective in my local test

**Pull request merged**
