### PR TITLE
Issue 935: Issue 915: Part 3 - Make circe-checksum module work for both java 8 and java 9

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

    - switch from jmockit to mockito, and from testng to junit. make testing and mocking framework consistent across modules.
    - skip `-Werror` check in circe-checksum since `finalize` is deprecated at java 9
    - change CRC32CDigestManager to use `circe-checksum` module
    - fix shading to include `circe-checksum`

This change is based #917 . Gitsha 73049f8 contains the changes to make circe-checksum module work for both java8 and java9.

### CODE REVIEW

**Comment by jvrao** [comment]
@sijie  what is the benefit of this change?

**Comment by sijie** [comment]
@jvrao 

is your question for benefits of moving pulsar-checksum to bookkeeper? or benefits of making it run with java8 and java9?

for "benefits of moving pulsar-checksum to bookkeeper": since pulsar depends on bookkeeper, this module is used for both bookkeeper and pulsar, it is making sense for pushing this module down to bookkeeper, so it doesn't have recursive dependency.

for "benefits of making it run with java8 and java9": currently the CI validates the builds at both java9 and java8. I need to make changes to make this checksum module can be compiled and run at both java9 and java8.

Hope this explains your question here.

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
Merging this change is blocked by #952. Because nar/g++ doesn't work when CI workspace path contains spaces.

**Pull request closed without merging**
