### PR TITLE
Upgrade Netty to 4.1.104.Final and io_uring to 0.0.24.Final

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Keep Netty and Netty's io_uring libraries up-to-date. 

Release notes since last upgrades:
Netty:
- https://netty.io/news/2023/12/15/4-1-104-Final.html
- https://netty.io/news/2023/12/13/4-1-103-Final.html
- https://netty.io/news/2023/11/09/4-1-101-Final.html
- https://netty.io/news/2023/10/10/4-1-100-Final.html
- https://netty.io/news/2023/09/21/4-1-99-Final.html
- https://netty.io/news/2023/09/21/4-1-98-Final.html
- https://netty.io/news/2023/08/23/4-1-97-Final.html
- https://netty.io/news/2023/07/27/4-1-96-Final.html
- https://netty.io/news/2023/07/20/4-1-95-Final.html
io_uring: 
- https://netty.io/news/2023/11/17/io_uring_0-0-24-Final.html
- https://netty.io/news/2023/10/02/multiple_releases_incubator.html

### Changes

- Upgrade Netty to 4.1.103.Final (from 4.1.94.Final)
- Upgrade Netty io_uring to 0.0.24.Final (from 0.0.21.Final)

### CODE REVIEW

**Comment by lhotari** [comment]
@hangc0276 It would be nice to have this included for 4.17 .

**Comment by lhotari** [comment]
4.1.103 is broken on MacOS on Intel. Let's wait for a fix to this issue in Netty: https://github.com/netty/netty/issues/13728

**Comment by lhotari** [comment]
Upgraded to 4.1.104 which fixes the issue in 4.1.103

**Review by hangc0276 — APPROVED** [review]

**Comment by hangc0276** [comment]
> @hangc0276 It would be nice to have this included for 4.17 .

@lhotari Sure, I add it to the 4.17 milestone

**Pull request merged**
