### PR TITLE
Spammy log when one bookie of ensemble is down (4.11 porting) 

### PR DESCRIPTION
**Pull request by nicoloboschi**
Descriptions of the changes in this PR:
Porting of #2285 PR on 4.11 branch

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
I don't know why github actions do not kick in

**Comment by eolivelli** [comment]
It looks like  that this branch does not build.

```
[INFO] Finished at: 2020-09-21T14:42:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bookkeeper-server: Compilation failure: Compilation failure: 
[ERROR] /Users/enrico.olivelli/dev/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java:[2462,51] cannot find symbol
[ERROR]   symbol:   variable bookieId
[ERROR]   location: class org.apache.bookkeeper.proto.PerChannelBookieClient.ConnectionFutureListener
[ERROR] /Users/enrico.olivelli/dev/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java:[2466,51] cannot find symbol
[ERROR]   symbol:   variable bookieId
[ERROR]   location: class org.apache.bookkeeper.proto.PerChannelBookieClient.ConnectionFutureListener
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Review by eolivelli — CHANGES_REQUESTED** [review]
please fix build issue

**Review by eolivelli — APPROVED** [review]
I am able to build this branch locally

+1

**Review by sijie — APPROVED** [review]

**Pull request merged**
