### PR TITLE
NP check for print BookieSocketAddress and a better format

### PR DESCRIPTION
**Pull request by rudy2steiner**
Descriptions of the changes in this PR:

### Motivation

NP check for print BookieSocketAddress and a better format to fix issues #2376 and #2371

### Changes
* NP check for print BookieSocketAddress on listbookies command
* A better format mentioned on #2376 

Master Issue: #2376 #2371

### CODE REVIEW

**Comment by rudy2steiner** [comment]
@mikecaat @sntfrc @sijie

**Comment by mikecaat** [comment]
@rudy2steiner 
Thanks for making a patch!
I think it's better to change its test code.

Since it's related to this fix, why don't you fix the dependencies of the doc and the source code?
Let me know if I should make another pull request for this change. It's ok.
https://github.com/mikecaat/bookkeeper/commit/3c1123a62e00f558d9c4fb5518ad38a7c44908f2

**Comment by rudy2steiner** [comment]
@eolivelli you mean to add a test case for an invalid hostname in BookieSocketAdress instance?

**Comment by rudy2steiner** [comment]
@mikecaat  you may continue your pr, this pr don't change the command input, it just wants to handle some exception

**Comment by rudy2steiner** [comment]
@eolivelli  I just mix an unknown hostname on bookieids, if none of the tests will be failed, proving that we can handle unknown hostname in bookieid gracefully.

**Pull request merged**
