### PR TITLE
Rerun the failed tests by comments

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Currently, non-committers cannot rerun the failure tests, we need to
provide the ability to let non-committer to rerun the failed tests.
I wrote a Github Actions that can rerun the failed test by comments
`rerun failure tests` and add it to the bookkeeper ci process.

### CODE REVIEW

**Comment by zymap** [comment]
Before merging this pull requests. We need to add a secrets named `BOT`. Using the default token can not trigger the another action. Can anyone help me?
https://github.community/t5/GitHub-Actions/Push-from-Action-does-not-trigger-subsequent-action/td-p/37872

**Comment by eolivelli** [comment]
@sijie do you know how to help?
Shall we ask INFRA

**Comment by sijie** [comment]
@eolivelli we need to ask INFRA for doing that. You can search the INFRA jiras to find my JIRA ticket created for Pulsar.

**Comment by eolivelli** [comment]
@sijie I will try to do it

**Comment by eolivelli** [comment]
I have created a ticket to INFRA (INFRA-20170)

**Comment by eolivelli** [comment]
@zymap which token should I give to INFRA ?
one of my personal tokens ? 
what permissions should I give to it ?

**Comment by eolivelli** [comment]
According to the guide you posted we need a 
`Please create a personal access token in repo setting(write permission accordingly)`

@sijie shall I ask INFRA to create a "repository token" ?

**Comment by zymap** [comment]
> @zymap which token should I give to INFRA ?

@eolivelli I am not sure about this. @sijie Could you help with this?

**Comment by sijie** [comment]
@eolivelli 

> create a "repository token" ?

I am not sure how to do it. How does "repository token" work?

**Comment by eolivelli** [comment]
@zymap the token is ready.
Can you please check and test it?
Or should I merge this patch now?

**Comment by eolivelli** [comment]
@zymap committed to master branch

can you please test it ?

**Pull request merged**
