### PR TITLE
[TEST] Test rerun command for the CI

### PR DESCRIPTION
**Pull request by zymap**
### Motivation

DO NOT MERGE THIS.

This is a PR for testing CI cmd

### CODE REVIEW

**Comment by eolivelli** [comment]
@zymap which is the correct command to use ?
FYI INFRA is pinging me in order to know if the TOKEN is okay
do you think it is configured properly?

**Comment by zymap** [comment]
rerun failure checks

**Comment by zymap** [comment]
@eolivelli the command to rerun the failure test is `rerun failure checks`. I am trying to verify the rerun command is ok. I will ping you if the command is ok.

**Comment by zymap** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
rerun failure checks

**Comment by zymap** [comment]
rerun failure checks

**Comment by zymap** [comment]
Hi @eolivelli, it's working now. Could you help me to test it? Just need to comment `rerun failure checks` then you should see the failed test is triggered. Thank you.

**Comment by zymap** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
erun failure checks

**Comment by eolivelli** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
@zymap it looks like this is working now.
I will close the issue on INFRA

thank you very much

please send an email to dev@ in order to announce this feature !

**Comment by zymap** [comment]
Greate! I will close this test PR.

**Pull request closed without merging**
