### PR TITLE
Fix CI is not failed when test have errors

### PR DESCRIPTION
**Pull request by zymap**
---

### Motivation

We added the test coverage to report the tests status. But when we use the code-coverage profile, it will ignore test failure because we set `<testFailureIgnore>true</testFailureIgnore>`.

### CODE REVIEW

**Review by hangc0276 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by zymap** [comment]
I am trying to fix the test https://github.com/zymap/bookkeeper/pull/20

The interesting thing is, the tests get passed on my local

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by horizonzy — APPROVED** [review]
LGTM.

**Review by merlimat — APPROVED** [review]

**Pull request merged**
