### PR TITLE
stage 8: bugfix indexDirs for LedgersIndexCheckOp

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

planning for index dir: [mail talking](https://lists.apache.org/thread/r657jf55khl59bbqltj2s95107lbkr0w)
stage 8 : 
1)  fix indexDirs for LedgersIndexCheckOp

### Changes

1.  bugfix indexDirs for LedgersIndexCheckOp
2. add index's testcase for LedgersIndexCheckOp

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by dlg99 — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
