### PR TITLE
Bump prometheus client version to 0.15.0

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
prometheus client `0.8.1` is release on Jan,2020, Keep update

### Changes
Bump prometheus client version from 0.8.1 to 0.15.0

### Test
Update prometheus client to 0.15.0, compare the metrics txt, the results are same.

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@dlg99 @nicoloboschi @eolivelli @merlimat PTAL

**Review by dlg99 — APPROVED** [review]
LGTM

**Pull request merged**
