### PR TITLE
Migrate command `updatecookie`

### PR DESCRIPTION
**Pull request by zymap**
Descriptions of the changes in this PR:

#2059 

### Description

Provide some admin operation about cookie

```
Command to update cookie

Usage:  bkctl cookie admin [flags]

Flags:

    -d, --delete
        Delete cookie both locally and in zooKeeper

    -e, --expandstorage
        Add new empty ledger/index directories

    -f, --force
        Force delete cookie

    -host, --hostname
        Expects config useHostNameAsBookieID=true as the option value

    -l, --list
        List paths of all the cookies present locally and on zooKeeper


    -h, --help
        Display help information
```

### Changes

Update command `updatecookie` to `admin`

### CODE REVIEW

**Comment by zymap** [comment]
run pr validation

**Comment by zymap** [comment]
rebuild java8
run bookkeeper-server bookie tests

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run bookkeeper-server replication tests

**Comment by zymap** [comment]
run bookkeeper-server replication tests

**Comment by jiazhai** [comment]
run pr validation
run integration tests
run bookkeeper-server bookie tests

**Comment by jiazhai** [comment]
run integration tests
run bookkeeper-server bookie tests

**Comment by zymap** [comment]
@jiazhai I'm fixing command `triggerauditor`,  this command has pr validation error. I'll fix this after another command merged.

**Pull request merged**
