### PR TITLE
Issue 2593: Run license check as part of CI

### LINKED ISSUE #2593: Run license check as part of CI
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Run license check as part of CI

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

must-have
Not running this as part of the CI makes it easy to miss; de-facto we are relying on the memory and attention span of a few committers. 

3. Provide any additional detail on your proposed use case for this feature.

https://github.com/apache/bookkeeper/issues/2592

### PR DESCRIPTION
**Pull request by eolivelli**
Run license check against all binary artifacts that we are going to release.

Fixes #2593

### CODE REVIEW

**Comment by eolivelli** [comment]
This is still a draft, waiting for #2592

**Comment by eolivelli** [comment]
@dianacle IMO you can merge this patch with yours in order to validate your work at #2592

**Review by dlg99 — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]
+1

**Pull request closed without merging**
