### PR TITLE
Open ledger returns no ledger exception if ledger id is negative

### PR DESCRIPTION
**Pull request by codingwangqi**
Descriptions of the changes in this PR:

### Motivation

if I open a ledger with negative value, bookkeeper client responds 'NoSuchLedgerException'. But I think it should return `IllegalOpException`, because it is an illegal exception.

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
Current implementation is better.
In the future we are going to support the full 64bit range of values for ledgerid.

So I think we should not change this exception type

**Comment by sijie** [comment]
@codingwangqi good catch. I think some discussions are required for this line.

@eolivelli I was actually looking into the the implementation. it seems that we treat every validation failure as 'NoSuchLedgerException'. It seems to be a problem to me, because if someone drops some other validation logic in `validate`, it will still be treated as `NoSuchLedgerException`, then it becomes wrong.

```
if (!validate()) {
                cb.openComplete(BKException.Code.NoSuchLedgerExistsException, null, null);
                return;
            }
```

`validate` should probably just return a proper rc code.

```
int rc = validate();
if (Code.OK != rc) {
    cd.openComplete(rc);
   return;
}
```

**Comment by eolivelli** [comment]
@sijie I agree with you.


But the specific case of id < 0 is fine to me, to throw NoSuchLedger because actually no ledger exists.
 In the (near) future we will have such cases of id < 0 so there no strong reason to change the behavior now.

Okay to work on other validation cases.

**Comment by sijie** [comment]
@eolivelli sure. I didn't suggest changing `id < 0` to a different result code. but I think we need to fix the implementation there, it is going to be a problem.

**Comment by codingwangqi** [comment]
@sijie @eolivelli thank you; will update the PR based on @sijie suggestion

**Comment by codingwangqi** [comment]
@sijie @eolivelli I followed what Sijie suggested and changed the code. Can you guys help review it again?

**Comment by sijie** [comment]
rebuild java8
run integration tests
run bookkeeper-server others tests

**Comment by sijie** [comment]
run bookkeeper-server other tests

**Comment by sijie** [comment]
run integration tests
run bookkeeper-server other tests

**Comment by sijie** [comment]
run bookkeeper-server remaining tests

**Comment by eolivelli** [comment]
rerun integration tests

**Pull request closed without merging**
