### PR TITLE
Make bookkeeper-server module buildable on jdk10

### PR DESCRIPTION
**Pull request by eolivelli**
Upgrade lombok and javadoc plugin to latest versions.
This way it is possible to work on most of the modules using JDK10.

### CODE REVIEW

**Comment by eolivelli** [comment]
Unfortunately Nar plugin is not still compatible with JDK10, see 
https://github.com/maven-nar/nar-maven-plugin/issues/313

With this minimal upgrade of Lombok, which is a javac annotation processor it is possible to work with an IDE which is running on JDK10 on bookkeeper-server module and other modules which do not use nar-plugin

**Comment by sijie** [comment]
there are some CI complains, please take a look

**Comment by eolivelli** [comment]
IGNORE CI

**Comment by eolivelli** [comment]
jenkins seems broken, failure is not related to the change
merging this one

**Comment by sijie** [comment]
@eolivelli it might be nice to have a travis CI coverage on building at jdk10. it doesn't have to run the tests, just make sure it can be built on jdk10.

**Comment by eolivelli** [comment]
Currently it it not possible due a problem in nar plugin.

**Pull request closed without merging**
