### PR TITLE
Recycle AddRequest/AddResponse objects

### PR DESCRIPTION
**Pull request by ivankelly**
This change was originally afd0ecb6 & 75bf0fa1 on the yahoo-4.3 branch

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/149/

**Comment by ivankelly** [comment]
yup, I have the findbugs fixed locally, but waiting to push to the parent PR first.

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by sijie** [comment]
#664 is merged. this change should be ready to merge once it is rebased.

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Pull request closed without merging**
