### PR TITLE
ISSUE #2640: BP-43 Migrate bookkeeper client tests to gradle

### PR DESCRIPTION
**Pull request by pkumar-singh**
### Motivation
Sometimes ago gradle was introduced to Bookkeeper, 
and with that build and release capabilities were built in Bookkeeper with gradle. But we never migrated bookkeeper to gradle.

Taking a first step towards gradle migration; This PR migrate all client unit tests of bookkeepr-server module to gradle 
### Changes
Replace maven test target with gradle

Master Issue: #2640

This is copy of the approved PR https://github.com/apache/bookkeeper/pull/2800

As github somehow is giving 404 with https://github.com/apache/bookkeeper/pull/2800 while merging it.

### CODE REVIEW

**Comment by hsaputra** [comment]
rerun failure checks

**Review by dlg99 — APPROVED** [review]

**Comment by hsaputra** [comment]
rerun failure checks

**Review by hsaputra — APPROVED** [review]
LGTM +1

**Review by merlimat — APPROVED** [review]

**Comment by hsaputra** [comment]
rerun failure checks

**Comment by hsaputra** [comment]
rerun failure checks

**Review by jerrypeng — APPROVED** [review]

**Pull request merged**
