### PR TITLE
Issue #2124: Test 'ListBookiesCommand ' is failing

### PR DESCRIPTION
**Pull request by mino181295**
Introduced and fixed the tests involving the ListBookiesCommand

### CODE REVIEW

**Comment by eolivelli** [comment]
I wonder why we did not see such failure while committing the original patch

**Comment by eolivelli** [comment]
CI is broken
"unable to access 'https://github.com/apache/bookkeeper.git/': Could not resolve host: github.com"

**Comment by eolivelli** [comment]
retest this please

**Comment by eolivelli** [comment]
run bookkeeper-server replication tests

**Comment by eolivelli** [comment]
run bookkeeper-server bookie tests

**Comment by eolivelli** [comment]
rebuild java11

**Comment by eolivelli** [comment]
run integration tests

**Comment by eolivelli** [comment]
The fix is quite straightforward I hope we can commit it soon and fix CI integration tests

**Comment by eolivelli** [comment]
run integration tests

**Comment by eolivelli** [comment]
rebuild java11

**Comment by eolivelli** [comment]
@ivankelly integration tests are now failing with 

```
+ docker network prune -f --filter 'name=testnetwork_*'
Error response from daemon: Invalid filter 'name'
Build step 'Execute shell' marked build as failure
```

**Comment by eolivelli** [comment]
rebuild java11
run integration tests
run bookkeeper-server bookie tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by eolivelli** [comment]
@jiazhai can you merge this patch please?

**Pull request merged**
