### PR TITLE
chore: reduce executable permissions on non-executable files

### PR DESCRIPTION
**Pull request by hezhangjian**
### Motivation

This patch aims to modify the permissions of various files within the BookKeeper repository that currently have executable permissions set (755) but do not require such permissions for their operation. Changing these permissions to 644 enhances security and maintains the consistency of file permissions throughout the project.

### Changes

Change `bk_server.conf` `standalone.conf` from 755 to 644

### CODE REVIEW

**Comment by shoothzj** [comment]
@nicoloboschi @eolivelli @hangc0276 @merlimat @zhaijack PTAL

**Comment by shoothzj** [comment]
@nicoloboschi @eolivelli @hangc0276 @merlimat @zhaijack PTAL

**Comment by shoothzj** [comment]
@dlg99 @eolivelli @hangc0276 @merlimat @nicoloboschi @zhaijack PTAL

**Review by eolivelli — APPROVED** [review]
+1

**Comment by hangc0276** [comment]
We can change the file mode here to prevent the following files from configuring the wrong permissions.
https://github.com/apache/bookkeeper/blob/e5300a0a2cbee6f50e20e24e79d1927d6500652a/bookkeeper-dist/src/assemble/bin-server.xml#L34-L36

**Pull request merged**
