### PR TITLE
Remove Twitter libraries:

### PR DESCRIPTION
**Pull request by eolivelli**
- Twitter Stats Providers
- Twitter Http Server

Descriptions of the changes in this PR:
- Drop all stats providers used only by Twitter and Twitter Http server 
- Fix BookKeeper Server packaging, it did not include Netty epoll transport Linux binding (no .so file)
- Adapt license stuff accordingly  
- Drop third party libs needed by Twitter stuff, most notably: Scala runtime and Netty 3.10

### Motivation

Those modules are apparently no more in use and especially they are no more mantained.
It is better to remove them, the code is still on git, but we won't be building it any more or bundling  useless third party libraries in our releases. 

### Changes
- remove twitter stats providers
- remove twitter http server
- adjust LICENSE file for binary distribution (bookkeeper-all)
- fix pom.xml files
- remove -Dtwitter from release files
- remove -Dtwitter from bin/common.sh
- remove other links to Twitter stuff in current documentation 

Master Issue: #<master-issue-number>

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java11]: skip build on java11. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
We have a problem in LICENSE checker,
btw I have to remove other references to third party libraries

**Comment by eolivelli** [comment]
run bookkeeper-server client tests
run integration tests

**Comment by eolivelli** [comment]
Jenkins H30 node has problems, I have filed 
https://issues.apache.org/jira/browse/INFRA-19660

**Comment by eolivelli** [comment]
run bookkeeper-server client tests
run integration tests

**Comment by eolivelli** [comment]
run bookkeeper-server client tests
run integration tests

**Comment by eolivelli** [comment]
@sijie Travis is failing with this error
I think it depends on the version of Ruby on Travis.

Can we merge this patch and fix the website builder problem in another patch ?
It would be great for me if you can take a look, I am totally new to Jekyll and Ruby, it will take a lot of time for me 

```
Warning: the lockfile is being updated to Bundler 2, after which you will be unable to return to Bundler 1.
Bundle complete! 3 Gemfile dependencies, 29 gems now installed.
Bundled gems are installed into `./vendor/bundle`
rm -rf _site local-generated generated_site
JEKYLL_ENV=production bundle exec jekyll build \
	--config _config.yml,_config.apache.yml
bundler: failed to load command: jekyll (/home/travis/build/apache/bookkeeper/site/vendor/bundle/ruby/2.4.0/bin/jekyll)
Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/lockfile_parser.rb:95:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:72:in `new'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:72:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:200:in `new'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:200:in `to_definition'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:12:in `evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:33:in `build
```

The License stuff should be okay 
```

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:17 min
[INFO] Finished at: 2020-01-05T13:04:19Z
[INFO] ------------------------------------------------------------------------
$BK_HOME/dev/check-binary-license ./bookkeeper-dist/all/target/bookkeeper-all-*-bin.tar.gz;
$BK_HOME/dev/check-binary-license ./bookkeeper-dist/server/target/bookkeeper-server-*-bin.tar.gz;
$BK_HOME/dev/check-binary-license ./bookkeeper-dist/bkctl/target/bkctl-*-bin.tar.gz;
```

**Comment by sijie** [comment]
@eolivelli sure

**Comment by eolivelli** [comment]
IGNORE CI

**Pull request merged**
