### PR TITLE
BOOKKEEPER-948: Provide an option to add more ledger/index directorie…

### PR DESCRIPTION
**Pull request by rithin-shetty**
…s to a bookie

This change allows the addition of new ledger and index directories to a bookie. Thus
increasing ts storage capacity. The option is exposed via 'allowStorageExpansion'
boolean configuration option. Also, the newly added directories need to be empty to be
accepted. Two new test cases have been added to test this functionality.

### CODE REVIEW

**Comment by eolivelli** [comment]
For my use cases I prefer this implementation. Maybe we can add a command line tool too.
Usually I distribute BookKeeper as emedded library and so without standard CLI tools

**Comment by sijie** [comment]
@eolivelli I am fine with an option on startup. how about moving the expanding logic into a until function, so that this function can be used on startup and a command line too. /cc @rithin-shetty

**Comment by eolivelli** [comment]
@sijie +1 for the utility function to be used at startup, my wish is to let ledgers dirs be expanded (add new directories) without errors

**Comment by rithin-shetty** [comment]
@sijie , I've uploaded the latest changes with the bookie shell command. Please have a look.

**Comment by sijie** [comment]
@rithin-shetty LGTM. +1

**Comment by rithin-shetty** [comment]
@eolivelli does this look good to you ?

**Comment by eolivelli** [comment]
@rithin-shetty LGTM +1

**Comment by rithin-shetty** [comment]
@sijie let me know if you need anything else from me before you can merge this PR.

**Comment by sijie** [comment]
@rithin-shetty sorry for late response. LGTM. merged the pr.

**Pull request closed without merging**
