### PR TITLE
Move bookkeeper-stats and bookkeeper-stats-providers as submodules of stats

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motiviations
Fix todo to make the project layout more reasonable and easier to fix bug/dev new feature
### Changes
move `bookkeeper-stats` and `bookkeeper-stats-providers` as submodules of `stats`

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by dlg99** [comment]
Overall LGTM with one catch:

This will change names of dependencies (org.apache.bookkeeper:bookkeeper-stats-providers -> org.apache.bookkeeper.stats:bookkeeper-stats-providers) thus will require a code change/rebuild in the projects that relies on that part of BK.

@eolivelli Any risks that I missed? I can get it into 4.15.0 RC1 if I merge this tomorrow

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by dlg99 — APPROVED** [review]

**Comment by Shoothzj** [comment]
@nicoloboschi @merlimat @pkumar-singh PTAL

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Pull request merged**
