### PR TITLE
Release notes for 4.10

### PR DESCRIPTION
**Pull request by eolivelli**
Please only consider this commit https://github.com/apache/bookkeeper/commit/0d91a95f306031d85c6a8195b0e6d73523cbfc0a as it contains the release notes.
The previous commit is only the preparation for the website.

### CODE REVIEW

**Comment by eolivelli** [comment]
@merlimat it seems that the website lacks the Release info about 4.9.2.
I am going to update this patch and add the release date of 4.9.2.
https://bookkeeper.apache.org/releases/#latest-release

I have also updater reporter.apache.org abount 4.9.2

**Comment by eolivelli** [comment]
@sijie @merlimat 
I have set the release date of 4.10.0 and for 4.9.2.

https://github.com/apache/bookkeeper/pull/2165/commits/72c06a0b368e4f1cd1b9ccfcd765e22b92289617

can you please merge this PR ?
this way the website will be updated and we can announce 4.10.0 to the public

**Comment by sijie** [comment]
run bookkeeper-server replication tests

**Comment by eolivelli** [comment]
run bookkeeper-server bookie tests
run bookkeeper-server replication tests

**Pull request merged**
