### PR TITLE
Issue 468: Introduce JMH for micro benchmarking

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- add a `test/jmh` module for micro-benchmarking
- add a protocol related test: serializing and deserializing requests

### CODE REVIEW

**Comment by sijie** [comment]
A simple comparison between serializing AddEntry requests in v2 and v3.

```
# Run complete. Total time: 00:20:33

Benchmark                         (size)   Mode  Cnt     Score     Error   Units
ProtocolBenchmark.testAddEntryV2      10  thrpt   50  5512.282 ±  93.379  ops/ms
ProtocolBenchmark.testAddEntryV2     100  thrpt   50  5527.793 ±  93.601  ops/ms
ProtocolBenchmark.testAddEntryV2    1000  thrpt   50  5637.913 ± 158.577  ops/ms
ProtocolBenchmark.testAddEntryV2   10000  thrpt   50  5504.068 ±  91.632  ops/ms
ProtocolBenchmark.testAddEntryV3      10  thrpt   50  3140.595 ± 132.859  ops/ms
ProtocolBenchmark.testAddEntryV3     100  thrpt   50  2869.691 ± 100.109  ops/ms
ProtocolBenchmark.testAddEntryV3    1000  thrpt   50  1912.591 ±  52.075  ops/ms
ProtocolBenchmark.testAddEntryV3   10000  thrpt   50   386.187 ±  11.246  ops/ms
```

**Comment by jiazhai** [comment]
Great work. Seems there is some checking error regarding the generated files in [CI](https://travis-ci.org/apache/bookkeeper/jobs/268156269)

**Comment by sijie** [comment]
@jiazhai I excluded the jmh generated code from findbugs.

**Comment by merlimat** [comment]
@sijie there's also the flag `-prof gc` that will measure the allocation rate

**Comment by jiazhai** [comment]
Bring in some conflicts while merge other PR, @sijie Would you please help fix them?

**Comment by sijie** [comment]
@merlimat yeah. I am thinking of running this jmh test on pull requests to verify if any changes introduce any performance degradation or increasing gc allocations. I am not sure if there is a stable approach to do that. I will give it a try.

**Pull request closed without merging**
