### PR TITLE
[Security] Upgrade Netty to 4.1.63.Final

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- addresses several CVEs

### Changes

- Upgrade Netty to 4.1.63.Final
- Upgrade netty-tcnative-boringssl-static to 2.0.36.Final
- adapt API deprecation in PooledByteBufAllocator API

### CODE REVIEW

**Review by dlg99 — CHANGES_REQUESTED** [review]
Overall LGTM but  the build is failing because some methods got deprecated in newer build:

```
Warning:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java:[81,51] defaultTinyCacheSize() in io.netty.buffer.PooledByteBufAllocator has been deprecated
Warning:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java:[75,44] PooledByteBufAllocator(boolean,int,int,int,int,int,int,int,boolean) in io.netty.buffer.PooledByteBufAllocator has been deprecated
```

Please fix these.

**Comment by lhotari** [comment]
> Overall LGTM but the build is failing because some methods got deprecated in newer build:
> 
> ```
> Warning:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java:[81,51] defaultTinyCacheSize() in io.netty.buffer.PooledByteBufAllocator has been deprecated
> Warning:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java:[75,44] PooledByteBufAllocator(boolean,int,int,int,int,int,int,int,boolean) in io.netty.buffer.PooledByteBufAllocator has been deprecated
> ```
> 
> Please fix these.

I have rebased the PR and fixed this problem.

**Comment by lhotari** [comment]
We have been doing a joint debugging session with @dlg99 . 
One of the observations is that TLSv1.3 doesn't throw SSLHandshakeException for certificate issues and that's the reason for TestTLS.testHandshakeFailure failing. See https://stackoverflow.com/a/62465859 for details.

**Comment by lhotari** [comment]
I'm running an experiment where TLSv1.3 is excluded from TLS protocols, commit is https://github.com/lhotari/bookkeeper/commit/6003a374 .

TLSv1.3 has been enabled by default since Netty 4.1.52.Final (when the JDK contains TLSv1.3). TLSv1.3 support has been available in Java 8 since 8u262 .
The handshake protocol in TLSv1.3 is different than in TLSv1.2 as explained in https://stackoverflow.com/a/62465859 . This difference isn't handled in Bookkeeper production code and test code.

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by dlg99 — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by lhotari** [comment]
> should we update default config with this?
> What's the risk of connecting with tls1.3 currently?
> will the BK simply fail later / on read?

The issue is more about lack of test coverage with TLS 1.3 . The main observable difference is in handshake and the main impact is that the FAILED_TLS_HANDSHAKE_COUNTER won't catch certificate issues on TLSv1.3 ([more details in the dev mailing list answer](https://lists.apache.org/thread.html/r5c246bbac0d29a10ca4b4921bb8c18b2bb8a6424f764d244f4f587cf%40%3Cdev.bookkeeper.apache.org%3E)) . I guess we cannot be sure about the behavior until there is test coverage in place.

**Pull request merged**
