### PR TITLE
Account Apache Thrift and Http Client files in LICENSE files - Fix build on Travis

### LINKED ISSUE #2227: Travis is failing with an error about LICENSE files
**BUG REPORT**

***Describe the bug***
CI Travis jobs fail due to a validation error reported by check-binary-license script.
The error is on current master and on 4.10 branch

```
org.apache.httpcomponents-httpclient-4.4.1.jar unaccounted for in LICENSE
org.apache.httpcomponents-httpcore-4.4.1.jar unaccounted for in LICENSE
org.apache.thrift-libthrift-0.9.3.jar unaccounted for in LICENSE

```

***To Reproduce***

Just run this script from the command line (it will build BookKeeper and perform the license checj)
.travis_scripts/build.sh

***Expected behavior***

No error is reported

***Additional context***

Those files are needed by distributed-core module and they seem to be needed in order to make the Stream Storage service to run (it is using DistributedLog).

I can reproduce the problem locally and consistently and the reported error seems real.
Maybe Travis started to fail after an upgrade of Maven ?

### PR DESCRIPTION
**Pull request by eolivelli**
fixes #2227

Descriptions of the changes in this PR:
- Account Thrift and Http client in LICENSE files.
- Force using Maven 3.6.3 in MacOSx builds on Travis
- Test only with -Dstream profile

### Motivation

Those files are inside the binary packages but they are not taken into account in LICENSE file.
Travis started to report errors when Travis updated Maven version to 3.6.2 in Linux machines, MaxOSx machines are still with 3.3.9 and the build does not bundle all of the needed jars ! 

Master Issue: #2227 

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [x] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [x] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [x] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [x] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [x] [skip build java11]: skip build on java11. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
With this fix the LICENSE file is good in case of STREAMDISABLED=false

https://travis-ci.org/apache/bookkeeper/jobs/630331451?utm_medium=notification&utm_source=github_status

We have to make a choice: 
- validate only with -Dstream (the release script builds binaries with -Dstream)
- have separate LICENSE files in case of -Dstream and without -Dstream

@sijie what's your take ?

I would go for simply validating with -Dstream 
In the future I would like to get rid of -Dstream but that's another story

**Comment by jiazhai** [comment]
+1 for " simply validating with -Dstream"

**Comment by eolivelli** [comment]
It looks like the build is failing on Mac (xcode builds on Travis)

**Comment by eolivelli** [comment]
I think that the cause is the maven version, on Mac we have 3.3.9, on Linux we see 3.6.2

**Comment by eolivelli** [comment]
I have added a tweak to download Maven 3.6.3

**Comment by eolivelli** [comment]
cherry picked to branch-4.10 as it is fixing a license issue

**Pull request merged**
