### PR TITLE
fix #2416 bookie format redundant clean ledgerDirs and indexDirs

### LINKED ISSUE #2416: bookie format redundant clean ledgerDirs and indexDirs
https://github.com/apache/bookkeeper/blob/ddfeaf9a11fc82cb3b1225a5754285435f2f7fab/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java#L1563

I think it maybe a mistake and should put outside the loop of clean journalDirs, as shown below:

```
        for (File journalDir : conf.getJournalDirs()) {
            String[] journalDirFiles =
                    journalDir.exists() && journalDir.isDirectory() ? journalDir.list() : null;
            if (journalDirFiles != null && journalDirFiles.length != 0) {
                try {
                    boolean confirm = false;
                    if (!isInteractive) {
                      
                        confirm = force;
                    } else {
                        confirm = IOUtils
                                .confirmPrompt("Are you sure to format Bookie data..?");
                    }
                   
                    if (!confirm) {
                        LOG.error("Bookie format aborted!!");
                        return false;
                    }
                } catch (IOException e) {
                    LOG.error("Error during bookie format", e);
                    return false;
                }
            }
            if (!cleanDir(journalDir)) {
                LOG.error("Formatting journal directory failed");
                return false;
            }
            
        }

        File[] ledgerDirs = conf.getLedgerDirs();
        for (File dir : ledgerDirs) {
            if (!cleanDir(dir)) {
                LOG.error("Formatting ledger directory " + dir + " failed");
                return false;
            }
        }

        // Clean up index directories if they are separate from the ledger dirs
        File[] indexDirs = conf.getIndexDirs();
        if (null != indexDirs) {
            for (File dir : indexDirs) {
                if (!cleanDir(dir)) {
                    LOG.error("Formatting ledger directory " + dir + " failed");
                    return false;
                }
            }
        }
```

### PR DESCRIPTION
**Pull request by HashZhang**
bookie format redundant clean ledgerDirs and indexDirs

### CODE REVIEW

**Comment by eolivelli** [comment]
can you please rebase to current master ?

**Comment by HashZhang** [comment]
> can you please rebase to current master ?

rebased

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]

**Comment by eolivelli** [comment]
as pointed out by @fpj 
tests are failing but github is reporting "all checks have passed"
https://github.com/apache/bookkeeper/pull/2417/checks?check_run_id=1174551641

**Review by sijie — APPROVED** [review]

**Pull request merged**
