### PR TITLE
General docs cleanup (WIP)

### PR DESCRIPTION
**Pull request by lucperkins**
There are a few docs that I feel like could use a bit of sprucing up (mostly in terms of wording). This is currently a WIP that I'll be adding to over the next week or so.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/25/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/103/

**Comment by sijie** [comment]
@lucperkins are you still working on this? or do you want us to go with these changes first?

**Comment by lucperkins** [comment]
@sijie I'm going to close this PR for now. There is some cleanup that I'd like to do but these changes are very old, so probably best to just start from scratch.

**Pull request closed without merging**
