### PR TITLE
Issue 463: Improve bookkeeper unit test

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- remove `timeout` on individual tests, instead setting globalTimeout on base test `BookKeeperClusterTestCase` to simplify managing timeout on individual tests
- use maven docker build to run unit tests
- zookeeper cluster uses port 0

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by sijie** [comment]
using `docker` to run the tests seems to be much stable:

https://builds.apache.org/job/bookkeeper-test/19/
https://builds.apache.org/job/bookkeeper-test/16/

**Comment by sijie** [comment]
https://builds.apache.org/view/B/view/BK/job/bookkeeper-precommit-pullrequest-docker/1/console

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/2/

**Pull request closed without merging**
