### PR TITLE
Fix the broken links and links to archive pages from README files

### PR DESCRIPTION
**Pull request by hsaputra**
Descriptions of the changes in this PR:

There are some broken and obsolete archive links in the README. Update them to point to latest Documentation site.

### Motivation

(Explain: why you're making that change, what is the problem you're trying to solve)

Update the README to point to latest info of the project.

### Changes

(Describe: what changes you have made)

Update the links in the main and Docker README files to point to right information.

Master Issue:N/A

### CODE REVIEW

**Comment by hsaputra** [comment]
I just removed some info from README file that could be easily be found from the Doc site.

**Review by eolivelli — APPROVED** [review]
Lgtm
Thanks!

**Comment by eolivelli** [comment]
I will merge on Monday

**Comment by hsaputra** [comment]
Thx for the review, @eolivelli. I can merge it if you do not mind

**Comment by eolivelli** [comment]
Sure. Go ahead

**Pull request merged**
