### PR TITLE
[CI] Using master action code for checking rerun commands

### PR DESCRIPTION
**Pull request by zymap**
The rerun checks CI can not use ref to get all failure test actions. So I change to use sha of the commits to get all failure test actions to rerun. https://github.com/zymap/bot/pull/3/files

### CODE REVIEW

**Comment by zymap** [comment]
@eolivelli PTAL.Thanks.

**Comment by eolivelli** [comment]
Isn't it better to stick to a tag instead of your master branch?
If you push something to your master branch it will affect our builds without notice

**Comment by zymap** [comment]
Ok, I change it to use the v1.0.1.

**Comment by eolivelli** [comment]
I will merge as soon as CI ends.
Please ping me if you see that I still haven't done it

**Comment by eolivelli** [comment]
@zymap I have committed to master branch.
Thank you

**Pull request merged**
