### PR TITLE
Security Vulnerabilities in CentOS 7 image, Upgrade image to CentOS 8…

### PR DESCRIPTION
**Pull request by gaddamas**
Security Vulnerabilities in CentOS 7 image, Upgrade image to CentOS 8 #2746

Descriptions of the changes in this PR:
Update base image to CentOS 8

### Motivation

(Explain: why you're making that change, what is the problem you're trying to solve)
Fix security vulnerabilities.

### Changes

(Describe: what changes you have made)

Master Issue: #<master-issue-number>

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
+1

**Comment by gaddamas** [comment]
Failure on integration test:
[ERROR] Failed to execute goal on project metadata-stores-etcd: Could not resolve dependencies for project org.apache.bookkeeper.metadata.drivers:metadata-stores-etcd:jar:4.15.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.bookkeeper:bookkeeper-server:jar:4.15.0-SNAPSHOT, org.apache.bookkeeper:bookkeeper-common:jar:tests:4.15.0-SNAPSHOT, org.apache.bookkeeper:bookkeeper-server:jar:tests:4.15.0-SNAPSHOT: org.apache.bookkeeper:bookkeeper-server:jar:4.15.0-SNAPSHOT was not found in https://repository.apache.org/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]

**Comment by eolivelli** [comment]
I have restarted the job

@lhotari can you please take a look to this patch ?

**Comment by eolivelli** [comment]
@gaddamas the patch is good to go.
We need another reviewer to validate the patch before merging it.

@sijie @fpj @merlimat @Ghatage PTAL

**Comment by eolivelli** [comment]
@gaddamas  did you try locally the new image ?

**Comment by gaddamas** [comment]
> @gaddamas did you try locally the new image ?

I am testing it, will not be merging until my local testing is complete.

**Comment by dlg99** [comment]
@eolivelli @gaddamas @lhotari It's been awhile. What's the consensus on the base image?

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Review by StevenLuMT — APPROVED** [review]
lgtm

**Comment by Shoothzj** [comment]
Now we have migrated to ubuntu, close this PR

**Pull request closed without merging**
