### PR TITLE
Optimized debug log enable

### PR DESCRIPTION
**Pull request by wenbingshen**
### Motivation

As the title.

### CODE REVIEW

**Comment by yaalsn** [comment]
Why not adjust log level to print debug logs?

**Comment by wenbingshen** [comment]
rerun failure checks

**Comment by wenbingshen** [comment]
> Why not adjust log level to print debug logs?

@yaalsn Why adjust the log level? Debug logs are generally only dynamically enabled and used when troubleshooting is required.

**Comment by hangc0276** [comment]
@wenbingshen Would you please explain the improvements of this change?

**Review by merlimat — APPROVED** [review]

**Comment by wenbingshen** [comment]
@merlimat Thanks for your explanation and review! :)

**Pull request merged**
