### PR TITLE
stage 5: bugfix indexDirs for readLedgerIndexEntries

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

planning for index dir: [mail talking](https://lists.apache.org/thread/r657jf55khl59bbqltj2s95107lbkr0w)
stage 5 : 
1)  fix indexDirs for EntryLocationIndex's tool

### Changes

1.  bugfix indexDirs for EntryLocationIndex's tool
2. add index's testcase for testReadLedgerIndexEntries
3. bugfix findexDirs for TestBase

### CODE REVIEW

**Review by dlg99 — APPROVED** [review]

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by Shoothzj — APPROVED** [review]

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]

**Comment by StevenLuMT** [comment]
run failure checks

**Comment by StevenLuMT** [comment]
run failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Pull request merged**
