### PR TITLE
BOOKKEEPER-1074: Remove JMX Bean

### PR DESCRIPTION
**Pull request by sijie**
This change is based on #160 , the change here is: gitsha [b3be81f](https://github.com/sijie/bookkeeper/commit/b3be81fadae50f2d4a2e938c2735fa35c6c31421)

### CODE REVIEW

**Comment by eolivelli** [comment]
For me is +1
I am using stats loggers to get JMX stats too

@jvrao @merlimat @revans2 are you OK for dropping this ?

**Comment by merlimat** [comment]
This was an obsoleted sets of stats that was superseded by the stats loggers. All the info should be accessible from there already.

**Comment by eolivelli** [comment]
ping @jvrao

**Comment by eolivelli** [comment]
@sijie this PR needs rebase

**Comment by sijie** [comment]
@eolivelli I will rebase and merge it.

**Comment by sijie** [comment]
rebased.

**Comment by eolivelli** [comment]
@sijie I will merge this

**Comment by reddycharan** [comment]
@jvrao @sijie we are using JMX not just for metrics (getters) but also for invoking actions, like forcecompact, forceflush,.. It is the easiest way to do out-of-band inter process communications for administrative/management purpose.

**Pull request closed without merging**
