### PR TITLE
Remove LedgerMetadata#getEnsembles in favour of #getAllEnsembles

### PR DESCRIPTION
**Pull request by ivankelly**
They do the same thing except that #getEnsembles returns a TreeMap
while #getAllEnsembles returns a NavigableMap.

LedgerMetadata#getAllEnsembles is part of the api interface.

Master issue: #281

### CODE REVIEW

**Comment by ivankelly** [comment]
rerun integration tests
rerun pr tests

**Comment by ivankelly** [comment]
rerun pr validaiton

**Comment by ivankelly** [comment]
rerun pr validation

**Comment by sijie** [comment]
run bookkeeper-server replication tests

**Comment by sijie** [comment]
IGNORE IT CI

**Pull request merged**
