### PR TITLE
fix openLedgerRereplicationGracePeriod default value doc

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
`openLedgerRereplicationGracePeriod` default value doc doesn't consistent with the code

### Changes
1. update default value doc for bk_server.conf

### CODE REVIEW

**Comment by hangc0276** [comment]
rerun failure checks

**Review by codelipenghui — APPROVED** [review]

**Comment by hangc0276** [comment]
rerun failure checks

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Comment by hangc0276** [comment]
@eolivelli  PTAL

**Review by eolivelli — APPROVED** [review]
LGTM

**Pull request merged**
