### PR TITLE
Migrate command `ledgermetadata`

### PR DESCRIPTION
**Pull request by zymap**
Descriptions of the changes in this PR:

Using `bkctl` run command `ledgermetadata`

### Motivation

#2018

### CODE REVIEW

**Comment by zymap** [comment]
rebuild java8
run integration tests

**Comment by sijie** [comment]
@zymap  there is a spotbugs error. Can you take a look and fix it?

```
[INFO] --- spotbugs-maven-plugin:3.1.8:check (default-cli) @ bookkeeper-server ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[ERROR] Unread field: org.apache.bookkeeper.bookie.BookieShell$LedgerMetadataCmd.serDe [org.apache.bookkeeper.bookie.BookieShell$LedgerMetadataCmd] At BookieShell.java:[line 1085] URF_UNREAD_FIELD
```

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by sijie** [comment]
@zymap can you rebase this PR?

**Comment by zymap** [comment]
@sijie sure

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run bookkeeper-server bookie tests
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by zymap** [comment]
run integration tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run integration tests
run bookkeeper-server bookie tests
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run bookkeeper-server bookie tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run bookkeeper-server bookie tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by sijie** [comment]
run bookkeeper-server remaining tests
run bookkeeper-server bookie tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Comment by zymap** [comment]
run bookkeeper-server remaining tests

**Pull request merged**
