### PR TITLE
Add fencing to recovery reads to avoid data loss issue

### PR DESCRIPTION
**Pull request by Vanlightly**
Descriptions of the changes in this PR:

### Motivation

Adding the fencing flag to recovery reads avoids a data loss scenario as described in [issue 2614](https://github.com/apache/bookkeeper/issues/2614)

### Changes

Added the fencing flag to recovery reads. Refactored some mocking unit test code to introduce fencing and allow two writers to share the same bookie state. Added a new unit to verify the fix. You can recreate the initial problem by removing the fencing flag from recovery reads and running the new unit test.

Master Issue: #2614

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM 

@dlg99 please take a look, probably it is worth to pick this fix for 4.13.0

**Comment by eolivelli** [comment]
@Vanlightly PR validation failed. PTAL 


Thank you very much for sharing your findings and also provide a fix

**Review by dlg99 — APPROVED** [review]
@Vanlightly it is an awesome catch and the fix lgtm.
One note about the test: often reliance on Thread.sleep() leads to test flakiness. 
Can I ask you to try to remove these and replace with wait for completion of specific events?

**Comment by dlg99** [comment]
Another note: NoSuchLedger/NoSuchEntry have special handling in PendingReadLacOp/RoundRobinDistributionSchedule, see https://github.com/apache/bookkeeper/issues/2612
Is it possible to repro case when at lac N write N+1 is lost?

**Comment by Vanlightly** [comment]
Yes of course. I'll take a look at both suggestions.

**Comment by Vanlightly** [comment]
@dlg99 I've replaced the Thread.sleep with CompletableFutures to ensure the right sequence is followed in a non-flaky way.

Regarding the issue #2612, I've left a comment there. Basically the protocol is not designed to handle arbitrary failures of that kind and data loss can result. In terms of this particular issue, which is not an arbitrary failure scenario, I think the current test is probably enough.

**Comment by dlg99** [comment]
@Vanlightly Thank you! The changes lgtm.

**Comment by eolivelli** [comment]
pushed to master branch and to branch-4.12.

thank you very much @Vanlightly 

I believe you are now unblocked in sending the next PR

**Pull request merged**
