### PR TITLE
BookKeeperClusterTestCase,UpdateLedgerOpTest: remove call to setAllow…

### PR DESCRIPTION
**Pull request by athanatos**
(@bug W-2962634@)
Signed-off-by: Andrey Yegorov <ayegorovsalesforce.com>
[Ported to master]
Signed-off-by: Samuel Just <sjust@salesforce.com>

### CODE REVIEW

**Comment by eolivelli** [comment]
Can you give a motivation for this change ?

**Comment by athanatos** [comment]
@eolivelli  It seems superfluous and it confused me when I was debugging something else.  I can drop it if you like, but this seems simpler.

**Comment by sijie** [comment]
@athanatos we are trying to use loopback as possible as we can, this would provide a more `stable` environment for running all the tests in CI environment. since all the tests are running in one machine, I am not sure how this would be different when using loopback vs not using loopback.

**Comment by eolivelli** [comment]
I would prefer to keep the ability of using loopback as Sijie described there is more benefit than trouble.
If you do not have strong feeling about this I would like to close this patch as won't fix

**Comment by athanatos** [comment]
@eolivelli @sijie Oh, sorry, I wasn't clear.  It's that TestBKConfiguration already sets it, so these calls  are superfluous.  It confused me briefly, so I figured I'd clean it up.  I can drop it if you think this is better.

**Comment by sijie** [comment]
@athanatos oh, then that makes sense to me. +1

**Pull request closed without merging**
