### PR TITLE
Replication throttle rate supports dynamic value

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation
Inspired by #3151, support set replication throttle rate dynamic

### Changes

support set replication throttle rate dynamic

### CODE REVIEW

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Comment by gaozhangmin** [comment]
@dlg99  PTAL this issue

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]

**Comment by gaozhangmin** [comment]
rerun failure checks

**Pull request merged**
