### PR TITLE
auto metaformat

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

Make it possible to automatically check zookeeper and create bookkeeper metadata when starting bookkeeper.

### Changes

1. automatically check zookeeper,
2. add a distributed lock to avoid consistency problems,
3. automatically  create bookkeeper metadata. 

Master Issue: [#2904](https://github.com/apache/bookkeeper/issues/2904)

### CODE REVIEW

**Comment by StevenLuMT** [comment]
@coolbeevip @hangc0276 
If you have time, please help me review it, thank you

**Review by eolivelli — CHANGES_REQUESTED** [review]
This is pretty dangerous because if you miss configure the bookie you will lose your data.

Can you please start a discussion on dev@bookkeeper.apache.org?

**Review by hangc0276 — CHANGES_REQUESTED** [review]
This operation is too dangerous. I will lose data when miss configured.

**Comment by shoothzj** [comment]
closed by no update.

**Comment by shoothzj** [comment]
feel free to reopen it.

**Pull request closed without merging**
