### PR TITLE
[build] misc bump serveral maven plugin version

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Keep plugin version update. I am trying to make bookkeeper can run on windows(more developers can join this project). I believe update some maven plugin versions can help a little.

### Changes
- bump jacoco maven plugin from 0.8.0 to 0.8.8
- bump maven-clean-plugin from 2.5 to 3.2.0
- bump maven-compiler version to 3.10.1
- bump maven-jar-plugin from 2.4 to 3.2.2
- bump nar-maven-plugin from 3.5.2 to 3.10.1
- delete a unnecessary dependency, it's already defined in parent pom

### ci failure
both `google-http-client-gson` and `maven-settings` are not related to this PR

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@nicoloboschi @dlg99 @eolivelli PTAL

**Review by nicoloboschi — APPROVED** [review]

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
`OWASP Dependency Check` failure: both `google-http-client-gson` and `maven-settings` are not related to this PR

**Pull request merged**
