### PR TITLE
[build] remove Maven POM files

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

The POM are not needed anymore

### Changes

* Removed all POM and maven related config
* Replaced bin/common.sh with bin/common_gradle.sh
* Replaced bin/bookkeeper with bin/bookkeeper_gradle
* Fixed backward compatibility test
* Fixed some "bin" classpath configuration. Now all the scripts under `bin` starts well using the development version 
* Fixed "benchmark/bin/benchmark" script to use correct gradle classpath 

Not yet:
* Removed Maven release scripts

### CODE REVIEW

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
@pkumar-singh @hsaputra PTAL

**Review by dlg99 — APPROVED** [review]

**Comment by pkumar-singh** [comment]
LGTM.

**Comment by pkumar-singh** [comment]
We may also have to update docs on how to build run tests etc. Run just one test. Run all tests in the class. Build only without building tests. Build all but not run tests, etc.

**Pull request merged**
