### PR TITLE
BP-47 (task1): Add native IO library support

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
This is the first task of BP-47

Provide an interface to the POSIX IO API + extensions for O_DIRECT and Linux's fallocate API in order to support direct IO on supported systems.  Direct IO will allow us to bypass cache layers in the underlying operation system, improving memory usage and reducing unnecessary I/O operations to fill caches that won't be used.

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
@eolivelli @dlg99 @zymap @jiazhai Please help take a look.

**Comment by hangc0276** [comment]
rerun failure checks

**Review by zymap — APPROVED** [review]

**Pull request merged**
