### PR TITLE
Change callbacks in CleanupLedgerManager as a Set

### PR DESCRIPTION
**Pull request by AnonHxy**
Descriptions of the changes in this PR:

### Motivation

Currently  the type of `CleanupLedgerManager#callbacks` is map, and the key and value are both the same `callbacks`. We just used it as a set. So this patch will change the `callbacks`  from map to set

### Changes

Change `callbacks` in `CleanupLedgerManager` as a Set

### CODE REVIEW

**Comment by AnonHxy** [comment]
rerun failure checks

**Comment by AnonHxy** [comment]
rerun failure checks

**Comment by AnonHxy** [comment]
@zymap @eolivelli @hangc0276  PTAL

**Review by hangc0276 — APPROVED** [review]
LGTM

**Pull request merged**
