### PR TITLE
Branch 4.0

### PR DESCRIPTION
**Pull request by vik5jagan**

### CODE REVIEW

**Comment by sijie** [comment]
@vik5jagan is this pull request valid?

**Comment by vik5jagan** [comment]
Hi Guo Sijie,

Yes, I want to do code contribution.

Thanks

**Comment by sijie** [comment]
@vik5jagan yup. but this pull request seems to try to merge branch 4.0 to master. is that intended? There is a link describing how to contribute to BookKeeper : https://cwiki.apache.org/confluence/display/BOOKKEEPER/Contributing+to+BookKeeper .

Let me know if you have any questions.

**Comment by vik5jagan** [comment]
Hi,

That is not intended. Sorry I dont want to merge the branch 4.0 to master.

Thanks
Vik

**Comment by sijie** [comment]
Got it. Do you mind closing the pull request?

**Pull request closed without merging**
