### PR TITLE
Upgrade libraries Common Compress and Hadoop (only tests) to fix vulnerabilities

### PR DESCRIPTION
**Pull request by Ghatage**
### Motivation and Changes
Upgraded libraries mentioned in #2509 #2510 #2511 #2512 #2513

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@Ghatage thank you for taking care of this!

**Comment by Ghatage** [comment]
Sure @sijie but I think it may be a little more involved since there are a few api changes with the version upgrades.
So will iterate on this.

**Comment by eolivelli** [comment]
@sijie is the thrift based code still useful? Was it used only at Twitter?
I wonder if we can rid of it at all

**Comment by eolivelli** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
@sijie @eolivelli 
This change at the moment will only resolve  #2513.
Will open up new PRs for the other ones as they need refactoring.

**Pull request merged**
