### PR TITLE
improve the throttle function

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

improve the throttle function : old pr: #2778 
1. duplicate definition for replicationRateByBytes
2.make sure this update safety when different callback run averageEntrySize updating

### Changes

1.clean code for duplicate definition for replicationRateByBytes
2.add a lock to make sure data safety for updateAverageEntrySize

### CODE REVIEW

**Comment by StevenLuMT** [comment]
@eolivelli @pkumar-singh @gaozhangmin @zymap 
If you have time, please help me review it, thank you

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
@eolivelli @pkumar-singh @gaozhangmin @zymap
If you have time, please help me review it, thank you

**Comment by StevenLuMT** [comment]
@eolivelli @pkumar-singh @zymap
If you have time, please help me review it, thank you

**Comment by StevenLuMT** [comment]
@eolivelli @pkumar-singh @zymap
If you have time, please help me review it, thank you

**Review by zymap — APPROVED** [review]

**Review by gaozhangmin — APPROVED** [review]

**Comment by gaozhangmin** [comment]
@StevenLuMT  Please squash your commits into one commit.

**Pull request merged**
