### PR TITLE
Ledger having a Empty segment is causing ReplicasCheck scrutiny to fail

### PR DESCRIPTION
**Pull request by reddycharan**
Descriptions of the changes in this PR:

- in Auditor.ReadLedgerMetadataCallbackForReplicasCheck, fixing logic for empty segments
- added test for validating areEntriesOfLedgerStoredInTheBookie for empty middle segment
- added testcase for ledger with more empty segments.

### CODE REVIEW

**Comment by reddycharan** [comment]
run integration tests

**Comment by reddycharan** [comment]
run bookkeeper-server client tests

**Comment by eolivelli** [comment]
run bookkeeper-server client tests

**Comment by eolivelli** [comment]
@reddycharan can you please rebase to current master ?

**Comment by reddycharan** [comment]
@eolivelli this is also rebased and good to merge.

**Pull request merged**
