### PR TITLE
Bookie Client add quarantine ratio when error count exceed threshold

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
When bookie client read/write data from/to bookie servers, it will check the health of each connected server in sepecific interval. Once the amount of errors reached the threshold, the bookie server will be quarantined for server miniutes (configurated by `bookieQuarantineTimeSeconds`) by the bookie client.

In most circumstance, there are large amount of bookie clients connected to one bookie server, like pulsar broker. Once the bookie server runs in heavy load, most of bookie clients will receive errors and trigger quarantine in the same time, and then quarantine the server for several miniutes. After a few miniutes passed by, the quarantined server will be put back in the same time for most bookie clients, which will lead to periodic oscillation of in/out throughput of the server. It is the obstacle of tunning the throughput of the bookkeeper cluster.

### Changes
I introduce a quarantine probability to determine whether to quarantine the server for the client, avoiding quaraninte the heavy load server in the same time for most of bookie client.

I also expose the quarantine stats to prometheus.

### CODE REVIEW

**Comment by eolivelli** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
Hi @hangc0276 
are you running this patch in production ?

@karanmehta93 @reddycharan @jvrao @merlimat @ravisharda @diegosalvi  @sijie  maybe interested in this patch

**Comment by eolivelli** [comment]
@hangc0276  can please add tests ?

**Comment by hangc0276** [comment]
> Hi @hangc0276
> are you running this patch in production ?
> 
> @karanmehta93 @reddycharan @jvrao @merlimat @ravisharda @diegosalvi @sijie maybe interested in this patch

Yes, I run this patch in my production. With this patch, the standard deviation of the bookies' input throughput decrease from 75MB to 40MB.

**Comment by hangc0276** [comment]
> @hangc0276 can please add tests ?

OK, I will add the test case.

**Comment by hangc0276** [comment]
ping   @sijie   @jiazhai   please take a look.

**Comment by sijie** [comment]
@hangc0276 Nice contribution!

**Pull request merged**
