### PR TITLE
Add 4.15.1 to versions file

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Add 4.15.1 to version file to update the website

### CODE REVIEW

**Comment by zymap** [comment]
@nicoloboschi please take a look when you have time, thank you!

**Review by nicoloboschi — CHANGES_REQUESTED** [review]
Please follow this guide https://github.com/apache/bookkeeper/tree/master/site3#patch-release

**Comment by zymap** [comment]
@nicoloboschi When I execute follow this https://github.com/apache/bookkeeper/tree/master/site3#patch-release, it deleted the 4.15.0 docs, is that expected?

**Comment by nicoloboschi** [comment]
> @nicoloboschi When I execute follow this https://github.com/apache/bookkeeper/tree/master/site3#patch-release, it moves the 4.15.0 document under the 4.15.1, is that expected?
Yes, only the latest patch doc is kept for each release - it makes the website easier to navigate and most of the time the doc is identical between patch releases

**Comment by zymap** [comment]
I think I did wrong at #3440. I remove the old one and regenerate it.

**Comment by zymap** [comment]
@nicoloboschi Could you please take another look?

**Comment by zymap** [comment]
ping @nicoloboschi

**Review by nicoloboschi — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
