### PR TITLE
[Merge Yahoo repo]: Support DbLedgerStorage in LedgerCmd to get list of logger files for a given ledgerId 

### PR DESCRIPTION
**Pull request by jiazhai**
Descriptions of the changes in this PR:
This is cherry-pick from yahoo repo of branch yahoo-4.3.

original change is:
https://github.com/yahoo/bookkeeper/commit/384414b6
Support DbLedgerStorage in LedgerCmd to get list of logger files for a given ledgerId

### CODE REVIEW

**Comment by sijie** [comment]
@jiazhai it seems the new test case is failing (at both java8 and java9 jenkins jobs). can you take a look?

**Comment by jiazhai** [comment]
retest this please

**Comment by jiazhai** [comment]
It is strange. They all passed on my local run

**Comment by sijie** [comment]
retest this please

**Pull request closed without merging**
