### PR TITLE
Create CI jobs for branch-4.7

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

We need to CI jobs running for subsequent minor releases on branch-4.7.

### CODE REVIEW

**Comment by sijie** [comment]
IGNORE CI

**Comment by eolivelli** [comment]
@sijie do we need integration tests job?

**Comment by sijie** [comment]
@eolivelli ideally yes. but I don't think it is a simple change than the normal CI jobs. we need to add instructions regarding updating bc tests, will think through it and do it later.

**Comment by eolivelli** [comment]
Okay. Thanks

**Pull request closed without merging**
