### PR TITLE
Upgrade Guava to 30.0-jre

### PR DESCRIPTION
**Pull request by eolivelli**
- Upgrade Guava to 30.0.jre (see https://github.com/google/guava/releases)
- adapt code, as Futures.addCallback(3-args) has been removed (see https://github.com/google/guava/commit/dfb00017144bf48c408bc4cfcebadc0a0498dc73)

### CODE REVIEW

**Comment by eolivelli** [comment]
rerun failure tests

**Comment by eolivelli** [comment]
@nicoloboschi this change will impact every downstream user of DistributedLog, I saw this problem while writing integration tests of Pulsar + EmailSuccess.com, EmailSuccess uses DLog and it does not support latest version of Guava

**Comment by eolivelli** [comment]
I would like to put this change in 4.12.0, this way users will have a way to upgrade to latest Guava.
The method that I am now using is present in older versions of Guava, so it should be a backward compatible change

**Comment by eolivelli** [comment]
@sijie can we include this fix in 4.12.0 ?

**Review by sijie — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Pull request merged**
