### PR TITLE
Issue-559 Fix findbugs error on SyncCallbackUtils

### PR DESCRIPTION
**Pull request by eolivelli**
Fix FindBugs warning BC_UNCONFIRMED_CAST in  class SyncCallbackUtils

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/109/

**Comment by eolivelli** [comment]
Findbugs is now passing on CI

**Comment by eolivelli** [comment]
Will do. Thanks

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/110/

**Comment by eolivelli** [comment]
@ivankelly done
can you check this again please ? so we can fix the master

**Comment by eolivelli** [comment]
Thank you. @jiazhai can you merge?

**Comment by eolivelli** [comment]
merged, GitHub is not up to date

**Pull request closed without merging**
