### PR TITLE
build: add java21 and windows daily build

### PR DESCRIPTION
**Pull request by shoothzj**
### Motivation

Add `java21` and `windows` daily build to prepare future support. We already do some works in java21 and windows. See alos #4189 

### Changes

Add daily github actions to trigger `mvn clean install` on java21 and windows

### CODE REVIEW

**Comment by shoothzj** [comment]
@nicoloboschi @eolivelli @hangc0276 @merlimat @zhaijack PTAL

**Comment by shoothzj** [comment]
@nicoloboschi @eolivelli @hangc0276 @merlimat @zhaijack PTAL

**Comment by shoothzj** [comment]
@dlg99 @eolivelli @hangc0276 @merlimat @nicoloboschi @zhaijack PTAL

**Review by eolivelli — APPROVED** [review]
+1

**Pull request merged**
