### PR TITLE
Issue-409 BookKeeper Server distribution contains useless jar guava

### PR DESCRIPTION
**Pull request by eolivelli**
Exclude Guava Jar from assembly configuration. Guava is still present by relocated

### CODE REVIEW

**Comment by eolivelli** [comment]
This change affects bookkeeper-server and bookkeeper-dist

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by sijie** [comment]
@eolivelli if you run `mvn dependency:tree`, you will find guava is used at multiple modules (e.g. bookkeeper-benchmark, almost all the stats provider implementations). so your change doesn't work for `bookkeeper-dist` package.

**Comment by eolivelli** [comment]
after all I think that we can close this issue as won't fix.
it is not worth to complicate the build. Guava is still on classpath but shaded on minimal bookie distribution.
ok @sijie  ?

**Comment by sijie** [comment]
sure let me close it. mark it as "won't fix"

**Pull request closed without merging**
