### PR TITLE
Avoid releasing sent buffer to early in BookieClient mock 

### LINKED ISSUE #1643: DeferredSyncTest is failing - Data received is smaller than the minimum for this digest type.  Either the packet it corrupt, or the wrong digest is configured
While preparing 4.8 release I have seen these errors on the logs.
This need investigation before release.

Maybe these are the same errors already seen by @jvrao 

It maybe be caused by a double release.

```
[INFO] -------------------------------------------------------
[INFO] Running org.apache.bookkeeper.client.DeferredSyncTest
[ERROR] Tests run: 13, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 2.476 s <<< FAILURE! - in org.apache.bookkeeper.client.DeferredSyncTest
[ERROR] testAddEntryLastAddConfirmedAdvanceWithForce(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 1.402 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testAddEntryLastAddConfirmedDoesNotAdvance(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.02 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testForceOnWriteAdvHandle(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.05 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKLedgerClosedException: Attempt to write to a closed ledger

[ERROR] testAddEntryLastAddConfirmedAdvanceWithForce(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.022 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testAddEntryLastAddConfirmedDoesNotAdvance(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.017 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testForceOnWriteAdvHandle(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.016 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testAddEntryLastAddConfirmedAdvanceWithForce(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.021 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testAddEntryLastAddConfirmedDoesNotAdvance(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.064 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

[ERROR] testForceOnWriteAdvHandle(org.apache.bookkeeper.client.DeferredSyncTest)  Time elapsed: 0.034 s  <<< ERROR!
org.apache.bookkeeper.client.BKException$BKWriteException: Write failed on bookie

```

Logs:

```
2018-09-04 18:21:12,814 - INFO  - [Builder-OrderedExecutor-1-0:LedgerCreateOp@220] - Ensemble: [localhost:1111, localhost:1112, localhost:1113] for ledger: 1
2018-09-04 18:21:12,857 - ERROR - [Builder-OrderedExecutor-1-0:DigestManager@172] - Data received is smaller than the minimum for this digest type.  Either the packet it corrupt, or the wrong digest is configured.  Digest type: org.apache.bookkeeper.proto.checksum.CRC32DigestManager, Packet Length: 0
2018-09-04 18:21:12,866 - ERROR - [Builder-OrderedExecutor-1-0:LedgerHandle@1763] - Closing ledger 1 due to WriteException: Write failed on bookie
2018-09-04 18:21:12,868 - ERROR - [Builder-OrderedExecutor-1-0:PendingAddOp@383] - Write of ledger entry to quorum failed: L1 E1
2018-09-04 18:21:12,869 - ERROR - [Builder-OrderedExecutor-1-0:DigestManager@172] - Data received is smaller than the minimum for this digest type.  Either the packet it corrupt, or the wrong digest is configured.  Digest type: org.apache.bookkeeper.proto.checksum.CRC32DigestManager, Packet Length: 0
2018-09-04 18:21:12,869 - WARN  - [Builder-OrderedExecutor-1-0:PendingAddOp@356] - Failed to write entry (1, 1): Entry digest does not match
2018-09-04 18:21:12,876 - ERROR - [Builder-OrderedExecutor-1-0:LedgerHandle@1763] - Closing ledger 1 due to WriteException: Write failed on bookie
2018-09-04 18:21:12,876 - ERROR - [Builder-OrderedExecutor-1-0:DigestManager@172] - Data received is smaller than the minimum for this digest type.  Either the packet it corrupt, or the wrong digest is configured.  Digest type: org.apache.bookkeeper.proto.checksum.CRC32DigestManager, Packet Length: 0
2018-09-04 18:21:12,876 - WARN  - [Builder-OrderedExecutor-1-0:PendingAddOp@356] - Failed to write entry (1, 1): Entry digest does not match
2018-09-04 18:21:12,877 - ERROR - [Builder-OrderedExecutor-1-0:LedgerHandle@1763] - Closing ledger 1 due to WriteException: Write failed on bookie
2018-09-04 18:21:12,877 - ERROR - [Builder-OrderedExecutor-1-0:DigestManager@172] - Data received is smaller than the minimum for this digest type.  Either the packet it corrupt, or the wrong digest is configured.  Digest type: org.apache.bookkeeper.proto.checksum.CRC32DigestManager, Packet Length: 0
2018-09-04 18:21:12,878 - WARN  - [Builder-OrderedExecutor-1-0:PendingAddOp@356] - Failed to write entry (1, 1): Entry digest 
```

### PR DESCRIPTION
**Pull request by eolivelli**
Cherry pick tp branch-4.8 commit https://github.com/apache/bookkeeper/commit/6b9cbf2052b27f331553f2738483ae21bf12b49c from Ivan Kelly

If the buffer was sent to more than one bookie with the mock, it would
be released after being sent to the first one. Each write should
retain a refCount themselves, and then release when done.

Author: Ivan Kelly <ivank@apache.org>

Relates to #1598, closes #1643

### CODE REVIEW

**Comment by eolivelli** [comment]
@sijie thank you for taking a look so quickly.

do you know why only Travis-CI started to validate this patch, and not ASF Jenkins ?

**Comment by sijie** [comment]
@eolivelli not sure. jenkins jobs should start as well.

**Comment by eolivelli** [comment]
@sijie  as soon as Travis will turn green I will merge this patch, the fix is trivial, it is already on master.
I think we do not need additional validations

**Comment by sijie** [comment]
@eolivelli sure works for me

**Comment by eolivelli** [comment]
closed with b5065b9479404948b231ab55d5df561211579cb1

**Pull request closed without merging**
