### PR TITLE
Remove old compat stuff

### PR DESCRIPTION
**Pull request by ivankelly**
As compat tests are now docker based, the shading stuff is no longer
needed.

Master Issue: #903

### CODE REVIEW

**Comment by eolivelli** [comment]
I like this very much !

I am +1 but I did not check that all tests have been migrated to the new system

This will also reduce the amount of stuff we are deploying nightly (SNAPSHOTS)

great work @ivankelly

**Comment by sijie** [comment]
@eolivelli 

> This will also reduce the amount of stuff we are deploying nightly (SNAPSHOTS)

just fyi - starting from 4.6.0, we already don't deploy those bc artifacts: https://github.com/apache/bookkeeper/blob/master/tests/pom.xml#L57

**Comment by eolivelli** [comment]
@sijie I forgot about it. Thank you for explanation

**Comment by ivankelly** [comment]
Merging this

**Pull request closed without merging**
