### PR TITLE
BOOKKEEPER-970: Bump the zookeeper version to 3.5

### PR DESCRIPTION
**Pull request by sijie**
in DL, we need to leverage the asynchronous version of 'multi' in zookeeper. so this jira is to bump the zookeeper version to 3.5 to support async multi.

### CODE REVIEW

**Comment by eolivelli** [comment]
Is 3.5 client compatible with 3.4 servers?

**Comment by sijie** [comment]
@eolivelli yes. 3.5 client is compatible with 3.4 servers.

**Comment by sijie** [comment]
@eolivelli yes. we used the new 3.5 API (e.g. asyncMulti and removeWatches) in DL.

**Comment by eolivelli** [comment]
I have double checked and now a new compile-time dependency appeared: net.java.dev.javacc:javacc:jar:5.0:compile

I have already opened a JIRA for that problem https://issues.apache.org/jira/browse/ZOOKEEPER-2460
mean while can we exclude it from BK pom ?

thanks

**Comment by sijie** [comment]
@eolivelli I excluded the javacc dependency

**Comment by eolivelli** [comment]
@sijie now LGTM +1

**Pull request closed without merging**
