### PR TITLE
Add /api/v1/bookie/info REST API

### PR DESCRIPTION
**Pull request by fretiq**
Descriptions of the changes in this PR:

This adds an additional HTTP REST endpoint to expose the bookie's info (only storage numbers for now).

### Motivation

I was looking for an HTTP endpoint that returned the info of only the current bookie, but couldn't find one. The only similar API I've found was `/api/v1/bookie/list_bookie_info`, however it connects to all bookies and may take a long time to respond (plus its response format is difficult to parse).

### Changes

I've added a new API at `/api/v1/bookie/info` that returns a response like:
```json
{
  "freeSpace" : 0,
  "totalSpace" : 0
}
```

### CODE REVIEW

**Comment by eolivelli** [comment]
@mino181295  PTAL this will be very useful for BookKeeper Visual Manager once BP-38 lands to BookKeeper 4.11

**Comment by mino181295** [comment]
Cool, LGTM!

**Comment by fretiq** [comment]
Awesome! Thanks for the quick review!

**Comment by eolivelli** [comment]
@fretiq  can you please resolve the conflicts ?
then we are good to go

**Comment by fretiq** [comment]
Conflicts resolved.

**Comment by eolivelli** [comment]
rerun failure tests

**Pull request merged**
