### PR TITLE
 Provide memory & gc options in bookkeeper script 

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

It is convenient to provide `MEM_OPTS` and `GC_OPTS` in bookkeeper script and bkenv.sh to allow overriding jvm settings through.

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
Looks good.

As you are working on this can you take a look at adding JAVA_JDK_OPT and add jdk internal module 'opens' to netty and orur codebase in order to hide 'illegal reflective access' warnings while running on jdk10?

I can do in a follow up change if you do not have time

**Comment by sijie** [comment]
> dk internal module 'opens' to netty and orur codebase in order to hide 'illegal reflective access' warnings while running on jdk10?

Please do this as a separate issue. I don't use jdk10, which I can't verify any changes.

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Pull request closed without merging**
