### PR TITLE
Remove unused journaltime

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation

journalTime metric is unused anymore  since #3843 

### Changes

Remove journalTime

### CODE REVIEW

**Review by horizonzy — COMMENTED** [review]
Remove it directly is not a good way, we can use `journalTime` again.

**Review by StevenLuMT — DISMISSED** [review]
I think adding `@Deprecated`  is better than cleaning this

**Review by hangc0276 — APPROVED** [review]
IMO, it's safe to remove it in the next major version.

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
> IMO, it's safe to remove it in the next major version.

@horizonzy @StevenLuMT @hangc0276  +1

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Comment by gaozhangmin** [comment]
rerun failure checks

**Review by shoothzj — APPROVED** [review]
unused metrics can be removed in major release

**Pull request merged**
