### PR TITLE
BOOKKEEPER-932: Move to JDK 8

### PR DESCRIPTION
**Pull request by merlimat**

### CODE REVIEW

**Comment by merlimat** [comment]
Build is failing because the container is providing JDK7 for build. @sijie Do you know how to change the configuration for the Jenkins jobs?

**Comment by sijie** [comment]
@merlimat do you have the jenkins account? I can grant the permission to you. 

I am changing it to jdk8 in https://builds.apache.org/job/bookkeeper-master/ job now. After it passed, I would change it to other jobs.

**Comment by merlimat** [comment]
@sijie I think that the PR build is still using JDK-1.7 : https://builds.apache.org/job/bookkeeper-master-git-pullrequest

**Comment by sijie** [comment]
yup. @merlimat I am going to merge this change. since the master ci job is on java8 and change the pr-validation job to java8 too.

**Comment by sijie** [comment]
LGTM +1

**Pull request closed without merging**
