### PR TITLE
ISSUE #2726 Fix JAVA_HOME containing spaces

### PR DESCRIPTION
**Pull request by Sunny-Island**
### Motivation

Fix issue [#3726](https://github.com/apache/bookkeeper/issues/2726)

### Changes

Add double quotation around `${JAVA}`  in `/bin/bookkeeper`.

### CODE REVIEW

**Review by zymap — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]
lgtm

**Review by Ghatage — CHANGES_REQUESTED** [review]
Thank you for your contribution @Sunny-Island!
We would like to run the Github workflows which should test this change.
However, there are multiple places where JAVA_HOME is used that could also use this change, Some such instances are in [bkctl](https://github.com/apache/bookkeeper/blob/f741b484e811925516d24bb541a86a386f112dc2/bin/bkctl#L67), [streamstorage-cli](https://github.com/apache/bookkeeper/blob/3e1507eb862ab5b7d23c15107d36a10ebe14eadd/stream/bin/streamstorage-cli#L111), and [streamstorage](https://github.com/apache/bookkeeper/blob/3e1507eb862ab5b7d23c15107d36a10ebe14eadd/stream/bin/streamstorage#L148) and [dlog](https://github.com/apache/bookkeeper/blob/3e1507eb862ab5b7d23c15107d36a10ebe14eadd/bin/dlog#L116) to name a few. Could you please take a look at all these instances and make the appropriate changes?
Once we have all instances of JAVA_HOME changed here, we can run the github workflows to test the change and get it merged. Thanks!

**Comment by Sunny-Island** [comment]
Thank you for your review @Ghatage. I will make these changes.

**Comment by Sunny-Island** [comment]
@dlg99 @Ghatage  Please review new commit.

**Review by sijie — APPROVED** [review]

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
Thank you for your contribution @Sunny-Island!

**Comment by Sunny-Island** [comment]
Thank you! I'll keep on contributing to community.

**Pull request merged**
