### PR TITLE
Bump netty version to 4.1.75.Final

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation

Changelog: https://netty.io/news/2022/03/10/4-1-75-Final.html

Netty 4.1.75 has https://github.com/netty/netty/issues/12103 feature that https://github.com/apache/bookkeeper/pull/2989 needs

### Modifications

* Upgrade Netty from 4.1.74.Final to 4.1.75.Final
* Netty 4.1.75.Final depends on netty-tc-native 2.0.50, also updates

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]
Great ! especially the Netty patch!

**Review by dlg99 — APPROVED** [review]

**Review by dlg99 — CHANGES_REQUESTED** [review]
@Shoothzj Integration Tests hang/time out consistently, always on the same task `:tests:integration:cluster:test`. This does not happen on other PRs. Can you please take a look?

**Comment by Shoothzj** [comment]
@dlg99 It's caused by https://github.com/grpc/grpc-java/issues/8981. I will follow up on this

**Comment by Shoothzj** [comment]
use #3163 instead

**Pull request closed without merging**
