### PR TITLE
Refactored EntryLogger Buffered channel

### PR DESCRIPTION
**Pull request by merlimat**
Porting https://github.com/yahoo/bookkeeper/commit/ecce14449b07e0b40434835bbc01d75d0a36880b from Yahoo branch.

Refactored entry logger to always use pooled `ByteBuf` when reading entries or scanning the log.

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat I resolved the conflicts after merging #823 . will wait for the CI to complete.

**Comment by merlimat** [comment]
@sijie Updated with required dependent change

**Comment by merlimat** [comment]
Do not merge yet, there still some tests failing. Will check that back later.

**Comment by merlimat** [comment]
Updated with test fixes. I had to include one more commit from Yahoo branch: https://github.com/yahoo/bookkeeper/commit/bdbf36ca6fbccace271f3838a7a7ab0b96798546

All tests should be clear now.

**Comment by jiazhai** [comment]
👍

**Pull request closed without merging**
