### PR TITLE
Issue-1001 merge DoubleByteBuffer from master

### PR DESCRIPTION
**Pull request by eolivelli**
Ports current version of DoubleByteBuffer from master

see #1001 for explanation

### CODE REVIEW

**Comment by eolivelli** [comment]
merged, closing with ac3f1aca808b8c8b9e96401e0190b00fe29b1754

**Comment by sijie** [comment]
I think this ports partial change of #824, we should attribute the changes to the original author, as this should be treated as a `cherry-pick`.

**Comment by sijie** [comment]
oh this change is already merged. anyway, I will update the description to also attribute the credits to the original author.

**Comment by eolivelli** [comment]
I am really sorry @sijie How can I change this ? We cannot force push

**Comment by sijie** [comment]
updated the description with the information. 

@eolivelli it is okay to leave the commit as it is. but in general, if a change was made in master and merged back to branches (either by manually port or cherry-pick), it is good to find the original commit and update description to be "this is a cherry-pick from (githsha) at master, contributed by ...". It is good to make sure credits are attached to original authors as well.

**Comment by eolivelli** [comment]
Totally agree with you @sijie when I merged the change I did not see it as a cherry pick.
Surely in the future I will do as you said.
Again, sorry

**Pull request closed without merging**
