### PR TITLE
[CLEAN] Fix missing Override annotation

### PR DESCRIPTION
**Pull request by lamber-ken**
### Motivation

**Code clean**

- An overridden method should be marked with @Override annotation, once the method signature in the abstract class is changed, the implementation class will report a compile-time error immediately.

- Exception class names must be ended with Exception

- The negation operator is not easy to be quickly understood

### Changes

- Fix missing `@Override` annotation
- `NoIndexForLedger` to `NoIndexForLedgerException` 
- `!(n.doubleValue() > max.doubleValue())` to `(n.doubleValue() <= max.doubleValue())`

### CODE REVIEW

**Comment by lamber-ken** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
CI failed.
Please check

**Comment by lamber-ken** [comment]
Thanks for your review @eolivelli 

> Do you think that we can add a checkstyle rule?

Sure, but from the checkstyle official docs, can not found a useful checkstyle rule.

https://checkstyle.sourceforge.io/checks.html
https://checkstyle.sourceforge.io/config_annotation.html#MissingOverride

> CI failed

I checked the ci error exception stackstrace, it seems doesn't caused by my modification. If you have, help to check it, thanks

**Comment by eolivelli** [comment]
rerun failure tests

**Comment by lamber-ken** [comment]
rerun failure tests

**Comment by lamber-ken** [comment]
rerun failure checks

**Comment by lamber-ken** [comment]
hi @sijie @eolivelli, please take a look, thanks

**Pull request merged**
