### PR TITLE
Fix potential NullPointerException when local book keeper stop on exit

### PR DESCRIPTION
**Pull request by gaoxinge**
Descriptions of the changes in this PR: 

- Fix potential NullPointerException when local book keeper stop on exit.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
@gaoxinge  can you please rebase onto current master ?
we fixed javadoc plugin problems.
I don't know why github actions is not merging your patch with master before validating the patch

**Comment by gaoxinge** [comment]
@eolivelli I merged the master code.

**Comment by eolivelli** [comment]
merged to master branch, thank you @gaoxinge

**Pull request merged**
