### PR TITLE
Fix bookie shell help command exception

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
When run `bin/bookkeeper shell ledgermetadata -h` command, it throw the following exception.
```
23:02:41,236 ERROR Error parsing command line arguments :
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -h
	at org.apache.commons.cli.Parser.processOption(Parser.java:363) ~[commons-cli-commons-cli-1.2.jar:1.2]
	at org.apache.commons.cli.Parser.parse(Parser.java:199) ~[commons-cli-commons-cli-1.2.jar:1.2]
	at org.apache.commons.cli.Parser.parse(Parser.java:85) ~[commons-cli-commons-cli-1.2.jar:1.2]
	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:240) ~[org.apache.bookkeeper-bookkeeper-server-4.16.0-SNAPSHOT.jar:4.16.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2372) ~[org.apache.bookkeeper-bookkeeper-server-4.16.0-SNAPSHOT.jar:4.16.0-SNAPSHOT]
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2463) ~[org.apache.bookkeeper-bookkeeper-server-4.16.0-SNAPSHOT.jar:4.16.0-SNAPSHOT]
ledgermetadata: Print the metadata for a ledger, or optionally dump to a file.
usage: ledgermetadata -ledgerid <ledgerid> [--dump-to-file
                      FILENAME|--restore-from-file FILENAME]
 -dumptofile <arg>        Dump metadata for ledger, to a file
 -l,--ledgerid <arg>      Ledger ID
 -restorefromfile <arg>   Restore metadata for ledger, from a file
```

### Changes
Add `-h` and `--help` support.

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Review by eolivelli — CHANGES_REQUESTED** [review]

**Comment by hangc0276** [comment]
ping @eolivelli @dlg99 @zymap, Please help take a look, thanks.

**Review by zymap — COMMENTED** [review]
How about adding a method `getOptionsWithHelp()` in `MyCommand`, that is 
```
        Options getOptionsWithHelp() {
            Options options = getOptions();
            options.addOption("h", "help", false, "show help");
            return options;
        }
```

Then when running the command in the `MyCommand`, we use `getOptionsWithHelp` to parse the options.

So the change will be only in the MyCommand and we don't need to change other place?

**Comment by hangc0276** [comment]
> How about adding a method `getOptionsWithHelp()` in `MyCommand`, that is
> 
> ```
>         Options getOptionsWithHelp() {
>             Options options = getOptions();
>             options.addOption("h", "help", false, "show help");
>             return options;
>         }
> ```
> 
> Then when running the command in the `MyCommand`, we use `getOptionsWithHelp` to parse the options.
> 
> So the change will be only in the MyCommand and we don't need to change other place?

Good idea, I have updated the code.

**Review by eolivelli — APPROVED** [review]
+1

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Comment by hangc0276** [comment]
rerun failure checks

**Review by dlg99 — APPROVED** [review]
Awesome!

**Pull request merged**
