### PR TITLE
[tests] remove backward compatibility test against yahoo-version (apache Pulsar 1.21)

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

Currently we have an integration test which download a very old version of Apache Pulsar (I suppose with a BK fork but IDK). 

I think it is better to remove this test because:
* we don't have control over yahoo repository (it downloads the client from a yahoo repo in very unstable manner)
* there's not much value upgrading from a unofficial 4.3.x BK fork since we have many other upgrade tests
* it slows down the docker test image creation and I've personally seen this to be flaky on Github CI 

### Changes

* Removed all the reference to the yahoo repository and I removed the test itself
* After some troubles with CI, additionally, I've
    * Upgraded test-logger gradle dep
    * Removed stdout in GH actions since it's not useful and the logs are uploaded after the test suite

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
The CI is failing with this error
```
2022-02-08T07:46:54.2759981Z org.apache.bookkeeper.bookie.CheckpointOnNewLedgersTest
2022-02-08T07:46:54.2760461Z 
2022-02-08T07:46:54.2761541Z   Test testCheckpoint PASSED
2022-02-08T07:46:57.2765613Z #
2022-02-08T07:46:57.2766208Z # A fatal error has been detected by the Java Runtime Environment:
2022-02-08T07:46:57.2766535Z #
2022-02-08T07:46:57.2766856Z #  SIGSEGV (0xb) at pc=0x00007f1d880007f0, pid=8233, tid=0x00007f1d7fd8e700
2022-02-08T07:46:57.2767165Z #
2022-02-08T07:46:57.2767875Z # JRE version: OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-linux64) (8.0_322-b06) (build 1.8.0_322-b06)
2022-02-08T07:46:57.2768474Z # Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
2022-02-08T07:46:57.2768844Z # Problematic frame:
2022-02-08T07:46:57.2769107Z # C  0x00007f1d880007f0
2022-02-08T07:46:57.2769358Z #
2022-02-08T07:46:57.2770201Z # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2022-02-08T07:46:57.2770603Z #
2022-02-08T07:46:57.2770907Z # An error report file with more information is saved as:
2022-02-08T07:46:57.2771410Z # /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/hs_err_pid8233.log
2022-02-08T07:46:57.2771749Z #
2022-02-08T07:46:57.2772055Z # If you would like to submit a bug report, please visit:
2022-02-08T07:46:57.2772401Z #   http://www.azul.com/support/
2022-02-08T07:46:57.2772771Z # The crash happened outside the Java Virtual Machine in native code.
2022-02-08T07:46:57.2773157Z # See problematic frame for where to report the bug.
2022-02-08T07:46:57.2773569Z #
2022-02-08T07:47:08.1818986Z #
2022-02-08T07:47:08.1819723Z # A fatal error has been detected by the Java Runtime Environment:
2022-02-08T07:47:08.1820203Z #
2022-02-08T07:47:08.1901743Z #  SIGSEGV (0xb) at pc=0x00007f92bc4311d0, pid=8348, tid=0x00007f92b9a98700
2022-02-08T07:47:08.1902026Z #
2022-02-08T07:47:08.1902666Z # JRE version: OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-linux64) (8.0_322-b06) (build 1.8.0_322-b06)
2022-02-08T07:47:08.1903153Z # Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
2022-02-08T07:47:08.1903448Z # Problematic frame:
2022-02-08T07:47:08.1903645Z # C  0x00007f92bc4311d0
2022-02-08T07:47:08.1903833Z #
2022-02-08T07:47:08.1904296Z # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2022-02-08T07:47:08.1904621Z #
2022-02-08T07:47:08.1904854Z # An error report file with more information is saved as:
2022-02-08T07:47:08.1905283Z # /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/hs_err_pid8348.log
2022-02-08T07:47:08.2760676Z #
2022-02-08T07:47:08.2761421Z # If you would like to submit a bug report, please visit:
2022-02-08T07:47:08.2761990Z #   http://www.azul.com/support/
2022-02-08T07:47:08.2762921Z # The crash happened outside the Java Virtual Machine in native code.
2022-02-08T07:47:08.2763459Z # See problematic frame for where to report the bug.
2022-02-08T07:47:08.2763875Z #
2022-02-08T07:47:08.4766360Z Process 'Gradle Test Executor 20' finished with non-zero exit value 134
2022-02-08T07:47:08.4766783Z This problem might be caused by incorrect test process configuration.
2022-02-08T07:47:08.4767850Z Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.3.3/userguide/java_testing.html#sec:test_execution
2022-02-08T07:47:08.4768520Z org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 20' finished with non-zero exit value 134
2022-02-08T07:47:08.4768985Z This problem might be caused by incorrect test process configuration.
2022-02-08T07:47:08.4769436Z Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.3.3/userguide/java_testing.html#sec:test_execution
2022-02-08T07:47:08.4770067Z 	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:183)
2022-02-08T07:47:08.4770885Z 	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
2022-02-08T07:47:08.4771798Z 	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:55)
2022-02-08T07:47:08.4772485Z 	at sun.reflect.GeneratedMethodAccessor427.invoke(Unknown Source)
2022-02-08T07:47:08.4772959Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-08T07:47:08.4773379Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2022-02-08T07:47:08.4773826Z 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-02-08T07:47:08.4774351Z 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-02-08T07:47:08.4774926Z 	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
2022-02-08T07:47:08.4775805Z 	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
2022-02-08T07:47:08.4776307Z 	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
2022-02-08T07:47:08.4776757Z 	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
2022-02-08T07:47:08.4777242Z 	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
2022-02-08T07:47:08.4778123Z 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
2022-02-08T07:47:08.4778935Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2022-02-08T07:47:08.4779461Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2022-02-08T07:47:08.4779965Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-02-08T07:47:08.4780446Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-02-08T07:47:08.4780956Z 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
2022-02-08T07:47:08.4781368Z 	at java.lang.Thread.run(Thread.java:750)
```
I'm sure is not related to my PR. Probably the cause is the switch to Gradle 7

**Comment by nicoloboschi** [comment]
rerun failure checks

**Pull request merged**
