### PR TITLE
[fix] Fix ConcurrentLongHashMap concurrency issue

### PR DESCRIPTION
**Pull request by dao-jun**
Descriptions of the changes in this PR:

### Motivation

Fix ConcurrentLongHashMap can be ArrayIndexOutBound when call `get`

### Changes

(Describe: what changes you have made)

Master Issue: https://github.com/apache/bookkeeper/issues/4316

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by dao-jun** [comment]
@merlimat @dlg99 @lhotari PTAL

**Comment by dao-jun** [comment]
It looks other Concurrent containers has the same issue, I'll create PRs to fix them one by one.

**Comment by dao-jun** [comment]
I created an issue for tracking it https://github.com/apache/bookkeeper/issues/4318

**Comment by dao-jun** [comment]
BTW, the key point is 
```java
                    int capacity = this.capacity;
                    bucket = signSafeMod(bucket, capacity);
```
and 
```java
                    // First try optimistic locking
                    long storedKey = keys[bucket];
                    V storedValue = values[bucket];
```

not an atomic operation.

If `rehash` triggered in an async thread *after* calculating `bucket` and finished *before* read entry from the array, we will read incorrect value.

**Review by lhotari — CHANGES_REQUESTED** [review]
Thanks for reporting the issue and starting the work to fix this issue.

Catching the exception would be the preferred solution since there's no point of using a StampedLock unless optimistic locking is used.

I think that we had this same bug discussed years ago, but for some reason we didn't fix this.

**Comment by lhotari** [comment]
Found the discussion from the past: https://github.com/apache/pulsar/pull/18390#discussion_r1016594541 . @thetumbled had originally made a PR to catch IndexOutOfBoundsException, which I think is the correct solution.

**Comment by thetumbled** [comment]
I have created this pr to fix the issue in bookkeeper: https://github.com/apache/bookkeeper/pull/4066, can we move forward with it? @lhotari @hangc0276 @eolivelli @wenbingshen @zymap @shoothzj @horizonzy

**Comment by lhotari** [comment]
Let's close this PR and continue with #4066

**Comment by dao-jun** [comment]
Good! Let's continue with #4066

**Pull request closed without merging**
