### PR TITLE
Pre break loop when self create layoutZNode succeed.

### PR DESCRIPTION
**Pull request by horizonzy**
Pre break loop when self create layoutZNode succeed.

### CODE REVIEW

**Review by nicoloboschi — COMMENTED** [review]
It would be clearer to add the break just after the node creation, line 190

**Comment by hangc0276** [comment]
@horizonzy  Would you please rebase the master?

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
I think this change is not necessary

**Comment by horizonzy** [comment]
> I think this change is not necessary

It can reduce once to invoke `zkc.exists(layoutZNode, false)`

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
