### PR TITLE
Add bookkeeper protocol file for repo

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolongran <xiaolongran@tencent.com>

This is the first commit for bk-client-go, we generate the proto file first.

### Motivation

Add protocol files for repo

### CODE REVIEW

**Review by liangyuanpeng — CHANGES_REQUESTED** [review]
It's greate if you can add README for generate proto file. like https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/pulsar_proto/README.md

**Comment by genert** [comment]
@wolfstudy Any update on this?

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Comment by shoothzj** [comment]
closed for no updates.

**Pull request closed without merging**
