### PR TITLE
[backward tests] add BookKeeper 4.14.4

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation
BK 4.14.4 has been released and we should test it in the upgrade tests

Note: for the sake of test performance, we test the upgrades only for the latest releases of each minor release 

### Changes

* Replaced BK 4.14.3 with 4.14.4

### CODE REVIEW

**Comment by nicoloboschi** [comment]
@eolivelli @dlg99 @pkumar-singh it would make sense to add this task to the release process

**Comment by nicoloboschi** [comment]
run failure checks

**Comment by nicoloboschi** [comment]
run failure checks

**Review by eolivelli — APPROVED** [review]
We didn't change the wire protocol in 4.14.4  so there is no hurry to update these values.

BTW the patch LGTM

**Comment by nicoloboschi** [comment]
run failure checks

**Review by dlg99 — APPROVED** [review]

**Comment by nicoloboschi** [comment]
run failure checks

**Comment by eolivelli** [comment]
@nicoloboschi sorry for late reply, 
can you please resolve the conflicts ?

**Pull request merged**
