### PR TITLE
Fix wrong module artifactId

### PR DESCRIPTION
**Pull request by lamber-ken**
### Motivation

Fix wrong maven artifactId, there are three module use the same artifactId.

### Changes

image

### CODE REVIEW

**Comment by eolivelli** [comment]
All tests facile on CI please check

**Comment by lamber-ken** [comment]
> All tests failed on CI please check

Welcome, not familiar with bookkeeper, I am checking the ci. : )

**Comment by lamber-ken** [comment]
@sijie @eolivelli please review again, thanks : )

**Comment by eolivelli** [comment]
@rdhabalia @sijie @jiazhai  PTAL and merge
IMO It is worth to backport to 4.10 branch

**Comment by eolivelli** [comment]
@rdhabalia @jiazhai can you please help merging this patch ?

**Pull request merged**
