### PR TITLE
ISSUE #2640: BP-43 Migrate bookkeepr-server org.apache.bookkeeper.bookie.* tests to gradle

### PR DESCRIPTION
**Pull request by pkumar-singh**
### Motivation
 Migrating bookkeeper-server bookie tests to gradle.

### Changes

1. As per the naming convention name of test class/file Should be {FooFeature}Test as opposed to Test{FooFeature}
2. Migrating tests to gradle

Master Issue: #2640

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
+1

**Review by eolivelli — CHANGES_REQUESTED** [review]
I am fine with this patch as far as we are sure that we are going to finish the gradle migration before the next major release.

We do not have a timeframe yet for a release but we should start a discussion as soon as possible on dev@bookkeeper.

My concern is that when we cut a release we MUST say to the users how to build BookKeeper and to run the tests.

So we must update the release procedure and the build instructions.

if we run the tests on CI with Gradle but still Maven is the build system for the release then we have a problem

**Comment by nicoloboschi** [comment]
@pkumar-singh other than github actions, are there any point (other than release procedure) to migrate?
If no, IMHO we can create a single PR migrating all GH tests and updating release guide, what do you think @eolivelli ?

**Comment by hsaputra** [comment]
@eolivelli - +1 to that. We should be able to complete the Gradle migration before next major release.
Will work with @pkumar-singh to make sure we complete the tasks for it.

**Review by hsaputra — APPROVED** [review]
LGTM +1

**Comment by pkumar-singh** [comment]
@eolivelli Absolutely. We are committed to moving everything to gradle before the next release. 
I think I have already sent an email to dev@bookkeepr some time last week.
This week I am going migrate the build to gradle. Next week I will focus on release and documentation updates.

**Comment by nicoloboschi** [comment]
The plan looks good to me, I think we can go ahead, thank you

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
merging

**Pull request merged**
