### PR TITLE
[ci] Move CI to JDK11

### PR DESCRIPTION
**Pull request by nicoloboschi**
Master issue: #3025
### Motivation

BookKeeper has been running with JDK11 for a long time. The official docker image is using JDK11 so it's much better to verify the codebase using JDK11 

### Changes

* Update all the checks to using jdk11 temurin distro, except for backward compatibility tests which uses old clients that do no support jdk11

### CODE REVIEW

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by nicoloboschi** [comment]
@eolivelli @dlg99 @merlimat PTAL

**Comment by zymap** [comment]
Can we use a matrix to run both the jdk1.8 and jdk11?

**Comment by nicoloboschi** [comment]
The matrix add a significant overhead for every pull request since the tests execution is doubled. 
I don't see any relevant motivation to keep the entire CI with both the jdk's.
I left a couple of jobs using JDK8, they ensure JDK8 compile compatibility.

Also, from a mid-term perspective, when we will upgrade to JDK 17 (or next TLS) it's not a good idea to duplicate the CI jobs another time.

**Review by dlg99 — APPROVED** [review]
Awesome!

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
