### PR TITLE
Fixed typos in README.md

### PR DESCRIPTION
**Pull request by dmsergeevp44**

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by dmsergeevp44** [comment]
@sijie how would I go about retesting this?

**Comment by merlimat** [comment]
> @sijie how would I go about retesting this?

No worries, that's a command for Jenkins CI to get retriggered :)

**Comment by sijie** [comment]
@dmsergeevp44 

haha, it is a command for Jenkins CI, not for you. sorry for confusion.

**Comment by sijie** [comment]
IGNORE CI

**Comment by sijie** [comment]
merged. 

@dmsergeevp44 thank you for your contribution!

**Pull request closed without merging**
