### PR TITLE
Use conf value in RackawareEnsemblePlacementPolicyImpl.initialize method

### PR DESCRIPTION
**Pull request by reddycharan**
Descriptions of the changes in this PR:

- Use conf value in RackawareEnsemblePlacementPolicyImpl.initialize method,
instead of uninitialized enforceMinNumRacksPerWriteQuorum variable

### CODE REVIEW

**Comment by reddycharan** [comment]
run integration tests

**Comment by reddycharan** [comment]
run integration tests

**Comment by reddycharan** [comment]
@sijie not sure what is the issue with integration tests here. shall i merge this PR?

**Comment by reddycharan** [comment]
run integration tests

**Comment by sijie** [comment]
IGNORE IT CI

**Comment by sijie** [comment]
IGNORE CI

**Pull request merged**
