### PR TITLE
BP61: revert BP-59 to release ByteBuf using ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()

### LINKED ISSUE #3792: BP-61: Revert BP-59 to release ByteBuf using ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()
**BP**

> Follow the instructions at https://bookkeeper.apache.org/community/bookkeeper-proposals/ to create a proposal.

This is the master ticket for tracking BP-61 :

### Motivation

In BP-59, which was not discussed in the dev mail list and without a vote refactored the ByteBuf release method by ReferenceCountUtil.safeRelease() instead of ByteBuf.release().

In the `ReferenceCountUtil.safeRelease()`, it catches the release exception. This change can make the ByteBuf release without any exceptions and makes the code run well, but it will make bugs hide deeper and more challenging to find out.
   ```java
   public static void safeRelease(Object msg) {
        try {
            release(msg);
        } catch (Throwable t) {
            logger.warn("Failed to release a message: {}", msg, t);
        }
    }
   ```
For example, if there is a bug to release the ByteBuf twice, whose refcnt is 1, we can find out the bug quickly if we use ByteBuf.release(), but the bug will be hard to find out if we use `ReferenceCountUtil.safeRelease()`

There are 12 PRs to refactor the ByteBuf release method, and I suggest reverting those PRs. 

- https://github.com/apache/bookkeeper/pull/3673
- https://github.com/apache/bookkeeper/pull/3674
- https://github.com/apache/bookkeeper/pull/3687
- https://github.com/apache/bookkeeper/pull/3688
- https://github.com/apache/bookkeeper/pull/3689
- https://github.com/apache/bookkeeper/pull/3691
- https://github.com/apache/bookkeeper/pull/3693
- https://github.com/apache/bookkeeper/pull/3694
- https://github.com/apache/bookkeeper/pull/3695
- https://github.com/apache/bookkeeper/pull/3698
- https://github.com/apache/bookkeeper/pull/3700
- https://github.com/apache/bookkeeper/pull/3703

Considering some PRs have been cherry-picked into the release branch but others not, it will be hard to cherry-pick if we just push one PR to revert all the above PRs. I will push three Prs for master, branch-4.15, and branch-4.14 to apply this change.

### Proposal PR
- #3796 
- #3797 
- #3798

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #3792

### CODE REVIEW

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcjQBvslxtJLpRNJfqCwknmpg
-1 (non-binding)
for new BP-61 :
1) I think no need to revert 12 PRs to refactor the ByteBuf release method
2) Directly replace ReferenceCountUtil.safeRelease() with ReferenceCountUtil.release()

**Comment by hangc0276** [comment]
> https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcjQBvslxtJLpRNJfqCwknmpg -1 (non-binding) for new BP-61 :
> 
> 1. I think no need to revert 12 PRs to refactor the ByteBuf release method
> 2. Directly replace ReferenceCountUtil.safeRelease() with ReferenceCountUtil.release()

@StevenLuMT I just replace `ReferenceCountUtil.safeRelease()` with `ReferenceCountUtil.release()` to revert those changes, would you please point out your ideas in detail?

**Comment by StevenLuMT** [comment]
> Fix #3792

why not directly replace ReferenceCountUtil.safeRelease() with ReferenceCountUtil.release?
#3840

> > https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcjQBvslxtJLpRNJfqCwknmpg -1 (non-binding) for new BP-61 :
> > 
> > 1. I think no need to revert 12 PRs to refactor the ByteBuf release method
> > 2. Directly replace ReferenceCountUtil.safeRelease() with ReferenceCountUtil.release()
> 
> @StevenLuMT I just replace `ReferenceCountUtil.safeRelease()` with `ReferenceCountUtil.release()` to revert those changes, would you please point out your ideas in detail?

sorry, I seem to have misunderstood, I thought you reverted first, and then proposed a replacement,
are your two replacements made for different branches? #3796 #3398

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
