### PR TITLE
Apache BookKeeper 4.11.1 release notes

### PR DESCRIPTION
**Pull request by eolivelli**
This PR contains the release notes for 4.11.1 release.

Do not merge please, I will merge this patch as part of the 4.11.1 release procedure

### CODE REVIEW

**Comment by eolivelli** [comment]
The skeleton of the 4.11.1 docs was already ready, created by @rdhabalia during 4.11.0 release process

**Review by rdhabalia — APPROVED** [review]

**Comment by rdhabalia** [comment]
do we want to merge this PR?

**Comment by eolivelli** [comment]
Only when 4.11.1 is released

**Comment by nicoloboschi** [comment]
@eolivelli I think we should also include https://github.com/apache/bookkeeper/commit/0979b41fbba0e50ea27c008f1f9f9a81e3fadd28

**Comment by eolivelli** [comment]
@nicoloboschi good catch, thank you

**Review by sijie — APPROVED** [review]

**Comment by eolivelli** [comment]
closing in favour of #2448

**Pull request closed without merging**
