### PR TITLE
Cleanup code in RackawareEnsemblePlacementPolicyImpl

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

Simple code cleanup

### Changes

1.RackawareEnsemblePlacementPolicyImpl.REPP_DNS_RESOLVER_CLASS has be existed in his parent class,so clean in the child class

2.NetUtils.logger is no use

### CODE REVIEW

**Comment by StevenLuMT** [comment]
@Vanlightly  @coolbeevip 
If you have time, please help me review it, thank you

**Comment by StevenLuMT** [comment]
@Vanlightly  @coolbeevip 
If you have time, please help me review it, thank you

**Review by eolivelli — APPROVED** [review]
LGTM

thank you

**Review by nicoloboschi — APPROVED** [review]

**Comment by StevenLuMT** [comment]
@eolivelli  
maybe need a maintainer to approve running workflows,thanks

**Review by dlg99 — APPROVED** [review]

**Comment by StevenLuMT** [comment]
@dlg99 @nicoloboschi 
hello,the workflows not finished? Some checks were not successful: 2 cancelled and 8 successful checks, 
 this pr can be merged ?  thanks

**Comment by nicoloboschi** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
> rerun failure checks
 Hi,I have cheecked,last workflow run 6 hours timeout，now all checks have passed, thanks
this pr can be **merged**? 
@nicoloboschi

**Comment by StevenLuMT** [comment]
> rerun failure checks
 Hi,I have cheecked,last workflow run 6 hours timeout，now all checks have passed, thanks
this pr can be **merged**? 
@nicoloboschi

**Review by Shoothzj — APPROVED** [review]

**Comment by StevenLuMT** [comment]
now all checks have passed, this pr can be merged?
thank you

@nicoloboschi @dlg99 @eolivelli @Shoothzj

**Comment by StevenLuMT** [comment]
now all checks have passed, this pr can be merged?
thank you,brothers

@nicoloboschi @dlg99 @eolivelli @Shoothzj

**Comment by StevenLuMT** [comment]
now all checks have passed, this pr can be merged?
thank you,my brothers

@nicoloboschi @dlg99 @eolivelli @Shoothzj

**Comment by StevenLuMT** [comment]
@nicoloboschi @dlg99 @eolivelli @Shoothzj
now all checks have passed, this pr can be merged?
thank you,my brothers

**Comment by StevenLuMT** [comment]
@nicoloboschi @dlg99 @eolivelli @Shoothzj
now all checks have passed, this pr can be merged?
thank you

**Comment by StevenLuMT** [comment]
@nicoloboschi @dlg99 @eolivelli
now all checks have passed, this pr can be merged?
thank you

**Review by eolivelli — APPROVED** [review]
+1

**Pull request merged**
