### PR TITLE
Issue 739: Move the implementation of http services to be under server package

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

bookkeeper-http module provides the framework for http admin rest api. it is using 'org.apache.bookkeeper.http' and 'org.apache.bookkeeper.http.service. the http package inbookkeeper-server` is reusing these two packages. it is not good for two modules sharing same package name, it is going to be confusing javadoc.

### CODE REVIEW

**Comment by eolivelli** [comment]
And it won't work on java9 after modularization: a package can live only inside one jar

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by sijie** [comment]
@eolivelli I made this for 4.6. because http server is the new feature, I would like it get fixed before release, rather than letting this structure layout get out in 4.6.

**Comment by sijie** [comment]
please retest this

**Comment by sijie** [comment]
retest this please

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Pull request closed without merging**
