### PR TITLE
BOOKKEEPER-1071: Use per connection instances of request encoder/decoder

### PR DESCRIPTION
**Pull request by merlimat**

### CODE REVIEW

**Comment by merlimat** [comment]
There seems to be some problem in Jenkins since the build is immediately failing:

```
...
Setting MAVEN_3_3_3_HOME=/home/jenkins/tools/maven/apache-maven-3.3.3
[bookkeeper-master-git-pullrequest] $ /bin/bash /tmp/hudson6425132611346733334.sh
/tmp/hudson6425132611346733334.sh: line 8: mvn: command not found
Build step 'Execute shell' marked build as failure
[FINDBUGS] Skipping publisher since build result is FAILURE

```

**Comment by sijie** [comment]
checking the jenkins build now

**Comment by sijie** [comment]
Hmm. I am not really sure about the error here.

@eolivelli - did you change any settings on hudson? The error message seems to be related to hudson.

**Comment by eolivelli** [comment]
No I only changed master job not the one for prs.
I will check too asap

**Comment by sijie** [comment]
I created a new maven-based job (the old one is using customized shell script). It seems to be working, need to adjust some build commands. https://builds.apache.org/job/bookkeeper-precommit-pullrequest/1/console

**Comment by sijie** [comment]
https://builds.apache.org/job/bookkeeper-precommit-pullrequest/4/console seems to be working now.

**Comment by sijie** [comment]
https://builds.apache.org/job/bookkeeper-precommit-pullrequest/4/console it passed. merging this change now.

**Pull request closed without merging**
