### PR TITLE
revert DoubleByteBuf niobuffers() changes

### PR DESCRIPTION
**Pull request by sschepens**
Revert some of the changes in https://github.com/apache/bookkeeper/pull/996 since they cause issues

### CODE REVIEW

**Comment by sijie** [comment]
committers, please make sure this one is cherry-picked to 4.6.

**Comment by eolivelli** [comment]
I will do, sure

**Comment by ivankelly** [comment]
What issues?

**Comment by jvrao** [comment]
Please be more descriptive in the commit message on what is the issue.

**Pull request closed without merging**
