### PR TITLE
ISSUE #1495: Option to enforce minNumRacksPerWriteQuorum

### PR DESCRIPTION
**Pull request by reddycharan**
Descriptions of the changes in this PR:

Provide an option to enforce the guarantee of minNumRacksPerWriteQuorum
if it is enabled. If it cann't find a bookie to enforce the guarantee
then the API in RackawareEnsemblePlacementPolicy should throw
BKNotEnoughBookiesException.

Master Issue: #1495

### CODE REVIEW

**Comment by reddycharan** [comment]
@sijie & @jvrao I would like to get it reviewed, before I proceed with adding testcases and cleaning the code (if it is required.)

**Comment by jvrao** [comment]
Looks good to me. Is there any part that you are concerned with Charan?

**Comment by reddycharan** [comment]
@sijie this must be good to go.

**Comment by sijie** [comment]
@reddycharan can you rebase the PR? there are file conflicts.

**Comment by reddycharan** [comment]
@sijie rebased the code to current master. I think the tests went fine, except the unrelated test failure.

**Comment by sijie** [comment]
run bookkeeper-server tests
run pr validation

**Comment by sijie** [comment]
rerun pr validation
run bookkeeper-server bookie tests

**Comment by sijie** [comment]
bookie tests have successfully passed before. https://builds.apache.org/job/bookkeeper_precommit_bookie_tests/76/ 

the failures due to timeout on EntryLogTest #1516

**Comment by sijie** [comment]
IGNORE CI

**Pull request closed without merging**
