### PR TITLE
Update distributedlog library to use NoSuchLedgerExistsOnMetadataServer

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Issue #2066 introduced `NoSuchLedgerExistsOnMetadataServer`. But the distributedlog
library is not updated to reflect to this change.

*Modifications*

Change to use `NoSuchLedgerExistsOnMetadataServer` in the right place.

### CODE REVIEW

**Comment by ivankelly** [comment]
This won't pass integration tests until the break introduced by #2090 is fixed.

**Comment by ivankelly** [comment]
@sijie Can you merge master into this? The integration tests should be fixed.

**Comment by eolivelli** [comment]
@ivankelly we can merge as there are enough approvals from committers.
please merge

**Comment by eolivelli** [comment]
@ivankelly I see (I saw your comment on the ML).
Usually committers can push changes to contributors branches in GitHub.
So you can push a change to @sijie's one.
There is not so much hurry, we can wait for @sijie

**Comment by eolivelli** [comment]
@ivankelly on our CI jobs every run of the job is done after merging with master (target) branch.

**Comment by eolivelli** [comment]
run integration tests

**Comment by ivankelly** [comment]
@eolivelli I don't merge things that aren't 100% green. That's what caused this issue in the first place. 
Sometimes GH gives you a button to do the master merge, but I guess that's when source and dest are same repo. I'll do it manually.

**Comment by eolivelli** [comment]
@ivankelly so you succeeded to push a change to Sijie's branch

**Comment by eolivelli** [comment]
> I don't merge things that aren't 100% green

Totally agree ! @ivankelly

**Comment by ivankelly** [comment]
rerun integration tests

**Comment by ivankelly** [comment]
rerun bookkeeper-server bookie tests

**Comment by ivankelly** [comment]
run integration tests

**Comment by ivankelly** [comment]
rerun integration tests

**Pull request merged**
