### PR TITLE
Site updates and release note for 4.14.2

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Site updates and release note for 4.14.2

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
the release notes are at
https://github.com/apache/bookkeeper/pull/2763/files#diff-e0a1e7642b2b55b58ef495600503f7c31d4d4e4c4c48d4c176110edb0ead0274R1

**Comment by eolivelli** [comment]
@zymap one note for the next time:
please separate in two commits the preparation of the website structure and the release notes page,
this way it is easier to review the release notes, otherwise they are buried into many files that are simply copied from the previous version

**Comment by zymap** [comment]
Got it. Thanks

**Comment by zymap** [comment]
I will merge this PR. The new release note will open in another PR

**Pull request merged**
