### PR TITLE
Migrate Dockerfile from centos to ubuntu

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
centos is not maintained anymore, switch to ubuntu

### Changes
- migrate from centos to ubuntu
- use python3 instead of python2
- Bump bookkeeper version from 4.12.1 to latest 4.15.1

### CODE REVIEW

**Comment by Shoothzj** [comment]
@merlimat @nicoloboschi @eolivelli @hangc0276 PTAL

**Review by merlimat — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
really good !

+1

**Comment by zymap** [comment]
I think we need to make the docker file changes apply to other branches.

**Comment by lhotari** [comment]
Putting compilers in a production docker image isn't usually recommended. There shouldn't be any need to add gcc and g++.

See https://github.com/apache/pulsar/pull/14093 . When installing python3 and pip3, the way to prevent installing compilers is to use `apt-get -y install --no-install-recommends python3 python3-pip` for the installation. 

Blog post which explains the need to use `--no-install-recommends` when creating docker images: https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends

**Pull request merged**
