### PR TITLE
BOOKKEEPER-852: Release LedgerDescriptor and master-key objects when not used anymore

### PR DESCRIPTION
**Pull request by merlimat**
Maps with ledger descriptors and master-keys are not cleaned after a ledger gets deleted.

For this PR, please only take a look at the last commit 18e3455. The other 2 commits are already in separate PRs. I'll rebase this PR once they'll get merged.

### CODE REVIEW

**Comment by sijie** [comment]
I guess this change depends on the other changes. I will try to get the other changes in today.

**Comment by eolivelli** [comment]
@revans2 @sijie  this PR is to be rebased

**Comment by merlimat** [comment]
Great, I'll rebase this

**Comment by merlimat** [comment]
Rebased and added basic unit test

**Comment by jvrao** [comment]
+1

**Pull request closed without merging**
