### PR TITLE
Issue #1169 Upgrade Surefire plugin to 2.20.1

### PR DESCRIPTION
**Pull request by pasha-kuznetsov**
**Context**

We at Salesforce have been experiencing a series of hard to nail down test failures related to some of our changes causing Bookkeeper tests occasionally hanging up until they were terminated by Maven / Surefire. What's been making it harder to figure out was that the issue was only reproducing on Jenkins, not locally, and the lack of thread dumps along with Surefire failing to produce reports for these tests, making them next to invisible in Jenkins output.

**Related**

Issue #463 / PR #481 changes help terminate tests hanging in `@Before` or `@After` by changing `@Test` based "local" timeouts to `@Rule` based "global" ones.

**Proposed changes**

Upgrade Surefire plugin to 2.20.1 which has a few related [fixes and improvements since 2.19.1](https://issues.apache.org/jira/browse/SUREFIRE-1413?jql=project%20%3D%20SUREFIRE%20AND%20fixVersion%20in%20(2.20%2C%202.20.1)): 
* [SUREFIRE-1322](https://issues.apache.org/jira/browse/SUREFIRE-1322) Surefire and Failsafe should dump critical errors in dump file and console
* [SUREFIRE-1435](https://issues.apache.org/jira/browse/SUREFIRE-1435) Improve Thread Dump
etc

(@bug W-4700391@)

### CODE REVIEW

**Comment by eolivelli** [comment]
retest this please

**Comment by sijie** [comment]
rekick travis ci

**Comment by sijie** [comment]
all CI job passed except integration tests. since this change only upgrade surefire plugin, it won't affect integration tests. so ignore integration test to merge it.

**Comment by sijie** [comment]
IGNORE CI

**Pull request closed without merging**
