### PR TITLE
Upgrade ZooKeeper to 3.6.2

### PR DESCRIPTION
**Pull request by eolivelli**
- upgrade ZooKeeper dependency
- add explicit dependency on Snappy Java, needed by ZooKeeper Server

Please note that ZooKeeper server also needs Drop Wizard Metrics Core, but we are already bundling it

### CODE REVIEW

**Comment by eolivelli** [comment]
Related to Pulsar issue
https://github.com/apache/pulsar/pull/8590

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Ghatage** [comment]
@eolivelli Looks like some tests will need refactoring.

```
Error:  org.apache.bookkeeper.benchmark.TestBenchmark.testReadThroughputLatency  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.zookeeper.server.ServerMetrics
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:246)
	at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:285)
	at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:494)
	at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:665)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:758)
	at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:130)
	at org.apache.bookkeeper.test.ZooKeeperUtil.restartCluster(ZooKeeperUtil.java:116)
```

**Comment by eolivelli** [comment]
Simply I need to add metrics core dep in more places:)

**Review by merlimat — APPROVED** [review]

**Comment by eolivelli** [comment]
@merlimat all test passed, can you please help me merging this patch ?

**Pull request merged**
