### PR TITLE
BP-27: New BookKeeper CLI

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

`BookieShell` is the current bookkeeper cli for interacting and operating a bookkeeper cluster. However, this class is getting bigger with more commands added to it. It is facing a few problems for maintenance and extensibility.

- All commands sit in one gaint shell class. It is hard to tell if a command is used for managing a bookie only or if a command is used for managing a cluster.
- Lack of unit tests. This class has very few test coverage. Most of the commands (introduced in early days) don't have a unit test.
- Lack of extensibility. If a new function component (for example, dlog) is introduced, it is a bit hard to extend this CLI to have commands for new function component.

All these problems lead to the proposal here. This proposal is to propose refactoring/redesigning the bookkeeper CLI to allow better managebility for maintenance, better test coverage and better extensibility for new function components.

Master Issue: #1000

### CODE REVIEW

**Comment by sijie** [comment]
Put up a PR #1094 for demonstrating the idea.

**Comment by sijie** [comment]
> Can I suggest that as you submit the changes, you submit each command individually, so that it's easier to review?

you mean this PR in #1094 or you mean the changes in future?

If you mean #1094 , the change there is mainly for setting up the framework and only 3 commands on each category is moved. so I think it is already a minimal change that I can get to for this review - you can get an overview on how the new CLI looks like.

If you mean the changes in futures, yes, there will be and should be one command per PR.

> Integration tests for these would also be good, since unit testing can't test the bash script part.

You don't need to test bash script every command. The testing of bash script should mainly just focus on if it is taking the environment settings correctly, invoking the CLI program correctly. That means the tests should be:

1) bash script testing: focus on testing the script itself, if it is taking the environment settings correctly, invoking the CLI program correctly. And it should stop after testing it can invoke the program. 

2) CLI program testing: focus on testing parsing and ensure the correct command is invoking and right parameters are passing into command.

3) Command logic testing: focus on testing the logic for individual commands.

This BP covers both 2) and 3). while 1) is related but it is a different topic in general, we need to test all the scripts we shipped along with the release. so it will have to be a different task than the one here.

Hope this make the clarification.

**Comment by ivankelly** [comment]
> you mean this PR in #1094 or you mean the changes in future?

Future changes. #1094 is already 2.5K loc, which is going to take a long time to give a good review.

> This BP covers both 2) and 3). while 1) is related but it is a different topic in general, we need to test all the scripts we shipped along with the release. so it will have to be a different task than the one here.

Sure.

**Comment by sijie** [comment]
@ivankelly create #1102 for bash script testing.

**Comment by ivankelly** [comment]
👍

**Pull request closed without merging**
