### PR TITLE
Issue 223: Code cleanups

### PR DESCRIPTION
**Pull request by sigee**
Descriptions of the changes in this PR:

There are some different kind of cleanups by commits. To make the code more readeable and improve code quality and improve performance in some cases.
E.g.: 
 - Remove unnecessary semicolons
 - Remove unused/unneeded/duplicated imports
- Replace l to L in long literals
- Remove boxing on an already boxed value
- Replace iterations to bulk operations

### CODE REVIEW

**Comment by eolivelli** [comment]
Thank you @sigee interesting proposal.

@sijie I think this patch could break some pending Pull Request

in general I am OK with this kind of patch but I think it would be better to have such cleanup at the start of next release or at the end of 4.5

it would be great to add maven checkstyle plugin to in the build pipeline in order to guarantee our coding conventions

**Comment by sigee** [comment]
@eolivelli,
If it is fine for you I can keep this PR up to date after every merge you make (and break this one).
So you can merge it when you want. ;)

I can add maven checkstyle plugin and attache it to the validate goal if you would like.

**Comment by eolivelli** [comment]
@sigee I will be happy to have the checkstyle plugin on but we should discuss on the dev@bookeeper.apache.org list about the rules to set up, maybe you can start a new thread

**Comment by sijie** [comment]
I am okay with using a checkstyle plugin. it shouldn't be a big deal with existing pull requests.

I am fine with merging this change and having a separate follow up jira to enable checkstyle plugin. Since DistributedLog is graduated as a subproject of BookKeeper, and there is already checkstyle rules in DistributedLog, it would be good to reuse the checkstyle rules there. https://github.com/apache/incubator-distributedlog/blob/master/distributedlog-build-tools/src/main/resources/distributedlog/checkstyle.xml

**Comment by jiazhai** [comment]
The change looks good, Please open an issue or a Jira ticket for this PR,  and at the end of this PR description, For the checks that you have done, please place "x" in the "[ ]".

**Comment by sigee** [comment]
@jiazhai, Opened an issue here: #223 

 @sijie, There was a conflict, I resolved, so at the moment this PR is mergeable if you think it is fine.

I started working on the CheckStyle, but there are lots of errors, I started to fix, so it is in progress. I'll create an issue and a different PR for that at the weekend.

**Comment by sijie** [comment]
@sigee do you mind creating an issue for the checkstyle changes and move the discussion there? I will the checkstyle change can be done in smaller batches, for example, package by package, so in this way, it is eaiser to review and less disruptive to other people's pull requests.

**Comment by jiazhai** [comment]
LGTM, but seems there is conflicts now.

**Comment by sigee** [comment]
@jiazhai, @eolivelli, @sijie, I've merged origin/master into my branch to resolve conflicts, but I see the following message: "This branch cannot be rebased due to conflicts"
What should I do to fix it?

**Comment by eolivelli** [comment]
Just issue a "git rebase master", this will be the output.
Usually I am more comfortable with "git rebase master" instead of merging from master.
We only merge with 'fast-forward" so that is the best procedure IMHO

```
First, rewinding head to replay your work on top of it...
Applying: Remove unnecessary semicolons
Using index info to reconstruct a base tree...
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
M	bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
Falling back to patching base and 3-way merge...
Auto-merging bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
Auto-merging bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
Auto-merging bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Applying: Symplify if statements
Applying: Use static member statically
Applying: Remove unused/unneeded/duplicated imports
Using index info to reconstruct a base tree...
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
M	bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Falling back to patching base and 3-way merge...
Auto-merging bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Auto-merging bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
Auto-merging bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
CONFLICT (content): Merge conflict in bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
error: Failed to merge in the changes.
Patch failed at 0004 Remove unused/unneeded/duplicated imports
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

```

**Comment by sigee** [comment]
@eolivelli, I've rebased my changes. Unfortunatelly I've needed to do a force push (this is why I didn't want it) with the new commits. (Rebase changed their hashes)
I don't like rebase or cherry pick in an existing PR after it is reviewed.

**Comment by eolivelli** [comment]
@sigee you are right, usually we prefer to append only commits to existing PRs so that the conversation is more fluent. Sometimes it is not possible...

Thank you

**Comment by sijie** [comment]
Re ""This branch cannot be rebased due to conflicts"" What should I do to fix it?

I don't think you need to rebase your pull request. When we merge the pull request, we do a squash merge with https://github.com/apache/bookkeeper/blob/master/dev/bk-merge-pr.py

Per BP-9, we want 'squash merge' not 'rebase and merge'? @jiazhai any thoughts?

**Comment by eolivelli** [comment]
@sijie I think that the problem is simply that the patch could not be applied without resolving conflicts.

Aside from this I think that the way we are merging patch leads to a linear git history, all made of "fast-forwards", which is equivalent to rebasing before merging
I think, but I am not sure, that "git merge --squash" is like "git rebase -i" but automatic

**Comment by sijie** [comment]
okay

**Comment by jiazhai** [comment]
@sijie The merge option issue has been fixed by INFRA team. Now we only have "squash and merge".  And thanks @eolivelli for the explanation.  Now seems it is clean now.

**Pull request closed without merging**
