### PR TITLE
add channel information if catch exception in BookieRequestHandler

### LINKED ISSUE #2475: BookieRequestHandler should provide remote address when catch exception
**BUG REPORT**

***Describe the bug***
Currently, [BookieRequestHandler](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java#L70)  only provides exception cause when catching exceptions. I think it's better to also log the  remote address, since it's helpful for trouble shooting if bookie have lots of connections.

***Additional context***
For now ,we can only know there is somthing wrong with one connection to bookie, but can not konw which connection .

```bash
2020-11-02 22:49:44,725 - ERROR [bookie-io-1-12:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
        at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
        at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
        at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
        at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316)
        at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:522)
        at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:938)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:525)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:423)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by aloyszhang**
### Motivation
fix #2475 
add channel information if catch exception in BookieRequestHandler

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM
@Ghatage @nicoloboschi @jiazhai  PTAL

this is worth to be committed for 4.12

**Review by Ghatage — APPROVED** [review]
LGTM +1

**Review by nicoloboschi — APPROVED** [review]
+1

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by eolivelli** [comment]
merged to master branch, thank you @aloyszhang  !

**Pull request merged**
