### PR TITLE
Remove unnecessary boxing unboxing

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
No need convert int to integer in main.

### CODE REVIEW

**Comment by Shoothzj** [comment]
@merlimat PTAL

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
Thanks for your contribution.
Usually I lean towards to not accept PRs tlike this one.
It is not fixing any real problem.
The boxing operation that you are saving is not on an hot path.

The patch would malke more sense of you try to take a look to all the useless boxing operations and make a general clean up

WDYT?

**Comment by Shoothzj** [comment]
> Thanks for your contribution. Usually I lean towards to not accept PRs tlike this one. It is not fixing any real problem. The boxing operation that you are saving is not on an hot path.
> 
> The patch would malke more sense of you try to take a look to all the useless boxing operations and make a general clean up
> 
> WDYT?

That's more worthful. I will use some tools to check it.
I just view at this, and change this line. 
From the machine view, it's not fixing any real problem. 
But from people view, it can make code more clean, more easier to read.

**Comment by Shoothzj** [comment]
But these small works can be aggregated together.

**Comment by Shoothzj** [comment]
@eolivelli I have took a general clean up, PTAL

**Review by eolivelli — APPROVED** [review]
Great and useful work!

Lgtm

**Comment by eolivelli** [comment]
Merged to master branch, thanks

**Pull request merged**
