### PR TITLE
getBookieInfo is stuck if no bookie is up

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation
getBookieInfo is stuck if no bookie is up

### Changes
Fix the problem, add a test case.
Also the getBookieInfoTimeout configuration was not  used, we were using the read entry timeout.

### CODE REVIEW

**Comment by eolivelli** [comment]
@Ghatage @karanmehta93  you may be interested in this fix

this fix is to be cherry picked to 4.12 and 4.11

**Comment by eolivelli** [comment]
We discovered this issue while working on BKVM
https://github.com/diennea/bookkeeper-visual-manager/pull/106

**Comment by eolivelli** [comment]
rerun-failure-checks

**Comment by eolivelli** [comment]
rerun failure tests

**Review by mino181295 — APPROVED** [review]

**Review by mino181295 — APPROVED** [review]

**Comment by eolivelli** [comment]
@nicoloboschi this fix is for BKVM

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by zymap — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
