### PR TITLE
[minor] [optimize] Remove redundant toString call

### PR DESCRIPTION
**Pull request by Shoothzj**
### Changes
- Remove redundant toString call
- fix typo

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh @nicoloboschi PTAL

**Review by merlimat — APPROVED** [review]

**Pull request merged**
