### PR TITLE
Issue 485: Change  'segment' to 'fragment' in docs

### PR DESCRIPTION
**Pull request by ArvinDevel**
Descriptions of the changes in this PR:
 Change  'segment' to 'fragment' in docs, and make some relative code more clearer

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue # or BOOKKEEPER-#>: Description of pull request`
>     `e.g. Issue 123: Description ...`
>     `e.g. BOOKKEEPER-1234: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install findbugs:check`.
> - [ ] Replace `<Issue # or BOOKKEEPER-#>` in the title with the actual Issue/JIRA number.
> 
> ---

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/6/

**Comment by sijie** [comment]
(all 3 checks have passed - wow!)

**Comment by ArvinDevel** [comment]
For the "segment", org.apache.bookkeeper.proto.DataFormats defines LedgerMetadataFormat.Segment as metadata for fragment of ledger, so the "segment" is also used in LedgerMetadata.java, BookKeeperAdmin.java to represent the metadata.
For the test, When I run 'mvn clean apache-rat:check install findbugs:check' in my laptop, sometimes all the checks passed, sometimes there exists some failure, maybe some test is sensitive to the environment.

**Comment by sijie** [comment]
@ArvinDevel it is fine in `LedgerMetadataFormat`. and the unit tests are not written very well, so some of them failed due to race conditions.

**Pull request closed without merging**
