### PR TITLE
Issue-561 Remove exec commands to start in the shell pid

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/bookkeeper-precommit-pullrequest-docker/105/

**Comment by eolivelli** [comment]
Can you create an issue and follow the guidelines, like naming the pr Issue-xxx ?

**Comment by ivankelly** [comment]
@eolivelli It's a small change, so I don't think it needs an issue. Forcing an issue to be created for all small changes will cause people to just bundle them with bigger changes.

@aahmed-se Some more description of why this change is good would be useful in the commit message.

**Comment by eolivelli** [comment]
@ivankelly we have already discussed this topic while introducing GitHub as issue tracker.
The conclusion was that it is important to always have an issue:
1) release notes and general roadmap are created from issues
2) high level discussion is done in the issue and comments on pr are only for code changes/comments

in this case we want an issue for 1)
I understand that it can seem a useless cost, but with JIRA we did the same

I think you can resurrect the thread on the mailing list if you want.

**Comment by ivankelly** [comment]
@eolivelli 

> release notes and general roadmap are created from issues

This change hold no interest for neither release notes or roadmap.

> I understand that it can seem a useless cost, but with JIRA we did the same

We don't want to replicate what we used to do with JIRA. That workflow was super painful, and I think it contributed to the situation where twitter and yahoo had their own branches, because things moved so slowly on mainline.

From the contribution guide [1].
> If the change is new, then it usually needs a new JIRA ticket / Github issue. However, trivial changes, where "what should change" is virtually the same as "how it should change" do not require a JIRA ticket. Example: "Fix typos in Foo javadoc"

We should update that guide to remove JIRA.

[1] https://cwiki.apache.org/confluence/display/BOOKKEEPER/Contributing+to+BookKeeper

**Comment by eolivelli** [comment]
@ivankelly I did a first pass on the guide on Confluence.
You are right that we wrote that for trivial changes an issue it not required.

I am fine with changing the PR description without creating the issue but I just wanted to report usual discussions on the community

//cc @sijie

**Comment by ivankelly** [comment]
@aahmed-se @eolivelli I think this is ready to merge.
@sijie Any opinion?

**Comment by jiazhai** [comment]
Right, It was Flavio's suggestion to create issue for each PR, and we agreed on that in community meeting. I recall the reason were mainly that:
- It will unify make the PR title;
- "trivial changes" is not a clear rule to follow.

**Comment by jiazhai** [comment]
This change LGTM. :)

**Comment by eolivelli** [comment]
created #557 
I am merging this PR now

**Comment by aahmed-se** [comment]
thank you

**Pull request closed without merging**
