### PR TITLE
Issue-553: Documentation for new fluent API

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- Add documentation for the new fluent API: create/open/delete, append/write/read, createadv

### CODE REVIEW

**Comment by sijie** [comment]
This change is for #553 and related to #728

**Comment by eolivelli** [comment]
@jiazhai  @sijie can we merge this and eventually make minor fixes and follow up ?

/cc @lucperkins

**Comment by sijie** [comment]
@eolivelli merged. it should unblock you now.

**Pull request closed without merging**
