### PR TITLE
remove legacy code to resole class missing error

### PR DESCRIPTION
**Pull request by aloyszhang**
Descriptions of the changes in this PR:

On the master branch,  TestTxnId can't find the dependency of `org.apache.bookkeeper.bookie.TestBookieImpl`.

### Motivation

remote the dependency and legacy code since it's not used

### Changes

remote the dependency and legacy code

### CODE REVIEW

**Comment by gaozhangmin** [comment]
+1

**Review by Vanlightly — APPROVED** [review]
Thanks @aloyszhang.

**Comment by aloyszhang** [comment]
@eolivelli PTAL, thanks!

**Review by dlg99 — APPROVED** [review]

**Comment by aloyszhang** [comment]
@Vanlightly I think this pull request is ready to merge. PTAL, thanks!

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
