### PR TITLE
Bringing back maven build

### PR DESCRIPTION
**Pull request by dlg99**
### Motivation

Bringing back maven build as per [conversation on ML](https://lists.apache.org/thread/wplcncz160d8z9wzmw1d68mcbrnjkf0b).

### Changes

Reverted change that deleted mvn build, fixed dependencies that were changed after the mvn deletion, suppressed warnings in tests (gradle build seems to ignore the warnings)

### CODE REVIEW

**Review by nicoloboschi — CHANGES_REQUESTED** [review]
Are you able to restore github actions? In this way we are sure the build is stable

**Comment by eolivelli** [comment]
Apache RAT fails due to "site3" directory, please add the exclusion:

```
diff --git a/pom.xml b/pom.xml
index aa1cb6f62..e7108f889 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1014,6 +1014,7 @@
             <!-- Website -->
             <exclude>site/**</exclude>
             <exclude>site2/**</exclude>
+            <exclude>site3/**</exclude>
 
             <!-- Thrift generated files -->
             <exclude>**/org/apache/distributedlog/thrift/*</exclude>
```

**Comment by eolivelli** [comment]
I built the package locally and run "localbookie" and a small bookkeeper cluster (tested with BKVM).
Everything looks good.
I am now running all the tests locally.

**Comment by dlg99** [comment]
@nicoloboschi @eolivelli I could not just revert the changes for the GH actions because there commit after that. I did the changes manually/picked them from branch 4.14 mostly. I left javadoc generation with gradle. Backwards compat tests also left running with gradle, plus added one action that simply builds everything with gradle but does not run tests.

**Comment by eolivelli** [comment]
There are problems with the license check

**Comment by eolivelli** [comment]
Problems with the docker image for tests 
Error: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project current-version-image: Missing Dockerfile in context directory: /home/runner/work/bookkeeper/bookkeeper/tests/docker-images/current-version-image -> [Help 1]

**Comment by eolivelli** [comment]
Very good!
I see only CompactionByEntriesWithoutMetadataCacheTest is failing.
It is not related to Maven

**Comment by dlg99** [comment]
I fixed `CompactionByEntriesWithMetadataCacheTest` in this PR because it was failing rather consistently.
The cases that were failing pass when I ran them one-by-one, it is possible gradle re-runs the failed tests differently from maven hence it was not as noticeable there. 
`org.apache.bookkeeper.test.BookieZKExpireTest` flakes on CI but I cannot repro it locally and it finally passed on the re-run.

@eolivelli @nicoloboschi Please take another look.

**Review by nicoloboschi — APPROVED** [review]
I did some checks locally:
- build with mvn (no tests) 
- started a bookie and run simple test shell command
-  checked dependencies versions matching between maven and gradle

great work @dlg99 !

**Review by zymap — APPROVED** [review]
+1 

Build with this branch
Run the zookeeper server + 1 bookie
Run the simpletest command successfully

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
