### PR TITLE
Remove log4j1 from bk test code

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
this is a part work of remove log4j1 from bookeeper, first remove it from our test code, unit test and integrate test

### Changes
- remove log4j1 scope test dependency
- use log4j2.xml instread of log4j.properties
- introduce testtools module to reduce duplication,  if a module needs particular configuration (very unlikely) we can add a log4j2-test.xml file which has precedence over log4j2.xml one. idea from [nicoloboschi](https://github.com/nicoloboschi)

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Great work

**Comment by eolivelli** [comment]
@nicoloboschi @dlg99  it looks like the CI job 'PR validation' still used Gradle

**Comment by eolivelli** [comment]
@Shoothzj could you please move the PR validation job to Maven?

**Comment by Shoothzj** [comment]
> @Shoothzj could you please move the PR validation job to Maven?

now we have `backward-compat-tests` and `pr-validation` step `Generate Javadoc`. I will do it in another pr

**Comment by Shoothzj** [comment]
@dlg99 @nicoloboschi @merlimat @pkumar-singh PTAL

**Comment by Shoothzj** [comment]
@dlg99 @nicoloboschi @merlimat @pkumar-singh PTAL

**Review by nicoloboschi — APPROVED** [review]
Great work!

**Comment by Shoothzj** [comment]
@dlg99 @merlimat @pkumar-singh PTAL

**Comment by hangc0276** [comment]
When I run `LedgerStorageCheckpointTest` in idea, it throws the following exception. I'm not sure whether related to this PR, would you please help take a look? Thanks a lot. @Shoothzj 

```
ERROR StatusLogger Unable to create Lookup for bundle
 java.lang.ClassCastException: class org.apache.logging.log4j.core.lookup.ResourceBundleLookup
	at java.lang.Class.asSubclass(Class.java:3404)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:79)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:100)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:133)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:74)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at org.apache.bookkeeper.bookie.LedgerStorageCheckpointTest.<clinit>(LedgerStorageCheckpointTest.java:84)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

**Comment by Shoothzj** [comment]
@hangc0276 My computer needs repair. I will check it after few days.

**Pull request merged**
