### PR TITLE
[Test] migrate-junit5-client-module

### LINKED ISSUE #4322: Migrate tests from junit4 to junit5
JUnit 5 offers significant improvements over JUnit 4, including more powerful and flexible testing capabilities like annotation-based coding(so we don't need to write assume), parallel test execution, and other features. We can write new test classes using junit5, and existing-test classes can be slowly migrated.

This issue to track tests migrate to junit5, we can migrate a package、a small module gradually.

See also:
 https://lists.apache.org/thread/hlyc722gy45s3y61q7n79hdcr6cgrx7v

### PR DESCRIPTION
**Pull request by sherlock-lin**
Descriptions of the changes in this PR:

Main Issue: #4322

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
> Fix https://github.com/apache/bookkeeper/issues/4322

 do not close the issue if it is just a subtask of an issue

**Comment by sherlock-lin** [comment]
> > Fix #4322
> 
> do not close the issue if it is just a subtask of an issue Fix #4322 is mean close the issue 4322 when this PR is merged

@liangyuanpeng Thanks, I'll avoid the same mistake in the future

**Comment by sherlock-lin** [comment]
please help review

**Comment by sherlock-lin** [comment]
@shoothzj  please help review

**Review by xiezhx9 — APPROVED** [review]
LGTM

**Comment by sherlock-lin** [comment]
> it contains too many format code, can we avoid this?
Ok, I'll make some adjustments.

**Comment by sherlock-lin** [comment]
> it contains too many format code, can we avoid this?
Ok, I'll make some adjustments.

**Pull request closed without merging**
