### PR TITLE
BOOKKEEPER-1043 Upgrade Apache Parent Pom Reference to latest version

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by eolivelli** [comment]
Thank @revans2  and @ivankelly for your review

I have merged this PR on https://git-wip-us.apache.org/repos/asf/bookkeeper.git
but GitHub mirror is not yet up-to-date

@sijie 
I have used the standard script. Let's wait for the @asfgit bot to perform the synch.
The PR will be closed

**Comment by sijie** [comment]
@eolivelli how did you merge this PR? Are you using the merge script?

**Comment by eolivelli** [comment]
@sijie yes. It conpleted with success.

But I have used my work laptop which did not have the jira python plugin.

**Comment by sijie** [comment]
This is weird. even you don't have jira plugin, the script won't close the jira but it will still close the pull request.

**Comment by sijie** [comment]
@eolivelli I am not sure why the merge scripts doesn't close this pull request. 

Can you manually close your pull request and resolve the jira?

**Comment by eolivelli** [comment]
Merged

**Pull request closed without merging**
