### PR TITLE
BOOKKEEPER-1010 Moving Guava to 20.0

### PR DESCRIPTION
**Pull request by arvindkandhare**
Moving Guava version from 13 to 20.0

### CODE REVIEW

**Comment by sijie** [comment]
@eolivelli - Let's separate "bumping the version" from "shading guava". Can you create a jira for "shading guava"?

**Comment by sijie** [comment]
@arvindkandhare this jenkins build failed. can you fixed it?

**Comment by eolivelli** [comment]
@sijie I have created the issue for shading Guava https://issues.apache.org/jira/browse/BOOKKEEPER-1012

**Comment by arvindkandhare** [comment]
@sijie looking at the failing tests. Will get back with a fix.

**Comment by eolivelli** [comment]
@arvindkandhare do you have news ?

**Comment by arvindkandhare** [comment]
Hi, I am not able to get the same error locally and I have lost the Jenkins build. What is the procedure to kick it off again? If you could share that it will be helpful to get me started on this again.

**Comment by eolivelli** [comment]
Just push again a commit  agaist your branch on github or maybe close and reopen the PR

**Comment by arvindkandhare** [comment]
Thanks for the pointers.

**Comment by eolivelli** [comment]
Thanks @arvindkandhare for trying to shade guava.
This test is failing because legacy compats on the classpath are tring to use the non shaded version of guava.
TestBackwardCompat.testCompatReads:751 » NoSuchMethod com.google.common.util.c.

I will look into this problem deeper, there are several ways to fix but I am not sure of which is the best option.
If you prefer you can leave unshaded guava for this pr and I will continue with the shade.
If the error is not related to the shade you will have to shade the old version of guava inside the compats deps and relocate it to a different package name

**Comment by eolivelli** [comment]
Another question. The latest version is 21. Is there a reason to get to 20 and not to 21?
Anyway if we shade guava we can use whatever version we want.
Sorry for typos. I am writing with my phone

**Comment by arvindkandhare** [comment]
I do not think version 20 or 21 matters a lot. Looks like I have not moved from exceptions to hang :). Will try and find a way to fix this. Do let me know if you have any further suggestions.

**Comment by eolivelli** [comment]
@arvindkandhare I have addressed all the issue.
Basically you forget to add an "include" clause in compat dependencies poms and relocate all guava classes.
As a class (HostAndPort) has been marked as "deprecate" a SuppressWarnings annotation needs to be added in the CodahaleMetricsProvider

I have pushed a working branch here
https://github.com/eolivelli/bookkeeper/tree/guava_version

You can take the last commit
https://github.com/eolivelli/bookkeeper/commit/b3d0ae8627c03356e1fd450326a5ef100f5b05dd

I hope that helps

The last thing to do is to ensure that Guava is not used in any "public" API (BookKeeper,LedgerHandler, Auth Plugin API, LedgerManager API, EnsemblePlacement API...and so on)
Recently we had to break compatibility because Protobuf was "shaded" and used in the Auth Plugin API explicitly

**Comment by eolivelli** [comment]
@arvindkandhare  ping

**Comment by sijie** [comment]
@arvindkandhare any updates? Do you want to merge @eolivelli 's patch?

**Comment by arvindkandhare** [comment]
Will merge @eolivelli's patch and update my PR. Thanks.

**Comment by eolivelli** [comment]
@arvindkandhare seems that apache-rat:check is failing here https://builds.apache.org/job/bookkeeper-master-git-pullrequest/384/

Failed to execute goal org.apache.rat:apache-rat-plugin:0.7:check (default-cli) on project bookkeeper: Too many unapproved licenses: 1 -> [Help 1]

**Comment by sijie** [comment]
@arvindkandhare @eolivelli any updates on this?

**Comment by eolivelli** [comment]
@sijie  I think that my version of this patch is overll OK
 @arvindkandhare I you want I can pick this issue and finish the details

**Comment by sijie** [comment]
@eolivelli  please go ahead. let's move first.

**Comment by eolivelli** [comment]
I have created a new PR, #166 
@arvindkandhare you can close this PR ?

**Pull request closed without merging**
