### PR TITLE
Upgrade protobuf to 3.14.0 (latest)

### PR DESCRIPTION
**Pull request by dlg99**
Descriptions of the changes in this PR:

Upgraded protobuf dependency

### Motivation

unit tests log "WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil" on Java11
This has been fixed in protobuf since version 3.7

### Changes

Upgraded protobuf; 
updated code to remove use of deprecated methods

Master Issue: #2579

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
+1

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
I am not sure we can port this patch to 4.12 branch, it is a non trivial library upgrade

@merlimat @sijie @rdhabalia @nicoloboschi @fpj  what do you think ?

**Comment by lhotari** [comment]
AFAIK, Protobuf versions <3.8.0 aren't compatible with Protobuf generated classes that have been compiled with Protobuf protoc >=3.8.0 ([due to a breaking change in Protobuf Java in 3.8.0](https://github.com/protocolbuffers/protobuf/commit/d0f91c863ae0fbb75b41460c8bbb786ade197a0f#diff-8168b8744060c287ceee789b0eb8cbb4R403-R405)) 
This probably won't be an issue with Bookkeeper and the usage of it's libraries?

**Comment by eolivelli** [comment]
On Pulsar we are using Protobuf, at least in 2.7., for 2.8 we are going to use a new Protobuf compatible library contributed by Splunk.
So it won't be a problem for Pulsar 2.8+

For users of BK...basic BK is not using GRPC, it is only for the StreamStorage service
I don't know other users of the StreamStorage service other than Pulsar Stateful Functions

**Pull request merged**
