### PR TITLE
upgrade netty version to 4.1.79.Final released

### PR DESCRIPTION
**Pull request by tyluffy**
## Motivation
fix some netty bugs for: 
https://github.com/netty/netty/pull/12370
https://github.com/netty/netty/pull/12490
### changeLog:
https://netty.io/news/2022/06/14/4-1-78-Final.html
https://netty.io/news/2022/07/11/4-1-79-Final.html

## Modifications
Upgrade Netty from 4.1.77.Final to 4.1.79.Final

### CODE REVIEW

**Comment by StevenLuMT** [comment]
what is this pr's motivation?
please explain: why you're making that change ?

**Comment by Shoothzj** [comment]
@tyluffy Thanks for your contribution, could you please fill the PR template?

**Review by Shoothzj — CHANGES_REQUESTED** [review]
does netty boringssl version needs change?

**Review by hangc0276 — CHANGES_REQUESTED** [review]
@tyluffy  Thanks for your contribution.
1. Would you please explain the new version resolves which problem in BookKeeper?
2. Would you please update the version in the license files?

**Comment by tyluffy** [comment]
> @tyluffy Thanks for your contribution, could you please fill the PR template?

ok

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
4.1.77.Final
you not only have to update this pom.xml,
you have to update other files as well

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Pull request closed without merging**
