### PR TITLE
BOOKKEEPER-1031: close the ledger handle in ReplicationWorker.rerepli…

### PR DESCRIPTION
**Pull request by athanatos**
…cate

Otherwise, we build up an unbounded set of Listeners in the
AbstractZkLedgerManager listenerSet structure which never go
away.

Signed-off-by: Samuel Just <sjust@salesforce.com>

### CODE REVIEW

**Comment by eolivelli** [comment]
@sijie can you add Samuel to the contributors in JIRA so that the issue can be assigned to him?

**Comment by athanatos** [comment]
Build's failing due to

Tests in error:
  BookieRecoveryTest.ensurePasswordUsedForOldLedgers[4] » BKNoSuchLedgerExists
  BookieRecoveryTest.ensurePasswordUsedForOldLedgers[5] » BKNoSuchLedgerExists

which seems to be broken in master.

I did a bisect and found that

https://github.com/apache/bookkeeper/commit/42e8f1294f206cbe51a6af669cf605833b78bf42 introduced both a hang in that test and that test failure.  https://github.com/apache/bookkeeper/commit/32ebf0ad68f85daffdec571e28206339a4d09443 fixed the hang uncovering the test failure.

**Comment by sijie** [comment]
@athanatos I think those two are known failures. I think @eolivelli knew about it.

**Comment by athanatos** [comment]
Cool, what's the next step?

**Comment by eolivelli** [comment]
We are going to merge as soon as possible. Thank you

**Comment by sijie** [comment]
merging now

**Pull request closed without merging**
