### PR TITLE
BP-68: Delete cookie as part of decommission API.

### PR DESCRIPTION
**Pull request by Karthickramk**
Descriptions of the changes in this PR:

New BP for deleting cookie as part of bookkeeper decommission API
https://github.com/apache/bookkeeper/issues/4499
Proposal PR: WIP

### CODE REVIEW

**Review by StevenLuMT — APPROVED** [review]
Good Job

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by shoothzj** [comment]
It's http body or url param?
```
{
"delete_cookie": true
}
```
or
```
?delete_cookie=true
```

**Comment by Karthickramk** [comment]
It is part of the body along with bookie_src.

Thanks,
Karthick

**Review by dlg99 — APPROVED** [review]

**Review by wenbingshen — APPROVED** [review]
LGTM. The default behavior is sufficient to maintain forward compatibility.

**Pull request merged**
