### PR TITLE
Upgrade Netty to 4.1.86.Final

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- see release notes for 4.1.85.Final: https://netty.io/news/2022/11/09/4-1-85-Final.html
- see release notes for 4.1.86.Final: https://netty.io/news/2022/12/12/4-1-86-Final.html

It is unknown whether there are fixes that specifically target Netty features used in Bookkeeper. One of the motivation of this PR is to upgrade Netty in Bookkeeper when the Netty version gets upgraded in Pulsar. The PR for Netty 4.1.86.Final upgrade in Pulsar is apache/pulsar#18599

### Changes

Upgrade Netty version to 4.1.86.Final

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Comment by hangc0276** [comment]
@lhotari Thanks for your contribution, please take a look at the license check, thanks.

**Comment by lhotari** [comment]
Netty 4.1.85.Final upgrade causes a regression in Pulsar. I have commented on the Netty change about this: https://github.com/netty/netty/pull/12888#issuecomment-1327795901 . It seems that there is a major change in behavior in Netty's HashedWheelTimer.

**Review by hangc0276 — CHANGES_REQUESTED** [review]
Waiting for Netty new release

**Comment by lhotari** [comment]
Upgraded to 4.1.86.Final which reverts the HashedWheelTimer change and includes some CVE fixes. See release notes for Netty changes. (referenced in PR description)

**Comment by lhotari** [comment]
@hangc0276 Please re-review this PR and possibly also merge it.

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
