### PR TITLE
Issue 1799: bkctl is broken with default build options 

### PR DESCRIPTION
**Pull request by eolivelli**
This is a cherry pick of #1799 on branch-4.8.
Original commit is from Sijie Guo

Descriptions of the changes in this PR:

*Motivation*

`bkctl` is designed in a modularized way for extensibility.
it loads command groups via ServiceLoader. However current build
profile doesn't leverage this extensibility. Instead it hardcodes
all the commands in one service load file. So if `bkctl` is built
without `-Dstream`, it will broke.

*Changes*

- move `ledger` related commands to `tools/ledger`
- generate the service load file by concating `commands` files from each module's resources directory.

*Results*

bkctl works for all build profiles.

- without `-Dstream`

```
$ bin/bkctl

bkctl interacts and operates Apache BookKeeper clusters

Usage:  bkctl [flags] [command group] [commands]

Commands:

    bookie      Commands on operating a single bookie
    bookies     Commands on operating a cluster of bookies
    cookie      Commands on operating cookies
    ledger      Commands on interacting with ledgers

    help        Display help information about it

Flags:

    -c, --conf
        Configuration file

    -n, --namespace
        Namespace scope to run commands (only valid for table service for now)

    -u, --service-uri
        Service Uri

    -h, --help
        Display help information

Use "bkctl [command] --help" or "bkctl help [command]" for more information
about a command
```

- with `-Dstream`

```
$ bin/bkctl

bkctl interacts and operates Apache BookKeeper clusters

Usage:  bkctl [flags] [command group] [commands]

Commands:

    bookie          Commands on operating a single bookie
    bookies         Commands on operating a cluster of bookies
    cluster         Commands on administrating bookkeeper clusters
    cookie          Commands on operating cookies
    ledger          Commands on interacting with ledgers
    namespace       Commands on operating namespaces
    table           Commands on interacting with tables
    tables          Commands on operating tables

    help            Display help information about it

Flags:

    -c, --conf
        Configuration file

    -n, --namespace
        Namespace scope to run commands (only valid for table service for now)

    -u, --service-uri
        Service Uri

    -h, --help
        Display help information

Use "bkctl [command] --help" or "bkctl help [command]" for more information
about a command
```

Master Issue: #1799

### CODE REVIEW

**Comment by sijie** [comment]
#1802 has to go in first.

**Comment by eolivelli** [comment]
@sijie  @ivankelly #1802 has been merged, I have rebased this patch on top of current branch-4.8

**Comment by eolivelli** [comment]
I will re run integration tests locally.
It is a big nuisance for contributors, we should fix this

**Comment by sijie** [comment]
branch-4.8 doesn't have `.test-infra/scripts/pre-docker-tests.sh` and `.test-infra/scripts/post-docker-tests.sh`

We can port those integration related test scripts to branch-4.8 and branch-4.7.

**Comment by eolivelli** [comment]
@sijie yes it will be better.
I do not have my laptop now, tomorrow I will see the result and eventually commit this change.
I am not aware of all the docker scripts we have, if you have time to port the minimal set of files to make those branch compatible with current CI jobs it will be great

**Comment by eolivelli** [comment]
IGNORE IT CI

**Pull request merged**
