### PR TITLE
[CI] Migrate the Jenkins CI to Github Action

### PR DESCRIPTION
**Pull request by zymap**
---

Master Issue: #2242

*Modifications*

Migrate theJenkins CI to Github Action

### CODE REVIEW

**Comment by zymap** [comment]
It's might I haven't right permission to create the Github Actions. The [Github Actions](https://github.com/apache/bookkeeper/actions) shows only collaborators may create it.

I will test it on my branch.

**Comment by eolivelli** [comment]
@zymap  I like this change.
But can you please start a discussion on dev@bookkeeper.apache.org

we need the community to agree

**Comment by zymap** [comment]
@eolivelli Sure. 

BTW, all Github actions have been passed under my repo.

**Comment by eolivelli** [comment]
@zymap Yes I saw then and I am very happy and I would like to commit this change soon.

**Comment by sijie** [comment]
ignore ci

**Pull request merged**
