### PR TITLE
Add slack-digest script which generates per channel digest emails to …

### PR DESCRIPTION
**Pull request by Ghatage**
…be emailed to the respective mailing lists.

Original script by @merlimat from his [private repo](https://github.com/merlimat/slack-email-digest).
Copied to BK repo for use with the BookKeeper project.

### CODE REVIEW

**Comment by eolivelli** [comment]
One check  failed PTAL

**Comment by eolivelli** [comment]
` Too many files with unapproved license: 3 See RAT report in: `

You have to add license header where possible or add exclusions to the Apache Rat plugin configuration in pom.xml

**Comment by Ghatage** [comment]
@eolivelli done.
Next steps are to set it up properly in a Jenkins job.
Will need your help for that as I am not aware of where the jobs are run nor do I have access.

**Comment by eolivelli** [comment]
@Ghatage I have committed this patch.
In order to create a jenkins job you have to add a groovy file to .test-infra/jenkins directory.
We are using Jenkins DSL

You can find our jenkins at https://builds.apache.org
you do not have access to configuration of jobs but actually the configuration is made thru those scripts

thank you very much

**Pull request merged**
