### PR TITLE
[build] support circe-checksum and cpu-affinity build on Windows

### PR DESCRIPTION
**Pull request by magiccao**
Descriptions of the changes in this PR:

### Motivation

(Explain: why you're making that change, what is the problem you're trying to solve)
try to fix issue: #2270

### Changes

(Describe: what changes you have made)

Master Issue: #2270 

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
very cool.
I cannot test it locally.

I would like to merge this patch

@nicoloboschi @dianacle @aluccaroni do you have a way to test building this branch on a windows machine ?

**Review by aluccaroni — CHANGES_REQUESTED** [review]
I'm not able to build correctly on Windows 10, I see a GCC error:

```
Starting Core 1 with 1 source files...
[ERROR] circe/cpp/crc32c_sse42.cpp: In function 'uint32_t crc32c_chunk(uint32_t, const void*, const chunk_config&)':
[ERROR] circe/cpp/crc32c_sse42.cpp:96:66: error: '_mm_crc32_u64' was not declared in this scope
[ERROR]      uint64_t crc0 = config.extra() > 1 ? _mm_crc32_u64(crc, *pq++) : crc;
[ERROR]                                                                   ^
[ERROR] circe/cpp/crc32c_sse42.cpp:110:77: error: '_mm_cvtsi64_si128' was not declared in this scope
[ERROR]          __m128i mul1 = _mm_clmulepi64_si128(_mm_cvtsi64_si128((int64_t) crc1), k, 0x10);
[ERROR]                                                                              ^
[ERROR] circe/cpp/crc32c_sse42.cpp:112:49: error: '_mm_cvtsi128_si64' was not declared in this scope
[ERROR]          tmp ^= (uint64_t) _mm_cvtsi128_si64(mul1);
[ERROR]                                                  ^
[ERROR] circe/cpp/crc32c_sse42.cpp: In function 'uint32_t crc32c_words(uint32_t, const void*, size_t)':
[ERROR] circe/cpp/crc32c_sse42.cpp:145:54: error: '_mm_crc32_u64' was not declared in this scope
[ERROR]              crc = (uint32_t) _mm_crc32_u64(crc, *pq++);
[ERROR]     
```                                                  ^

Info regarding the system:

- Windows 10 Pro 64bit
- Java AdoptOpenJDK 11.0.7.10
- Git Bash
- Maven 3.6.3
- GCC g++ 6.3.0-1 (MinGW)

**Comment by Ghatage** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
`OWASP Dependency Check` failure: both `google-http-client-gson` and `maven-settings` are not related to this PR

**Pull request merged**
