### PR TITLE
#2279 fix NPE when exec readjournal command

### PR DESCRIPTION
**Pull request by aloyszhang**
Descriptions of the changes in this PR:
This PR fix NullPointerException when exec readjournal command
See issue #2279

### CODE REVIEW

**Comment by aloyszhang** [comment]
Parameter `-dir` must be specified when bookie has more than one directories for `journalDirectories` while not need when only one journal directory.

**Comment by aloyszhang** [comment]
cc @eolivelli

**Comment by eolivelli** [comment]
Yes but if you only have one directory the parameter is not required.
With this patch you are making it always required.

**Comment by aloyszhang** [comment]
As I understand, if `hasArg` of an `Option`  set to true,  it means that an argument is required after this option other than this `Option`  is must be specified.
We still can run the command without the parameter `-dir` like this 
 ```
./bin/bookkeeper shell readjournal /data1/bookkeeper/journal/current/170ab39159f.txn 
```
and this command runs well.

**Comment by aloyszhang** [comment]
cc @eolivelli please have a look.

**Comment by eolivelli** [comment]
I am sorry.
I clicked on 'close and comment' instead of 'comment'

**Pull request merged**
