### PR TITLE
Fixed: DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause

### PR DESCRIPTION
**Pull request by dlg99**
DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause
Same as https://github.com/apache/bookkeeper/pull/2553 but for master branch

Descriptions of the changes in this PR:

added .initCause for the new FNFE exception to preserver it

### Motivation

got the
ERROR org.apache.bookkeeper.statelib.impl.rocksdb.checkpoint.RocksCheckpointer - Failed to restore rocksdb ...
java.io.FileNotFoundException: ..../metadata
without any additional info for the rootcause (other than stack pointing to the DLCheckpointStore)

DLCheckpointStore appears to re-throw exceptions as FNFE without preserving the rootcause

### Changes

added .initCause

Master Issue: #2552
> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks.
>
> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by eolivelli** [comment]
rerun-failure-tests

**Comment by dlg99** [comment]
rerun-failure-tests

**Comment by eolivelli** [comment]
@dlg99 as you are a committer here you can enter the github action page and click in 'rerun job'. It is quicker than using the magic comment

**Review by eolivelli — APPROVED** [review]
LGTM

**Pull request merged**
