### PR TITLE
Bump testcontainers version to 1.16.3

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
- Bump the testcontainers version to make tests can run on the latest docker on `Mac Intel Chip`
- Bump `docker-java` version to `3.2.13`

### CODE REVIEW

**Review by nicoloboschi — CHANGES_REQUESTED** [review]
We need to update docker-java as well

**Comment by Shoothzj** [comment]
> We need to update docker-java as well

Thanks for your attention. Is that needed on linux or windows? After update `testcontainers`, I can run unit-tests on my laptop.

**Comment by nicoloboschi** [comment]
It's usually better to have the matching version in order to avoid unexpected behaviors

**Review by nicoloboschi — APPROVED** [review]

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by dlg99 — APPROVED** [review]

**Pull request merged**
