### PR TITLE
(WIP) Enable bytebuf leak detection in tests

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

distributedlog already enables leak detection at some modules. it would be good to enable leak detection for all the modules across the project.

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by sijie** [comment]
this change is only to enable leak detection. given we are heavily using netty bytebuf. we should watch this closely on tests.

the next step is to address any potential leaks (either in the main bookkeeper code or testing code itself), then enable CI to fail build if testing output contains "LEAK".

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
@jiazhai I think there are some issues got exposed after enabled leak detection, that's why jenkins failed. I am trying to fix some of them. so "retest" is not helping here.

I am turning this PR to WIP until I fixed the issues I found here.

**Comment by eolivelli** [comment]
@sijie how is going this work?

**Comment by eolivelli** [comment]
@sijie are you still working on this ? there is a conflict on pom.xml , can we fix it so that we can use this PR to look for leaks ?

**Comment by sijie** [comment]
@eolivelli I am not active on this. This requires quite tons of work, because some of the tests are failing after enabling this.

**Comment by sijie** [comment]
io.netty.leakDetection.level is enabled at #1613

**Pull request closed without merging**
