### PR TITLE
add bookie expand or shrink directories operation guide

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation

Currently, BookKeeper website doesn't have any operation guide for shrink or expand journal/ledger directories.

### Changes
Add the operation guide for shrink or expand journal/ledger directories.

### CODE REVIEW

**Comment by zymap** [comment]
Here has a mail about this: http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/202111.mbox/browser

**Comment by Vanlightly** [comment]
> Here has a mail about this: http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/202111.mbox/browser

Considering that data loss is an outcome of this operation, I think that should be clearly communicated here. When this data loss is addressed in a future patch we can modify the docs.

**Comment by dlg99** [comment]
maybe it is better to recommend to NOT use the shrink/expand procedure at all and instead decomm the bookie/add it back with shrunk/expanded storage.

**Comment by StevenLuMT** [comment]
hi @hangc0276 
I would like to know how the current PR is going.

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Review by jiazhai — APPROVED** [review]

**Pull request closed without merging**
