### PR TITLE
Add maven tools

### PR DESCRIPTION
**Pull request by CalvinKirs**
Descriptions of the changes in this PR:

Using `maven-wrapper` can save users from installing maven,
and can lock the version, at the same time, improve our build time. 3.X's `maven-warpper` performance has been greatly improved.

### CODE REVIEW

**Comment by StevenLuMT** [comment]
"performance has been greatly improved."
do you have some test  data?

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
improve build time from *** to ***
do you have some test data?

**Comment by CalvinKirs** [comment]
> improve build time from *** to *** do you have some test data?

He has about 10% improvement on my M1 machine, which is also an optimization made by the official.

**Comment by StevenLuMT** [comment]
fix old workflow,please see #3455 for detail

**Review by nicoloboschi — COMMENTED** [review]
@CalvinKirs could you rebase ?

**Comment by hangc0276** [comment]
@CalvinKirs Thanks for your contribution. Would you please rebase the master and resolve the conflicts? Thanks a lot. After those conflicts are resolved, I will move back to the 4.16.0.

**Comment by shoothzj** [comment]
@CalvinKirs Are you still want to working on this? Could you please rebase the master code? Thanks

**Comment by shoothzj** [comment]
closed by no updte, feel free to reopen it if you still want to working on this.

**Pull request closed without merging**
