### PR TITLE
stage 9: bugfix indexDirs for LedgersIndexRebuildOp

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

planning for index dir: [mail talking](https://lists.apache.org/thread/r657jf55khl59bbqltj2s95107lbkr0w)
stage 9 : 
1)  fix indexDirs for LedgersIndexRebuildOp

### Changes

1.  bugfix indexDirs for LedgersIndexRebuildOp
2. add index's testcase for LedgersIndexRebuildOp

### CODE REVIEW

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Comment by StevenLuMT** [comment]
rerun failure checks

**Review by dlg99 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
