### PR TITLE
Issue 1147: Move bookkeeper-server/{bin,conf} to root module

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

*Motivation*

since 4.7, we are shipping the binary distribution using bookkeeper-dist modules. so it is making more sense to have {bin,conf} directory at root module,
rather than bookkeeper-server module.

*Solution*

- move bookkeeper-server/bin to bin
- move bookkeeper-server/conf to conf
- update the new bookkeeper cli related files as "experimental"

This change is needed for integrating with dlog scripts for BP-26 and new bookkeeper cli for BP-27.

Master Issue: #1147 

Related Issues:

- BP-26 #1024 
- BP-27 #1000 

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by sijie** [comment]
A few other notes:

- this existing IT tests covers testing the bookkeeper-server package, which would cover testing the scripts to some extent.
- we can consider using [shunit2](https://github.com/kward/shunit2) for testing shell scripts in future.
- remove "copy right" lines from license headers, because they are not needed for files in apache project.

**Comment by ivankelly** [comment]
retest this please

**Comment by ivankelly** [comment]
rekicked the test because the IT had failed for some weird reason (couldn't connect to zk container, no reason given).

**Comment by sijie** [comment]
yes I tested from source and the compiled packages `bookkeeper-server` and `bookkeeper-all`.

**Comment by sijie** [comment]
retest this please

**Pull request closed without merging**
