### PR TITLE
ISSUE #507: Introduce @FlakyTest annotation for marking a few tests as flaky

### LINKED ISSUE #507: Introduce @FlakyTest annotation for marking a few tests as flaky
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Add an annotation `@FlakyTest` for marking a few tests as flaky. So we can bring CI back to normal while at the same time working on fixing flaky tests.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

### PR DESCRIPTION
**Pull request by ivankelly**
Descriptions of the changes in this PR:

- introduced FlakyTest annotation
- mark a few tests as flaky tests (create issues for them)

Author: Sijie Guo <sijie@apache.org>

Reviewers: Jia Zhai <None>

This closes #504 from sijie/mark_test_as_failures, closes #507

Descriptions of the changes in this PR:

(PR description content here)...

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue # or BOOKKEEPER-#>: Description of pull request`
>     `e.g. Issue 123: Description ...`
>     `e.g. BOOKKEEPER-1234: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install findbugs:check`.
> - [ ] Replace `<Issue # or BOOKKEEPER-#>` in the title with the actual Issue/JIRA number.
> 
> ---

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by jiazhai** [comment]
I will have a try

**Comment by eolivelli** [comment]
I am merging this into 4.5

**Comment by eolivelli** [comment]
are you trying too @jiazhai ?

**Comment by jiazhai** [comment]
what a coincidence for us to do it at same time, will close this, since it is merged.

**Pull request closed without merging**
